### ISSUE TITLE
Better support for bathymetry rendering 

### ISSUE THREAD

**Issue by epifanio** [AnalyticalGraphicsInc/cesium-ion-community#1]
I've tried rendering a bathymetry layer (1m resolution, at an average depth of -70m, referenced to the geoid). I uploaded the GeoTiff (Float64)and after few seconds I had it loaded in a cesium app, which is great! 
However, the file is not rendered correctly, no details are visible from the surface. Perhaps it is a scale/Z-exag issue? If you like to debug the issue, the file for testing is available here:  https://nextcloud.epinux.com/index.php/s/VYbnFy3X05Gbd0G

**Comment by tfili** [comment]
@epifanio Thanks for giving Cesium ion a try and for the bug report. I'll take a look at it and let you know what I find.

**Comment by tfili** [comment]
@epifanio I'm seeing you terrain show up. Terrain preview uses Natural Earth Imagery which can make it hard to see terrain that doesn't extrude much (or at all) from the globe. We are in the process of fixing this. We will probably end up using Sentinel-2 or something similar. Here is what I see:

![image](https://user-images.githubusercontent.com/1652382/39599376-aaf40db8-4ee9-11e8-90f3-998db5b3e893.png)

using the following code example
```javascript
Cesium.Ion.defaultAccessToken = '<INSERT YOUR TOKEN>';

var viewer = new Cesium.Viewer('cesiumContainer',{
    terrainProvider : new Cesium.CesiumTerrainProvider({
        url: Cesium.IonResource.fromAssetId(4309),
        requestVertexNormals: true
    })
});

viewer.scene.globe.enableLighting = true;
```

Cesium itself has issues with undersea terrain that we are working on improving. You can follow the following PRs/Issues in Cesium to better handle this use case

https://github.com/AnalyticalGraphicsInc/cesium/issues/5665
https://github.com/AnalyticalGraphicsInc/cesium/pull/6047

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This is still on the roadmap, and we're tracking it internally as well as in the above linked CesiumJS issues. For any follow-up questions, please use the community forum!
