### ISSUE TITLE
Adding support for CityGML files

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#10]
Hello,

Just as for SHP files, will Cesium ION support CityGML files? And I mean textured CityGML, so a ZIP containing GML + associated JPG files, such as :
https://download.data.grandlyon.com/files/grandlyon/localisation/bati3d/SATHONAY_VILLAGE_2015.zip
Downloaded from lyon Open Data from here:
https://data.grandlyon.com/localisation/maquette-3d-texturfe-de-la-commune-de-sathonay-village-mftropole-de-lyon/

Thanks,

**Comment by hpinkos** [comment]
Yes!  We've been working on a CityGML to 3D Tiles processor so this is already on our roadmap for ion.  Thanks for linking the data sets!  Those will be helpful for testing the processor before we roll it out in beta.

**Comment by mramato** [comment]
@fnicollet Our CityGML pipeline is now live on ion.  You can upload citygml/xml/gml files and their associated textures.

Unfortunately, the CityGML you linked to does not have SRS information embedded in the file, which means it will currently fail to convert properly.  However, detecting this and adding the ability to specify a specific SRS at upload time is something we would like to do.  I'm going to close this issue and open one specifically for data without a defined SRS.
