### ISSUE TITLE
Geometric Error of parent is smaller than children (ID 14533)

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#100]
The tileset with asset ID 14533 produces geometric errors that are not strictly decreasing down the tree. See this forum thread for more details:

https://groups.google.com/d/msg/cesium-dev/ZWyLkQNGmYU/0SovtPhAFAAJ

**Comment by LeonYuanYao** [comment]
Thank you for opening the issue. If you open the tileset.json tree and looking down at every first child. you'll find the geometricError from the root node to the last one is 1141.566 -> 13.651 -> 10.765 -> 8.573 -> 10.384 -> 19.649 -> 0.

**Comment by lilleyse** [comment]
@LeonYuanYao try re-uploading your asset using the BIM/CAD/Other option. The geometric errors are fixed and the tileset looks better in general.
