### ISSUE TITLE
Tiling issue with asset id: 14679

### ISSUE THREAD

**Issue by arzoomalhotra** [AnalyticalGraphicsInc/cesium-ion-community#101]
I added a 2D KML to your application and it doesn't work. 

Why is this the case?

**Comment by lilleyse** [comment]
Hi @arzoomalhotra

Cesium ion only supports KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip).

Until ion supports KML with vector data, you can load KML in CesiumJS directly with [KmlDataSource](https://cesiumjs.org/Cesium/Build/Documentation/KmlDataSource.html).
