### ISSUE TITLE
Tiling issue with asset id: 14799

### ISSUE THREAD

**Issue by gibranparvez** [AnalyticalGraphicsInc/cesium-ion-community#102]
I can't figure out why it won't accept my Erdas IMG file. It is georeferenced exactly like the previous one that I uploaded, asset 14689. Thoughts?

**Comment by lilleyse** [comment]
Hi @gibranparvez, according to [Uploading Data to ion](https://cesium.com/docs/tutorials/uploading/) raster terrain must be a single band of floating point or integer elevations.

It looks like your file has four bands, whereas the previous asset 14689 has one.
