### ISSUE TITLE
Tiling issue with asset id: 15080

### ISSUE THREAD

**Issue by gvanwagner** [AnalyticalGraphicsInc/cesium-ion-community#103]
<I have a simple KML file with polygons and placemarks with text behind them that I would like to layer in Cesium but it says it is having trouble with the data.>

**Comment by lilleyse** [comment]
Hi @gvanwagner 

Cesium ion only supports KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip).

Until ion supports KML with vector data, you can load KML in CesiumJS directly with [KmlDataSource](https://cesiumjs.org/Cesium/Build/Documentation/KmlDataSource.html).
