### ISSUE TITLE
Tiling issue with asset id: 15191

### ISSUE THREAD

**Issue by juheni** [AnalyticalGraphicsInc/cesium-ion-community#104]
Problem import buildings in Cesium Ion. Last week everything was ok. Now I get error: We're having trouble with your data. Buildings should be similar as before, I do not have any change with in my process. 
I import buildings with FME process. Buildings format are CityGML. Buildings are from same area as before. Building types as before and no texture. When problem starts, only difference was that there are few more buildings as before. Last time I tried to import same data as last week, which was ok. Now I got the same problem with that data also. I can not import any buildings. Can not understand where is the problem.

**Comment by hpinkos** [comment]
Hello @juheni, thanks for reporting this.  We recently published a new version of the tilers, and you may have found a regression.  @lilleyse will look into this further and give you an update.  Thanks!

**Comment by lilleyse** [comment]
Hi @juheni, the regression has been fixed. The failing asset is now fixed in your account.
