### ISSUE TITLE
Tiling issue with asset id: 15256

### ISSUE THREAD

**Issue by mholthausen** [AnalyticalGraphicsInc/cesium-ion-community#105]
It's a 3D object of a surface layer generated with Blender and exported as glb. Then I compressed it with the pipeline tool into a Draco mesh. The gltf-Viewer shows my object as generated (https://gltf-viewer.donmccurdy.com/). but with an internal error: Cannot validate an extension as it is not supported by the validator: 'KHR_draco_mesh_compression'.
When I upload this into the Asset Depot on Ion, I get the message:  We're having trouble with your data. To help fix it, please open an issue in our Github repository.
I want to create a 3D Tile of it, model type: BIM/CAD/Other
I tried to convert it into a b3dm myself, it's loaded (I see it in the developer tools) but not displayed in CesiumJS.

**Comment by lilleyse** [comment]
Hi @mholthausen, try uploading the glb without Draco compression.

The BIM/CAD/Other tiler expects input data to be uncompressed and applies Draco compression itself.
