### ISSUE TITLE
Tiling issue with asset id: 15293

### ISSUE THREAD

**Issue by jlwtyrens** [AnalyticalGraphicsInc/cesium-ion-community#106]
This data is generated from a bunch of Ifc-files and dwg, through FME to a CityGML.

**Comment by lilleyse** [comment]
Thanks @jlwtyrens, this looks like a similar issue to https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/56. We'll let you know once we have a fix.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
