### ISSUE TITLE
Tiling issue with IDs 15482 and 15484

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#107]
Posting on behalf of a community member [on the forum](https://groups.google.com/d/msg/cesium-dev/4vmmxnjDld0/LpGTaraPFQAJ).

> I have converted the data do DAE and uploaded both models to CesiumIon. In both cases there is an error during tileset pipeline. The assets ID are: 15482 and 15484. 
During creating the DAE files in ContextCapture I choose LOD (Level of detail) with Adaptive tree. Default the LOD was switch off.

**Comment by lilleyse** [comment]
In asset 15482 one dae is failing because it doesn't contain any geometry (`Model_L28_0001310200.dae`). It looks like 15484 has the same problem.

We recommend keeping the LOD option switched off since ion will generate the LOD tree.

**Comment by OmarShehata** [comment]
@lilleyse follow up from the forum:

> Hi, 
I have created the DAE files without LOD in ContextCapture and uploaded tchem into Cesium Ion. There ID are: 16218 and 16219. 
I think there are still some problems with loading the files. The loading of the testures when zooming in takes some time. What is more the textures are lacking details.

**Comment by mramato** [comment]
FYI, turns out that draco compression was being a little enthusiastic with this dataset, resulting in wavy geometry in the detailed area which could come across looking lower detailed.  We have a fix in the works and I'll bump this once it's deployed.

**Comment by mramato** [comment]
We have deployed the latest updates and re-tiling these assets will produce greatly improved results.
