### ISSUE TITLE
Support for Models with negative scale

### ISSUE THREAD

**Issue by tkazik** [AnalyticalGraphicsInc/cesium-ion-community#109]
Hi folks

First of all: Congratulations for the support of gltf 2.0, great work!
The second thing I would love to see is the support for models with negative scales, see this report for details and also an example model:

https://github.com/AnalyticalGraphicsInc/cesium/issues/6304

Any chances, that this will get a shot in the near future? Thx!

**Comment by tkazik** [comment]
Hey guys, a year has passed and I am wondering whether there is no interest in this issue. Any update? Thx!

**Comment by lilleyse** [comment]
@tkazik I'm going to close this issue, but we can keep the discussion going in https://github.com/CesiumGS/cesium/issues/6304.
