### ISSUE TITLE
Write FAQ for corporate firewalls

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#11]
Some ion users are behind corporate firewalls and need to know exactly which ports and DNS entries need to be included.

While we recommend *.cesium.com for future-proofing, that's not always the case.  As of right now, the specific subdomains would be:

cesium.com (ports 80 & 443)
api.cesium.com (ports 80 & 443)
assets.cesium.com (ports 80 & 443)

Bing maps also needs separate firewall settings because the actual tiles are still hosted by Microsoft.  Generally, I believe you can allow *.virtualearth.net (ports 80 & 443), but we should confirm if there is a tighter rule that can be defined.

**Comment by mramato** [comment]
Originally requested in this forum thread: https://groups.google.com/d/msg/cesium-dev/uprp6toccpI/Ir95kO5OCgAJ

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/what-are-the-ports-urls-used-by-cesium-ion-imagery-terrain/6932
