### ISSUE TITLE
Tiling issue with asset id: 15662 & 15663

### ISSUE THREAD

**Issue by nkwasey** [AnalyticalGraphicsInc/cesium-ion-community#110]
I am trying to upload a  3D tile in KMZ format, and a TIFF file but it keeps failing each time. I exported my generated and exported my file using photoscan.

**Comment by lilleyse** [comment]
Hi @nkwasey,

Asset 15662:

We only support KML with model placemarks at the moment (KML/COLLADA).

Asset 15663:

According to [Uploading Data to ion](https://cesium.com/docs/tutorials/uploading/), raster terrain must be a single band of floating point or integer elevations. If you are able to convert the tif to a single-band it should work.

**Comment by mramato** [comment]
As @lilleyse alluded to, both of these datasets are imagery, not 3D Models or terrain.  If you upload them as Imagery they will tile and load fine in ion.  I'm going to close this, but please let us know if you have any additional questions.
