### ISSUE TITLE
Tiling issue with asset id: 15870

### ISSUE THREAD

**Issue by andreafurla** [AnalyticalGraphicsInc/cesium-ion-community#112]
<Please provide a short summary of your data.>
[rete-commerciale.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2874927/rete-commerciale.zip)
Hi guys,
I export from Google earth pro this file (in KML version).
Into Cesium ion I've this alert
>  We're having trouble with your data. To help fix it, please open an issue in our Github repository.
Why?

Can you help me?

Many thanks,
Andrea

**Comment by andreafurla** [comment]
Hi guy,
sorry, I mean KMZ version...

Andrea

**Comment by lilleyse** [comment]
Hi @andreafurla,

Cesium ion only supports KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip).

Until ion supports KML with vector data, you can load KML in CesiumJS directly with [KmlDataSource](https://cesiumjs.org/Cesium/Build/Documentation/KmlDataSource.html).

**Comment by andreafurla** [comment]
Hi @lilleyse ,
how can I add this kml file to Cesium ion without conflicts? https://www.fareimpresavalbrembilla.eu/kml/rete-commerciale.kml
Is it write correctly?

Please, help me.
I'm not a developer...

Many thanks,
Andrea

**Comment by lilleyse** [comment]
I put together a quick glitch app that loads the KML into CesiumJS. Hopefully it helps until we support these types of KML in ion.

https://gleaming-seatbelt.glitch.me

See the code here: https://glitch.com/edit/#!/gleaming-seatbelt

**Comment by andreafurla** [comment]
Hi @lilleyse ,
you save me my day!!!

I change a little bit the code.
I add zoom control button set to fixed height value: 10km, 100km, 500km, 1000km, 2500km, 25000km.
Is there a way to make the (zoom) transition between height more fluid?

Here all my js code (without my Cesium.Ion.defaultAccessToken):
```
var rectangle = Cesium.Rectangle.fromDegrees(-20, 75, 40, 15)

Cesium.Camera.DEFAULT_VIEW_FACTOR = 0;
Cesium.Camera.DEFAULT_VIEW_RECTANGLE = rectangle;

var viewer = new Cesium.Viewer('cesiumContainer', {
    animation: false,
    timeline: false,
  geocoder: false
});

viewer.scene.screenSpaceCameraController.enableZoom = false;

var cartographic = new Cesium.Cartographic();
var cartesian = new Cesium.Cartesian3();
var camera = viewer.scene.camera;
var ellipsoid = viewer.scene.mapProjection.ellipsoid;
var toolbar = document.getElementById('toolbar');
toolbar.innerHTML = '<div id="hud"></div>' +
    '<button type="button" class="cesium-button" id="h1km">1km height</button></br>' +
    '<button type="button" class="cesium-button" id="h2km">2km height</button></br>' +
    '<button type="button" class="cesium-button" id="h10km">10km height</button></br>' +
    '<button type="button" class="cesium-button" id="h100km">100km height</button></br>' +
    '<button type="button" class="cesium-button" id="h500km">500km height</button></br>' +
    '<button type="button" class="cesium-button" id="h1000km">1000km height</button></br>' + 
    '<button type="button" class="cesium-button" id="h2500km">2500km height</button></br>' +
    '<button type="button" class="cesium-button" id="h25000km">25000km height</button>';

toolbar.setAttribute('style', 'background: rgba(42,42,42,0.9); border-radius: 5px;');

var hud = document.getElementById('hud');

viewer.clock.onTick.addEventListener(function(clock) {
    ellipsoid.cartesianToCartographic(camera.positionWC, cartographic);
    hud.innerHTML =
        'Lon: ' + Cesium.Math.toDegrees(cartographic.longitude).toFixed(3) + ' deg<br/>' +
        'Lat: ' + Cesium.Math.toDegrees(cartographic.latitude).toFixed(3) + ' deg<br/>' +
        'Alt: ' + (cartographic.height * 0.001).toFixed(1) + ' km';
});

function setHeightKm(heightInKilometers) {
    ellipsoid.cartesianToCartographic(camera.position, cartographic);
    cartographic.height = heightInKilometers * 1000;  // convert to meters
    ellipsoid.cartographicToCartesian(cartographic, cartesian);
    camera.position = cartesian;
}

document.getElementById('h1km').addEventListener('click', function() {
    setHeightKm(1);
}, false);

document.getElementById('h2km').addEventListener('click', function() {
    setHeightKm(2);
}, false);

document.getElementById('h10km').addEventListener('click', function() {
    setHeightKm(10);
}, false);

document.getElementById('h100km').addEventListener('click', function() {
    setHeightKm(100);
}, false);

document.getElementById('h500km').addEventListener('click', function() {
    setHeightKm(500);
}, false);

document.getElementById('h1000km').addEventListener('click', function() {
    setHeightKm(1000);
}, false);

document.getElementById('h2500km').addEventListener('click', function() {
    setHeightKm(2500);
}, false);

document.getElementById('h25000km').addEventListener('click', function() {
    setHeightKm(25000);
}, false);

viewer.dataSources.add(Cesium.KmlDataSource.load('https://cdn.glitch.com/465e4861-b3fc-4dfd-ab9d-61c71b9ec3be%2Frete-commerciale.kml?1550702366054',
     {
          camera: viewer.scene.camera,
          canvas: viewer.scene.canvas
     })
);

// Start off looking at Australia.
viewer.camera.setView({
    destination: Cesium.Rectangle.fromDegrees(-20, 75, 40, 15)
});

```

and here my html code:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <script src="https://cesiumjs.org/releases/1.54/Build/Cesium/Cesium.js"></script>
  <link href="https://cesiumjs.org/releases/1.54/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
</head>
<body>
  <link href="style.css" rel="stylesheet">
  <div id="cesiumContainer"></div>
  <div id="toolbar"></div>
  <script src="script.js"></script>
</body>
</html>
```



Many thanks,
Andrea

**Comment by andreafurla** [comment]
Hi @lilleyse ,
I've another question for you:
I add Cesium world into an iframe here https://www.fareimpresavalbrembilla.eu/cesium/

Why can not I scroll over cesium map?
Is there a way to solve this issue to scroll all page?

Note:
in my js I add this line of code
`viewer.scene.screenSpaceCameraController.enableZoom = false;`
to prevent zoom in cesium iframe when I use mouse wheel to scroll up and down.

Thank you,
Andrea

**Comment by lilleyse** [comment]
Hi @andreafurla, sorry for missing your questions. You might have better luck posting your questions to the Cesium forum if you haven't already: https://groups.google.com/forum/?hl=en#!forum/cesium-dev.

Since the asset issue is resolved I'm going to close this issue.
