### ISSUE TITLE
Cesium visualization issue with asset id: 2

### ISSUE THREAD

**Issue by phlahut** [AnalyticalGraphicsInc/cesium-ion-community#113]
<the viewport will down the earth.>

**Comment by lilleyse** [comment]
@phlahut do you have more information about the issue? Is this about Bing Maps Aerial (asset id 2) or one of your own assets?

**Comment by mramato** [comment]
Since we have not heard back, I'm going to close this, @phlahut please leave a comment if you have any more information and we can re-open if necessary.  Thanks.
