### ISSUE TITLE
Tiling issue with asset id: 16051

### ISSUE THREAD

**Issue by abuklea** [AnalyticalGraphicsInc/cesium-ion-community#114]
Error processing data in Ion. Building scan from a Faro scanner.. multiple scans merged into one using lastools

**Comment by lilleyse** [comment]
@abuklea - we fixed the problem and will you know once it's pushed out to ion.

**Comment by lilleyse** [comment]
Hi @abuklea - the fix is deployed. If you upload the asset again it will convert correctly.
