### ISSUE TITLE
Tiling issue with asset id: 16547

### ISSUE THREAD

**Issue by novelistparty** [AnalyticalGraphicsInc/cesium-ion-community#119]
It's a kmz made from ocean acoustics modeling tools. This kmz works fine in google earth

**Comment by lilleyse** [comment]
Hi @novelistparty,

Cesium ion only supports KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip).
