### ISSUE TITLE
Make delete button more obvious

### ISSUE THREAD

**Issue by Ed-Triplett** [AnalyticalGraphicsInc/cesium-ion-community#12]
I have not had any luck uploading any of my Collada files to Cesium Ion as models. One model worked as a 3D Tiles asset, but I was not able to repeat the success with the same model. Additional attempts to upload the model as 3D tiles failed. Are others having this issue? The files are not huge. The one 3dTiles asset that worked is 512KB.

*** I finally noticed the tiny trashcan icon at the top-right to delete the failed models. It might be useful to add this icon next to each asset in the list rather than above the preview window.

**Comment by hpinkos** [comment]
Hi @Ed-Triplett!  

Sorry you've been having trouble with the model converter.  Both the model converter and the 3D tiles converter are in beta right now, so we're still working on smoothing out some of the issues.  It would be very helpful if you could share the failed COLLADA models with us so we can use them to debug, but if you can't share them that's fine too.  Thanks!

To delete the asset, select the asset from the list then click the 'Delete' button on the upper right side of the screen

![image](https://user-images.githubusercontent.com/3451886/40432706-4f74649e-5e78-11e8-856d-719f9cc3566e.png)

Other users have had difficulty finding this button too, so you're not alone!  We plan to improve the user interface here to make it easier to figure out how to view, edit and delete your assets.

Best,

Hannah

**Comment by Ed-Triplett** [comment]
That is great. If you send a Dropbox or other Cloud storage link I am happy to share the COLLADA models with you for testing.

**Comment by hpinkos** [comment]
Thanks @Ed-Triplett! I'll get back to you once we have a chance to look at the errors

**Comment by OmarShehata** [comment]
The asset table now has a delete button in each row when you hover over it, in addition to the delete button in the top right in the preview window.
