### ISSUE TITLE
Photogrammetry with large texture fails to tile

### ISSUE THREAD

**Issue by bosscq** [AnalyticalGraphicsInc/cesium-ion-community#123]
obj exported from photoscan in local coordinate system. Asset ID 16671.

**Comment by lilleyse** [comment]
Thanks @bosscq, we're looking into it.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
