### ISSUE TITLE
Tiling issue with asset id: 16712

### ISSUE THREAD

**Issue by skybluego123** [AnalyticalGraphicsInc/cesium-ion-community#124]
<Please provide a short summary of your data.>

I upload several building model formed by collada(.DAE) file format for combining one 3D Tile on cesium ion assets.

However, a process of converting collada to 3D tiles occurs an error with this information box ' We're having trouble with your data. To help fix it, please open an issue in our Github repository.'

And also, I want to adjust tileset location of my uploaded 3D tile in cesium ion based on my csv file that includes coordinates of every building model. 

I attached my 3D building model made by collada (.dae) file format and csv file that include coordinates of every building model.
[3D building model.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2912177/3D.building.model.zip)

**Comment by lilleyse** [comment]
Hi @skybluego123,

The error will be fixed in the next update of the BIM/CAD tiler.

However since we don't yet take CSV+COLLADA input in ion the buildings will all appear on top of each other.

**Comment by lilleyse** [comment]
@skybluego123 this issue is fixed and the asset is now working in your account.
