### ISSUE TITLE
Tiling issue with asset id: 16866

### ISSUE THREAD

**Issue by Rebeccafrgr** [AnalyticalGraphicsInc/cesium-ion-community#125]
It's a Geotiff file with coordinates in geosystem EPSG2100

**Comment by lilleyse** [comment]
Hi @Rebeccafrgr,

The error we're seeing is: `Raster terrain and imagery must be in a North-Up projection`.

This may be due to the GeoTransform embedded in the GeoTIFF. We're looking into ways to correct the data automatically on our end.

**Comment by mramato** [comment]
We have a fix for this (appears to be overly aggressive data validation on our end).  I'll comment here and close the issue once everything is deployed.  Thanks for letting us know @Rebeccafrgr!

**Comment by lilleyse** [comment]
Hi @Rebeccafrgr, the fix was deployed. If you upload the asset again it should convert correctly.
