### ISSUE TITLE
Tiling issue with asset id: 16909

### ISSUE THREAD

**Issue by bonfigli** [AnalyticalGraphicsInc/cesium-ion-community#126]
Terrain tiling progress is stuck at 87%

**Comment by bonfigli** [comment]
Now it says job timed out. Would it be possible to get more info in case something goes wrong with the tiling? Otherwise it's hard to understand what's happened and where the problem is.

**Comment by lilleyse** [comment]
@bonfigli

The source data is fine and it converts locally. There was an internal error on our end that we're looking into. Once we have a fix we'll reconvert your data and let you known when it's ready to use.

**Comment by bonfigli** [comment]
@lilleyse Thank you for your support. The problem happened also with asset id 17159. Also I've sometimes noticed that in case of errors trying again to upload the same asset may result in a successfully completed procedure.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
