### ISSUE TITLE
Vector tiling

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#130]
This is a meta-issue for vector data tiling into 3D Tiles vector payloads.  We absolutely plan to have this feature in ion at some point in the future, but for now this issue can be a place for users to mention their interest as well as link other related issues and have a general overall discussion.

Initial thoughts regarding format support would be:
* GeoJSON
* Shapefiles
* KML Points/Lines/Polygons

Uploading these to ion would create a 3D Tiles tileset, optionally clamped to terrain, which could be efficiently streamed to clients.

**Comment by fnicollet** [comment]
Just leaving a comment to receive notifications (I submitted 3 of the 4 issues which has been closed in favor of this one). ION was quite disappointing when we tried it (not having the hability to use vector files was a major issue to us), so at the moment we are just not doing any 3D. If ION gets better at handling GIS files, I guess we'll have another look :)

**Comment by AJJackGIS** [comment]
quite agree with @fnicollet , for many GIS engineers, geojson , shapefiles is the most common files, as far as i kown,  there has a some teams/organizationes already developed tools for the shp -> 3dtiles converter,so there will be great if cesium ion has the ability

**Comment by nhenry012** [comment]
This would be a great feature for my clients as they are accustomed to exporting kml from their cad software for use in Google Earth and those kmls use polygons to render the shapes. It seems like it has been a while since the last comment on this thread, has their been any traction on this issue?

**Comment by OmarShehata** [comment]
@nhenry012 vector tiling isn't supported yet, but you can now upload KML/GeoJSON/CZML directly on Cesium ion: https://cesium.com/blog/2019/10/25/upload-kml-geojson-czml/

**Comment by nhenry012** [comment]
@OmarShehata we are currently using Cesium to render some kml models. However our larger models tend to either slow Cesium down to a crawl or, in several cases, they cause the browser to eat up so much memory that the webpage crashes and tries to refresh itself. I do not think that this is Cesium's fault but rather just a facet of working in kmls with large numbers of polygons. I think that the best way I can get away from that is by using this Cesiums kml tiling when it becomes available.

**Comment by OmarShehata** [comment]
Yes, tiling these larger KML datasets is ultimately the ideal long term solution. This is still on our radar, but we don't have a specific timeline for it at the moment. I appreciate you voicing your interest here @nhenry012 .

**Comment by nhenry012** [comment]
@OmarShehata Thank you for the response. I am specifically interested in converting Navisworks exported kml files to map tiles because that provides me with a simple effecient path from Autocad to Cesium. It would be great if the converter could recognize individual Autocad assemblies in the kml file as features in the tileset so you can pick out assemblies on the globe the same way that you can pick out buildings in the New York example on the sandbox.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/support-tiling-vector-data-into-3d-tiles/10522. You can subscribe to that topic to be notified for any updates on this.

**Comment by AsoVaisi95** [comment]
I am currently working on a WebGIS application using CesiumJS with data stored in PostGIS. My backend serves data as Mapbox Vector Tiles (MVT), for example via a tile service such as Martin (XYZ `{z}/{x}/{y}` endpoints).

I understand that CesiumJS does not natively support rendering 2D vector tiles in the same way as MapLibre or Mapbox GL, and that the recommended and well-supported format in Cesium is 3D Tiles.

However, I would like to ask for clarification on the following points:

1. Is there any official or recommended approach for visualizing **2D vector tiles (MVT)** in CesiumJS today , or is this intentionally out of scope?
2. Are there any plans or roadmap items for **native vector tile support** in CesiumJS?
3. For use cases where the data is fundamentally 2D (e.g., parcels, cadastral layers, administrative boundaries), is the recommended workflow to:

   * Convert the data to **3D Tiles** (even with minimal or zero extrusion), or
   * Render the data externally (e.g., MapLibre) and integrate it into a Cesium-based application as raster imagery?


I have experimented with third-party solutions (such as vector-tile-to-imagery approaches), but I would prefer to follow an officially supported or recommended pattern if possible.
