### ISSUE TITLE
Ability to upload models and convert them to glTF

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#131]
ion can take obj, dae, and glTF models and tile them into 3D Tiles, but there are some use cases where you simply want to create a glTF model rather than a 3D Tiles tileset, for example it could be a very small model and not worth tiling or you are using a client that only supports glTF.

**Comment by OmarShehata** [comment]
Does that mean we'll consider allowing users to upload untiled vector data for the same reasons stated here? (it's a small CZML/GeoJSON file, not worth tiling etc.)

**Comment by OmarShehata** [comment]
This is now supported! Including both serving as glTF as well as uploading and hosting CZML/GeoJSON and KML. See: https://cesium.com/blog/2019/09/17/ion-gltf/ and https://cesium.com/blog/2019/10/25/upload-kml-geojson-czml/
