### ISSUE TITLE
Options to add information to batch table?

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#132]
Right now, ion doesn't let you decide what information should be added in the batch table. It might be useful in some cases to embed more information, but perhaps not by default so as not to bloat tile sizes unnecessarily.

For example, in this [forum thread](https://groups.google.com/d/msg/cesium-dev/ZVLLiG8Dznk/fQYGPP1YBQAJ), the goal is to get the boundaries of buildings. I believe the building tiler will compute lat/long/height and put those in the batch table, but nothing else. 

Is this a good idea? This could potentially be a pretty open ended thing. Are there other kinds of data we might commonly want to add to the batch table?

_Edit: was confusing batch/feature tables_

**Comment by lilleyse** [comment]
Another case here is preserving glTF metadata in the CAD tiler. Which itself is open ended - would it only work on node extras?

**Comment by OmarShehata** [comment]
Requested again for the CAD tiler here, to be able to click to highlight individual models: https://groups.google.com/d/msg/cesium-dev/JatWIqy_coE/U4jK6C5qEQAJ

**Comment by OmarShehata** [comment]
Requested again here, to be able to add metadata in an OBJ/DAE. I think if there was a way to do it with glTF that would be sufficient. In this case, the models here are buildings, and the metadata would be building names/IDs: https://groups.google.com/d/msg/cesium-dev/zZqhaCmtZMY/ppy0R4CmEgAJ

**Comment by OmarShehata** [comment]
For preserving glTF metadata, there's at least one Blender plugin that will import Shapefile metadata like longitude, latitude and projection and embed that into the `extras` of each node. There's some discussion on this in this forum thread:

https://groups.google.com/d/msg/cesium-dev/TUXFisw3P-0/bgd-IiE4BgAJ

This uses the BlenderGIS plugin: https://github.com/domlysz/BlenderGIS

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're definitely interested in expanding the metadata that the Cesium ion 3D tiling pipeline reads and outputs. If you have a specific question about your data you don't see the answer to in our docs or on the forum, please open a new topic on the community forum!
