### ISSUE TITLE
Tiling slowly then failed when choosing Cesium World Terrain as base terrain, asset ID: 18111

### ISSUE THREAD

**Issue by dylandong12** [AnalyticalGraphicsInc/cesium-ion-community#134]
Hi, I am trying to show a terrain asset on top of the Cesium World Terrain. The asset is only 3.5MB. It has been a day and the tiling process is only 57% done. Now it shows an error with "We're having trouble with your data."

The reason why I choose Cesium World Terrain is that my terrain asset looks much taller than the neighbor terrain if I choose WGS84 Ellipsoid as the base terrain. I assume it is because the WGS84 terrain does not have the bumpy effect. So I select Cesium World Terrain as the base terrain and want to see what the tile looks like.

**Comment by lilleyse** [comment]
Hi @dylandong12, this was a recent regression that has been fixed. All assets that were affected have been re-run and asset 18111 is now fixed in your account.

Now we're looking into what appears to be a terrain artifact in your data. Possibly a data issue or a tiler issue. We'll get back once we know.

**Comment by dylandong12** [comment]
Thanks @lilleyse , just a quick question, what is the difference between Cesium World Terrain and the WGS84 Ellipsoid base terrain? I notice that if I put my terrain asset on top of the latter, the asset will look like very very tall compared to the surrounding neighbor.

**Comment by lilleyse** [comment]
The WGS84 Ellipsoid is a globe without elevation so most terrain data tiled against it will have that extruded look.

Cesium World Terrain contains real-world elevation. More info here: https://cesium.com/content/cesium-world-terrain/.

**Comment by dylandong12** [comment]
Thanks @lilleyse !
