### ISSUE TITLE
Cesium visualization issue with asset id: 18581

### ISSUE THREAD

**Issue by balajiputhiran** [AnalyticalGraphicsInc/cesium-ion-community#137]
<Please provide a short summary of your data.>

i have kml , gml , Shapfile , geojson data . When i am uploading it's not working on cesium ion .It's showing error after processing data.So please tell me how to upload data in cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Map Pins.html&label=Beginner

**Comment by lilleyse** [comment]
@balajiputhiran what error are you seeing?

Note that one of your KML files doesn't have any models in it and so won't get included in the tileset. However if you load that KML separately in CesiumJS you'll see it.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var options = {
    camera : viewer.scene.camera,
    canvas : viewer.scene.canvas
};
viewer.dataSources.add(Cesium.KmlDataSource.load('<url to 3d.kml>', options)).then(function(dataSource) {
    viewer.zoomTo(dataSource);
});
```

**Comment by lilleyse** [comment]
@balajiputhiran I'm going to close this for now, but let us know if you have any questions about this.
