### ISSUE TITLE
Tiling issue with asset id: 18669

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#139]
Opening on behalf of forum user:

https://groups.google.com/d/msg/cesium-dev/DZfSgIWi6MI/4zLZpIZiCgAJ

> Unable to add dsm data to ion.What could be  the reason for the error.

**Comment by lilleyse** [comment]
Thanks @OmarShehata, we're looking into this.

**Comment by mramato** [comment]
This issue is fixed, but the original asset was deleted by the user.  @OmarShehata please follow up on the forum and let them know.  Thanks.
