### ISSUE TITLE
Additional ways to upload pre-existing terrain tilesets

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#14]
There was a request on the Cesium forum for how to upload existing terrain tilesets that were not `.terraindb` files: https://groups.google.com/d/msg/cesium-dev/mt8YKJO8bMo/z6VmKRgaBQAJ

Support for uploading a directory of terrain is most likely not a good avenue because of the amount of files and requests needed.  One possibility is to document the `.terraindb` spec so that users who which to generate their own `.terraindb` files can do so.

Zip file support could also be a possible solution, but may have security implications.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're interested in this feature, please open a new topic in the community forum!
