### ISSUE TITLE
question: roadmap

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#140]
I was about to drop a question about future features for Cesium Ion, but I thought I could instead ask you guys if there's somewhere where the roadmap and releases are documented so we can check there.

If that's not the question, is this the right place for such questions?

**Comment by hpinkos** [comment]
Hello @pablocbre,  we have a Changelog published in ion.  A link to this can be found in the footer: https://cesium.com/ion/changelog 
We update this when major features and improvements are deployed.

We don't have a public roadmap at this time, but are happy to answer any questions you have!  This is the right place to ask questions about Cesium ion, and you can also ask questions about anything Cesium related on our forum: https://groups.google.com/forum/?hl=en#!forum/cesium-dev

**Comment by pablocbre** [comment]
Great, I think we can close this and I'll create new ones for my other questions. Thanks Hannah.
