### ISSUE TITLE
Tiling KML/COLLADA with textures

### ISSUE THREAD

**Issue by alisimsek** [AnalyticalGraphicsInc/cesium-ion-community#141]
Hello
I am trying to create a tileset using KML/COLLADA files with corresponding textures(.png). However i am unable to create a tileset with textures. When i upload COLLADA/PNG files together, i can get models with textures without any problem. But i need to specify the locations using KML  files and textures are not loaded when i upload 3 file formats together.
Do i need to create COLLADA models with embedded textures or are there any solutions for this problem ?

Thanks

**Comment by lilleyse** [comment]
@alisimsek You should be able to load all the files at once including the texture files. Could you send us the asset id for the time you uploaded the 3 file formats together?

**Comment by alisimsek** [comment]
@lilleyse 19781. 3 files are uploaded(kml, dae, png).

**Comment by alisimsek** [comment]
@lilleyse Now i can see that they're actually loaded but not properly. Textures are so pale that i can barely see them.

**Comment by lilleyse** [comment]
Yes I'm seeing that as well. The problem is the emission and ambient colors in the DAE file are really strong. If you remove the lines it looks a lot better.

```xml
<emission>
    <color>1 1 1 1</color>
</emission>
<ambient>
    <color>1 1 1 1</color>
</ambient>

```

**Comment by alisimsek** [comment]
@lilleyse Yeah that works perfectly. Thanks a lot. 
I want to ask one last thing. When i add .dae and .png files together, it looks perfectly fine but why does it look so pale when i add .kml file with them?

**Comment by lilleyse** [comment]
It depends on whether you selected Photogrammetry or BIM/CAD/Other in ion. Photogrammetry looks good because it creates it's own unlit materials that ignores emission and ambient. But BIM/CAD/Other has the same pale color as KML.

**Comment by alisimsek** [comment]
@lilleyse Thanks a lot for your helps.

**Comment by pioclaudio** [comment]
Hi @lilleyse I uploaded a KMZ file generated from Google Earth and tiled it but textures are not displayed. You can see it at 126212.   Is there a solution for this problem?

**Comment by OmarShehata** [comment]
@pioclaudio thanks for reporting. We'll take a investigate and let you know what the issue is there.

**Comment by pioclaudio** [comment]
Hi @OmarShehata Thanks for looking into this. On my end, I tried changing the texture references in DAEs and removing the KML "ResourceMap" mappings and then textures get shown (126260). It looks like "Alias" are not being interpreted correctly.

**Comment by OmarShehata** [comment]
Thanks for confirming @pioclaudio . It looks like the original asset referenced the images with the prefix `untitled/`, but the images were in the same folder, so that caused the incorrect path to the images. The updated asset does not have this prefix.
