### ISSUE TITLE
Question: upload through API

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#142]
I wanted to know if there's any way to upload assets to an ION account through an API. Dropping files via the web UI is good enough for development. But without a way to refresh data automatically, apps with quick-changing resources can't be developed (unless you make someone spend 10 min a day doing it manually, which doesn't seem very elegant).

**Comment by hpinkos** [comment]
@pablocbre yes, we do have a REST API for ion that is designed for handling this kind of use case.  We are actively working on making the API public, and will have documentation published before the end of this month.  We'll give you an update when it's ready.  Thanks!

**Comment by pablocbre** [comment]
Great, thanks for the details Hannah. Looking forward to it.

**Comment by mramato** [comment]
@pablocbre we have officially released the REST API: You can read all about it and get started in our blog post: https://cesium.com/blog/2019/04/24/rest-api/
