### ISSUE TITLE
CityGML fails when there are too many files (asset id: 19913)

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#143]
CityGML with many buildings. What seems to be the issue?

**Comment by lilleyse** [comment]
Hi @pablocbre,

We're not sure what the issue is yet but we're starting to look into it.

**Comment by pablocbre** [comment]
Ok, thanks. Looking forward to it.

**Comment by pablocbre** [comment]
Hi Sean. A solution for this from your side would be great, but, if in the meantime is there any workaround I can implement on my side, I would be thankful to have that while you guys dig into the problem.

Thanks

**Comment by lilleyse** [comment]
@pablocbre It looks like the problem is caused by the sheer number of CityGML files and not the data itself. It's something we need to fix on our side.

A workaround is to combine as many of the CityGML files together as possible. Even one very large CityGML should work.

**Comment by pablocbre** [comment]
@lilleyse ok, I'll try that. Though it would be quite convenient to be able to upload them as individual ones down the road.

Thanks for your feedback

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
