### ISSUE TITLE
Question: utf-8

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#146]
Hi guys. I tried to upload a CityGML encoded with UTF-8 and an error occurred when tiling.

I was wondering if Ion supports UTF-8. If not, how can we upload content with characters such as á é ü etc?

Thank you

**Comment by shehzan10** [comment]
Hi @pablocbre. The tiling pipeline does allow UTF-8 files. Can you give me the asset number so I can test it out?

**Comment by pablocbre** [comment]
20547.

The error message states:
`Additional Information: invalid byte 'A' at position 2 of a 2-byte sequence, Line 1, Column 1`

**Comment by shehzan10** [comment]
Hi @pablocbre. Looks like the file is in ISO-8859-1 rather than UTF8.

```
file -i 20547.gml
20547.gml: text/plain; charset=iso-8859-1
```

I converted this to UTF8 using
```
iconv -f ISO_8859-1 -t UTF8 20547.gml -o 20547_utf8.gml
```

The UTF8 file then works correctly through the tiler and the properties include UTF8 text.

**Comment by pablocbre** [comment]
Hi @shehzan10. Okay, that means I got confused and I was actually already updating my assets in UTF8 (such as in assets 20541).

The original question came motivated by a problem that's still alive. Using the same sandcastle you recently shared with me in a different issue, when I print some buildings metadata, I'm getting a strange behaviour:

- Buildings in a CityGML have an attribute called 'building', where they store their name. 

- I upload them to Ion an consume them as 3DTiles. When printing the features properties on the CesiumJS viewer, most of them show fine. So 'Town Hall' prints as 'Town Hall'.

- But those with non-ascii chars only store the chars after them. So, 'Gúeran' prints as 'úeran' and 'Corporación 3' prints as 'ón 3'.

- If you look for specific examples back on the original CityGML file, the names appear correctly ('Gúeran' is 'Gúeran' and 'Corporación 3' is 'Corporación 3'). 

So, that's the issue I'm facing. I'm not sure about whether I can give you any extra details that could help.

**Comment by pablocbre** [comment]
Hi @shehzan10. Okay, that means I got confused and I was actually already updating my assets in UTF8 (such as in assets 20541).

The original question came motivated by a problem that's still alive. Using the same sandcastle you recently shared with me in a different issue, when I print some buildings metadata, I'm getting a strange behaviour:

- Buildings in a CityGML have an attribute called 'building', where they store their name. 

- I upload them to Ion an consume them as 3DTiles. When printing the features properties on the CesiumJS viewer, most of them show fine. So 'Town Hall' prints as 'Town Hall'.

- But those with non-ascii chars only store the chars after them. So, 'Gúeran' prints as 'úeran' and 'Corporación 3' prints as 'ón 3'.

- If you look for specific examples back on the original CityGML file, the names appear correctly ('Gúeran' is 'Gúeran' and 'Corporación 3' is 'Corporación 3'). 

So, that's the issue I'm facing. I'm not sure about whether I can give you any extra details that could help.

**Comment by shehzan10** [comment]
Hi @pablocbre

I don't see either of the buildings you mentioned in the in source files of either 20541 or 20547.

In the 20547 file, one example I found was `building: DIPUTACIÓ 353` being printed correctly.

However, this may still be an issue. Do you think you can isolate the 2 buildings you mentioned into a separate CityGML file and upload it? We can run some further testing on it.

PS. I downloaded 20541 and the encoding seems to be ASCII, not UTF-8.

**Comment by pablocbre** [comment]
Hi @shehzan10, if you:

- Use the [Sandcastle example](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html#c=1Vhtb9s2EP4rXPbBcmvTXdsBg5MUcx1nMZrEXqJk65YhoCXaJiKRAknlpUP++46iKFGyvTXbpwUIZPHunnvh3fGoMVUsT/FUcBzTJckTPYoiqlQo7ihHh6jzeXZ1cRvOPk3Ob08mF5PO/g2/4fdEontGH6gEFk4f0NjCXBdrQScqXseCa8I4lZ1uJaUiyikIWWlcvAKRLVHwTfGCMxbdzYVimgl+mWeZkJrGXfTnDUfwFwmuREJxIlZBJ1wzhRZSPCgwJBZUIS40UlYI+UC4MOHZWGG1rBKxoOByptchVXq0AkOVDqmU8APs0zKnDVfPREwTIJR2SLZa63ECKkaRUTBEHcJBO9G007MsKYvjhDZ51iymHTCkgC6DdsdFdCdyjbUk0V1QKauDpoVIFsTEOhZRnlKu8YrqSULNz49P0zjolCyFm21ckmXJ00fGY8ZXqsbvOdxaUekC2KpAWbkfkqUQw3uqMInjwNvtU7KgyVgkCS3cC7qexSyhiurWRrexbJw8RPt4dxRa8aAMtvnLZTJ0bJCtF1SJXEYUL6VIRwqYIQqDVyZb+6PLy0nYnx71TcK+GnR7NUpKHlmap5eRpJRfZiSiEymFHKIfLM9z94aXXli7vwiRhiIo/elaLiz0msoHpmiwzHnhPAqoAarytJ2rlrrvtFSBWhMOSdIqI9+8e9jiE8sUlDZFBESVxSjlsQkAz3JtM60yK0jFfZEllWFG6ZISnUtabzGkaMWJs7JmnLVFbZaWQY+Ago6DEqHb8FdSWOPOR2OdU0hsjA7rSsLtAvKUOe7DQ6+oGprcamV0z/lUhRjRRNENuEyKjErNqGoCQmJyPa+IL8Y1adJENCt/AwM9oLdru8OnjOKL6U8n4e34dDr+9D/f6Y0+uGOri97YUFPqxmotHgBySSD0Xx3As+nR0enEj2BVq3+TPk69Me5rziPnd0RgWTHCG6F2crtDbnUFraBXaN2up8fXJVaSZGsWgTrXO73VoiuOHYgHt7+JtqamEgHHh8V2FWtxzB7BoLdd9Bp1UGqPfx/COzKKnt6ytyiu0mc0rMPU22TT9FEDi9W8hW6y4COckCspch4Dpzmjt/AtYewAaue799kjSgUXyiRGZwvnWkj2xQwpyQzaETMGlsE8aVHw6eQ43IJwb/pFtCl/3VjHH2dhODvbIh8zRRYJPXJzyBFTmvCIAtJ5ni6g3Oezy2k4vZ7cTs+Pp+fT8HMT5Nnf0ue6Nhr5/s/dbet4VUsMO06NyZiyiT6dk5SaOcGVKcwkc58U+EIJ5Su9Bu6GNLbLJd9SSBQYZgZ8b/bhcVDK7aPXr9lG0flQbeTf2R/724/iDoJMft0UhuQeFqtbfAl8zm633fUGAzS5J0kO/aRqtzFVkWSZCf6WuB7VVGS1luMFVvoJmFKqCfYgMC3x62a8397iHceNfxYkgq+YzmNa94wzotdQ4xckhpJUwTbnO5VYp9vYT6j5fwFWSjWxqha0VcZSyztEtfVlTxk3e6E/S3qUoHKiVxnec2pfoTf4+0Z+u37lWrm9LNAkYZkSLMZ+pwxF3We3GdU0O4IUkqQCtq+NSBAzpRfd2JBwueBbx3S0rhmK14YOsVza0dv+OIaj4MSizA3vBeErGpS4PQvnxeItftM0GW4lXEFlpvVOh25JYUqUPocjcX2VhfasOJZgWNA+5+ockezxPU7hosnMreRpLqA3BZWSXml1D/kIZRFZj5fJE0zkXiuAUtGMk7KenJzXbaGZQ1U4htYJ5UI+dL9abdrGe2ifXq/12CAIIHfsarE6BSaNdfzz1ejoYhROx7ezq9C7CTQr+SW7Js1qVeQuM/x6jBKSZkHJ3vcp8+nt7HoCd/tfZj20g+B2r05Ln/ELlSIU4YOYM2dZF/V3YTXL1xj0M/S0GtK8UclNoIo73SNTI75KaODVc1Fm7/AVnIO3n8GfAqa7WT//Dfk3QHb+eNhS6J24Lp8Dz4Be7WXPN6yFaUuiEVp4f1eYWmsISu3d7aW+6UkELW+nh79uLct3Xllew51eyKCyr65L+2wBeAo4XZmj6mvZa5WXMC8RWQkWud2WtxePctGVzl5v76A4OT9Yph9ZWnwAymUSYDzQNM2g6VM1WOTRHZyykVIO71v3acVrCotqxhwiuVqQ4P3bHnL/b/AP/sSVwcgL2zpEMGt6ywshYyr7EvY8Vz7xuaW26O+0od6Mr/2Hoh0PASiJN9X1tciG6PuGSkdaCK1F6lNB58HAxecgZveIxYc3e61vdDd7CHqFUkBZ5klyyb7Qm70PBwPgb4glokjkGUy+CXkyLOvvPpzaRYzxwQBeN6VKf4Hd2lRQnD4bA6BdFGdQZG6K5UVy6KCc0IcDZi6/SMMVD0RNhAWYbgYk8+5udrAUE036C8YLX9cUdt7sZ+urAygdlSIv1FR/SXiBrrkZxJGZ74zECzWaEe8Fun4DdqSFm6nayjajf1bc0/9T+M0VfpeJG58BQOUJ8LcNdM+/AA) to visualize asset 20541

- Use the geocoder with the following text (353 Cl Diputacio, Barcelona, Spain) to travel to that building.


- Print the metadata on the building.

You'll see the same "DIPUTACIÓ" 353 being cut (and appearing as "Ó 353"). 

![image](https://user-images.githubusercontent.com/43879499/56197432-1a2bef00-6039-11e9-864f-164204a9cb57.png)
![image](https://user-images.githubusercontent.com/43879499/56197469-2e6fec00-6039-11e9-9a06-b10c561ec459.png)

**Comment by shehzan10** [comment]
Hi @pablocbre 

I think this is a result of the file being in ASCII encoding. In the 20541 asset, the string attribute is
```
<gen:stringAttribute name="building"><gen:value>PASSEIG SANT JOAN 39-41/DIPUTACI&#211; 355</gen:value></gen:stringAttribute>
```

> Note: `&#211;` is the Numeric Character Reference for `Ó` https://en.wikipedia.org/wiki/%C3%93

Whereas in the 20547 asset, in both ISO-8859-1 and UTF-8, the attribute is
```
<gen:stringAttribute name="building"><gen:value>PASSEIG SANT JOAN 39-41/DIPUTACIÓ 355</gen:value></gen:stringAttribute>
```

I am able to reproduce `DIPUTACIÓ 353` being shown as `Ó 353` for 20541. But in 20547, `DIPUTACIÓ 353` is printed correctly.

I also tried converting the 20541 ASCII file to UTF-8 and ISO-8859-1, but since ASCII is a direct subset, iconv doesn't convert the file.

I then tried to find-and-replace all `&#211;` with `Ó` in the file. The running this through the tiler also produces the correct strings.

So I think your best option is to export UTF-8.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

I believe the original issue was resolved here, but if you have any follow up questions please post in the community forum!
