### ISSUE TITLE
Zoom to terrain after tiling

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#152]
The ion asset viewer can zoom to the terrain you tiled because it stores the extents before tiling. You can't do this in your application because it gets merged with the base layer and you lose information on the extent.

I believe this will be possible once the REST API is released, so developers will be able to access this metadata and zoom in accordingly.

Forum thread: https://groups.google.com/d/msg/cesium-dev/anU7NLM79iw/SiZPb_zxDAAJ

**Comment by OmarShehata** [comment]
@mramato it looks like this is not exposed yet with the new REST API? But looking at the network tab, it looks like the route `/extent` does exist. So I can do:

```
https://api.cesium.com/v1/assets/<id>
````

To get metadata on the asset ID, and then do:

```
https://api.cesium.com/assets/<id>/extent
```

To get the rectangle extent.

This was [requested on the forum here](https://groups.google.com/d/msg/cesium-dev/IWKQMr_8SZI/eq26kgQKDAAJ).

**Comment by mramato** [comment]
The main issue here is that a CesiumJS terrain tileset is always global, even if it doesn't look like it from the end user perspective.  Terrain always covers the entire globe.

We definitely want to have the ability to zoom to just the parts of the terrain the user might care about (i.e. the tiles they uploaded for processing) but it's not part of the REST API yet and it's something that requires some thought.  It may ultimately have to go into the terrain's layer.json instead.

The endpoint you listed is private and will definitely change at any time, we do not officially support it and it's not something I would encourage anyone to use.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

For getting the bounding box from an asset with the REST API, we have a feature request for this you can subscribe to here: https://community.cesium.com/t/get-bounding-box-for-asset-through-cesium-ion-rest-api/10386
