### ISSUE TITLE
Support Cesium Ion Content streaming to Unity or Unreal

### ISSUE THREAD

**Issue by donrv** [AnalyticalGraphicsInc/cesium-ion-community#154]
Need a feature that Support Cesium Ion Content streaming to Unity or Unreal

**Comment by OmarShehata** [comment]
Thanks for opening this feature request @donrv! This is definitely something on our radar but we don't have a specific timeline for it at the moment. The new [ion REST API](https://cesium.com/blog/2019/04/24/rest-api/) is a step in this direction in that you can now stream the data to any platform, but it'll only work if the engine supports loading 3D Tiles.

What kind of data are you hoping to stream into your Unity/Unreal projects? 3D Tiles? Terrain/quantized mesh? Something else?

**Comment by Lildreas** [comment]
Hi Omar,
I just pitch in, we would be interested in using 3D tiles in Unreal Engine to build a flight simulator. Maybe we could even work with you to make this happen?
Best from Germany
Andreas

**Comment by OmarShehata** [comment]
That sounds like an interesting use case @Lildreas! 

If you're trying to work on implementing it yourself, the specification is a great place to start: https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification and CesiumJS as an open source implementation is also a great reference. Let me know how it goes!

**Comment by Lildreas** [comment]
Hi Omar,

thanks for the lightning fast response!

The specification looks very good, it will be really helpful. 

One more question: Do you know of a C++ implementation to render the 3D tiles? I so far only found C++ code for the pipeline to create 3D tiles. If not I guess we'll have to do it on our own.

Thanks & best
Andreas

**Comment by OmarShehata** [comment]
I don't believe there is one as far as I'm aware. Feel free to share any progress you make here, on the forum (https://groups.google.com/forum/#!forum/cesium-dev) or on [twitter](http://twitter.com/CesiumJS)!

**Comment by Lildreas** [comment]
Ok. Thanks for the feedback, and if we decide to do it we will contribute to the project. :-)

**Comment by OmarShehata** [comment]
We're currently working on this! See: https://cesium.com/blog/2020/06/04/cesium-for-unreal-engine/

We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/cesium-for-unreal-engine/9814

**Comment by Lildreas** [comment]
Hello Omar,

Thanks for the update! I will now watch the forum entries for this, it’s awesome that you’re working on this!

Best
Andreas


Dipl.-Ing. Univ. Andreas Freiherr von Lepel
Simulator Software Engineer
+49 175 850 3886 <tel:+491758503886>
lilium.com<https://lilium.com>

[Divider]
[Lilium Logo]<https://lilium.com/>

Lilium GmbH | Claude-Dornier Str. 1, Geb. 335 | 82234 Wessling | Germany
Sitz der Gesellschaft: München, Deutschland | Amtsgericht München HRB 216921
Geschäftsführer: Daniel Wiegand | USt-ID (VAT) DE299517739

> Data Protection Information<https://lilium.com/privacy-policy>
This e-mail is intended only for the use of the addressee and may contain information that is privileged and confidential. If the reader of this e-mail is not the intended recipient or the employee or agent responsible to deliver it to the intended recipient, please be advised that your dissemination, distribution or copying of this e-mail is improper. If you have received this e-mail in error, please contact us immediately at the above-mentioned telephone number. This e-mail and the attachment(s) thereto have to be deleted immediately.

**Comment by chaoslife** [comment]
Will it support unity?

**Comment by Czudol** [comment]
In your roadmap did you account for an 3D Tiles engine for Unity?

**Comment by shehzan10** [comment]
@chaoslife @Czudol The Cesium ion REST API can be integrated into any runtime engine.

For questions not related to Cesium ion REST API (ie. this repo), that cover a broader product ecosystem, please search on the [Cesium Community Forum](https://community.cesium.com), or if a question doesn't exist, please ask a new one.

**Comment by Czudol** [comment]
Sorry the question is more specific, will you release a intergration plugin for Unity to connect to Cesium ion

**Comment by shehzan10** [comment]
@Czudol To have better community engagement and searchability, we keep questions and answers in the relevant repos/forums. The Cesium Community Forum is the right place for your question. A quick ["Unity" search](https://community.cesium.com/search?q=Unity) will likely get you the answers you are looking for. If you have any other questions, feel free to follow up on an existing topic or post a new one on the forum.
