### ISSUE TITLE
Support Overlaying 360 Panoramic Imagery (Indoor/OutDoor)

### ISSUE THREAD

**Issue by donrv** [AnalyticalGraphicsInc/cesium-ion-community#155]
Would love to see Cesium Ion Support Overlaying 360 Panoramic Imagery (Indoor/OutDoor).
You can get a cue from [NavVis Indoor Viewer](https://www.navvis.com/indoorviewer) and [Orbit 3D Mapping Cloud](https://3dmapping.cloud/)

**Comment by OmarShehata** [comment]
Thanks for opening this feature request @donrv ! I'd love to hear more about your use case. Are there any particular formats you'd like to see supported here? Are you hoping to include or embed these panoramic scenes inside your 3D Tiles?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

There's already some discussion about ways to do this on the forum here: https://community.cesium.com/t/image-files-as-panorama-view-in-cesium/7763
