### ISSUE TITLE
"Add Data" in "My Assets" should allow adding WMS URLs

### ISSUE THREAD

**Issue by donrv** [AnalyticalGraphicsInc/cesium-ion-community#156]
"Add Data" in "My Assets" should allow adding WMS URLs

**Comment by OmarShehata** [comment]
What kind of sources would this be loading from? I think this would be the same feature as described here https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/65 ?

**Comment by donrv** [comment]
#65 issue is actually to track usage of map services and bill accordingly. I meant to create cesium ion Tokens for WMS URLs I want to load using cesiumjs

**Comment by OmarShehata** [comment]
Do you mean you have WMS imagery you want to load from a certain server, but that requires a token, so you want to store this third party token in Cesium ion so you have all your data sources in one place? 

Are you able to share an example of what these WMS urls are?

**Comment by OmarShehata** [comment]
@donrv I'm closing this since it sounds like issue linked above can be for keeping track of external assets in Cesium ion as you describe. Feel free to follow up if that's not the case!
