### ISSUE TITLE
Tiling issue with asset id: 21770

### ISSUE THREAD

**Issue by n8mlr** [AnalyticalGraphicsInc/cesium-ion-community#157]
Hello, I'm attempting to load a rather large city dataset (https://www.cgtrader.com/3d-models/exterior/cityscape/seattle-city-and-suburbs) into Ion, but encountered the error message 'We're having trouble with your data' after the data completed uploading and stuck at the 5% progress bar for a while. 

Anything I can do on my side? Thanks! Awesome product

**Comment by OmarShehata** [comment]
Thanks for the kind words @nate63179 ! Just wanted to let you know I'm looking into this issue. 

In the mean time, I see this model is also available as an OBJ. I think that would be significantly faster to tile since it would be a faster conversion step to glTF. I would try tiling that instead of the DAE. Make sure to select model type "BIM/CAD/Other" when tiling it.

**Comment by OmarShehata** [comment]
Just a quick update: I tried converting the DAE model to a glTF using [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF), which worked but produced the following warnings for missing images:

```
Converting seattle_dae.DAE -> output\seattle_dae.gltf
WARNING: Image uri: file:\C:\Libs\Maps\Grass_GP_DM_03.jpg could not be resolved
WARNING: Image uri: file:\C:\Libs\Maps\Grass_GP_DM_04.jpg could not be resolved
Time: 261345 ms
```

Putting some placeholder textures there before tiling still produces an error. I suspect there might be a deeper issue on our end. I'll update this issue once we've had a chance to investigate further and deploy a fix.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
