### ISSUE TITLE
Converting KML with models leads to black background of textures (Asset ID: 21823)

### ISSUE THREAD

**Issue by Tugark** [AnalyticalGraphicsInc/cesium-ion-community#158]
Hi all

I'm trying to create a 3D-tileset for some of our 2D datasets. I do so by using any COLLADA model (just for testing, as of now) and adding it to our 2D point datasets, then save it as KML.

In Google Earth, this looks fine:
![image](https://user-images.githubusercontent.com/16555423/56881945-55c7af80-6a62-11e9-9aa1-2312802dfeea.png)

While in Cesium, once uploaded and tiled (Asset ID: 21823), it looks like this:
![image](https://user-images.githubusercontent.com/16555423/56881994-7abc2280-6a62-11e9-8081-7e78547f920d.png)
It's as if all the PNG-textures of the model get a black background, and the model itself is also incorrectly created.

If I only upload the COLLADA model to Cesium ION, it works fine:
![image](https://user-images.githubusercontent.com/16555423/56882997-a7256e00-6a65-11e9-8870-15ccba67bd95.png)

Do you have any idea why this happens? I only found that with JPG textures, it works nice. It's the PNG ones that have this sort of "blackness" behaviour.

**Comment by OmarShehata** [comment]
Thanks for opening this bug report @Tugark ! It looks like this is because the converted glTF does not have the correct `alphaMode` set. When tiling it on ion as photogrammetry/CAD etc. it does an extra check to set that up, so that's why that option works.

We have a fix in the works, I'll update this when it's deployed.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
