### ISSUE TITLE
Add support for NAVD88 height reference

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#16]
One meter DEMs derived from LiDAR in the US are referenced vertically to NAVD88.  Downloadable from [here](https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Elevation/1m/IMG/
).

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this request internally now. For any follow-up questions, please use the community forum!
