### ISSUE TITLE
3d tiles ion resources

### ISSUE THREAD

**Issue by AJJackGIS** [AnalyticalGraphicsInc/cesium-ion-community#161]
question: how can i get more ion resources, the default access token has only few resources, i'm learning examples from Sandcastle APP, but the majority i can't get the whole page.

add: we are working on 3dtiles application, recently i was learning 3d tiles demos in the Sandcastle Gallery , for example , 3D Tiles feature picking, 3D Tiles photogrammetry classification and so on, how can i get this kind of resources. thanks!!

coming from https://github.com/AnalyticalGraphicsInc/cesium/issues/7794

**Comment by OmarShehata** [comment]
So we are curating some 3D Tilesets to add to the ion asset depot, so you'll be able to search for them, add them to your account, then use them in your own applications. For example, one of them is going to be the New York building dataset used in the [Cesium workshop](https://cesium.com/docs/tutorials/cesium-workshop/). 

I'll update this issue once they're available!

**Comment by AJJackGIS** [comment]
oh, that would be great ! i'm looking forward.
