### ISSUE TITLE
i have a 3dtiles format zip file (with a tileset.json and larges of .b3dm)，how can i upload it to the ion?

### ISSUE THREAD

**Issue by AJJackGIS** [AnalyticalGraphicsInc/cesium-ion-community#162]

**Comment by OmarShehata** [comment]
Cesium ion currently doesn't support uploading pretiled data, but if you upload the source files (so the original OBJ and materials for example) the ion 3D Tiling pipeline will create an optimized 3D Tileset for you.

With that said, supporting upload of already tiled data is something on our roadmap. Can you tell me a bit about your use case? How did you tile this data?

**Comment by AJJackGIS** [comment]
we have some osgb format building model file from cc software,as i know,cc can export b3dm format already. but some times, we can get osgb file only, so there is a question, cesium can't work with osgb, so i'm curious about the osgb converter and supporting upload.
