### ISSUE TITLE
CityGML with CP1252 encoding fails to tile with no error

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#163]
Hi, I uploaded this asset through the API. It's a CityGML.

What's the issue with the file?

**Comment by OmarShehata** [comment]
Looks like the error with that file is:

```
Error: Invalid File
Details: unable to create converter for 'CP1252' encoding, Line 1, Column 40
```

I would use ASCII or UTF-8 for the XML file encoding. I'll keep this issue open for either better error handling of this error or supporting this encoding type.

**Comment by pablocbre** [comment]
Hi @OmarShehata, I'm kind of surprised because I just tried to upload a GML generated from the same source, simply smaller, and it worked fine (see asset 23121).

**Comment by OmarShehata** [comment]
Yeah looks like the only difference between those two files is that the one that fails starts with:

```
<?xml version='1.0' encoding='cp1252'?>
```

Whereas the second, smaller one, doesn't declare any encoding at all. I would try either removing that line (which is the first line in the gml that fails to tile) and retiling.

**Comment by pablocbre** [comment]
Gosh, I'm going mad with encodings. Ok, I'll remove that line and try again, thanks a lot Omar.

**Comment by pablocbre** [comment]
Hi @OmarShehata, I uploaded the file without the encoding line but an error occurred again. Asset ID is 23191. Could you let me know what the issue is now?

**Comment by OmarShehata** [comment]
@pablocbre this might be a separate issue now. It's not a known error on the server. I'm going to investigate and open a separate issue if it turns out to be an unrelated problem.

I have been able to successfully tile CityGML buildings around ~80 GB in the past on ion. The difference there was there were many gml files instead of one big one.

**Comment by pablocbre** [comment]
OK, looking forward to knowing what you find out.

**Comment by pablocbre** [comment]
Hi @OmarShehata , just wondering if finally this is a new issue or is related with the same problem.

**Comment by OmarShehata** [comment]
@pablocbre sorry for the delay here. The good news is that I was able to tile this using the [on-premise tilers](https://cesium.com/docs/on-premise/). I believe the issue is the ion job runs out of memory trying to read the single file. 

I have opened a bug report internally to better deal with larger CityGML files like this. In the mean time, do you have a way of splitting this on export? Even just splitting into 2 would ensure each piece is less than 16 GB and it should fit into the available memory in ion jobs.

**Comment by pablocbre** [comment]
Hi @OmarShehata, no worries. 

Ok, I'll try to split it in smaller parts.

I'm wondering what's the sweetspot here, since apparently neither a single big file can be uploaded nor a large quantity of individual files (see issue #143 ).

**Comment by pablocbre** [comment]
Hi @OmarShehata. 

I tried to upload a new CityGML (9Gb uncompressed) inside a ZIP file. Everything was running smoothly and it started tiling successfully, but it got stuck at 39% and then an error popped up. Asset ID is 28512. 

What is the issue with this one?

BTW, if you feel like this should be split into several issues I have no problem with that. I feel we are uncovering many different things as we advance.

**Comment by OmarShehata** [comment]
@pablocbre looks like the issue here is indeed the same as https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/143 - too many files. 

I would say an ideal file size is less than/around 1 GB, which should significantly cut down the number of files here and tile efficiently on ion.

**Comment by pablocbre** [comment]
Hi @OmarShehata, still not getting there... I've uploadad a single, 9Gb GML inside a ZIP and it ended up in an error. Asset ID is 28777.

**Comment by OmarShehata** [comment]
@pablocbre can you try perhaps 10 files that are 1 GB each? Or 20 that are 500 mb each? This is generally the range the [NYC CityGML](https://www1.nyc.gov/site/doitt/initiatives/3d-building.page) model is formatted in, which I know performs well.

**Comment by pablocbre** [comment]
Hi @OmarShehata, I'll try to upload 5 GMLs with a size of 3.5Gb each that I have at hand first, since splitting  and merging GMLs is quite time consuming for me. 

I guess this is pretty obvious, but it would be nice to have explicit docs on these thresholds that make the process fail so we could know about them.

As always, thanks a lot for your help

**Comment by pablocbre** [comment]
Just confirming that the previous attempt failed (Asset ID 28919).

**Comment by OmarShehata** [comment]
@pablocbre I definitely agree. We know these failures are bugs we're working on solving, but in the mean time I'll see if I can add a note about best practices and known issues in the docs pages. 

I appreciate your patience and all the incredibly helpful debug information!

> Just confirming that the previous attempt failed (Asset ID 28919).

This is the one with 5 GMLs?

**Comment by pablocbre** [comment]
Yes, @OmarShehata. It's that one.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
