### ISSUE TITLE
Tiling issue with asset id: 23224

### ISSUE THREAD

**Issue by gibranparvez** [AnalyticalGraphicsInc/cesium-ion-community#164]
This is an 8-bit unsigned single-band raster that seems to fail on upload. Thoughts?

**Comment by OmarShehata** [comment]
I think the issue is the data type. The [ion uploading data](https://cesium.com/docs/tutorials/uploading/) page says:

> Raster terrain must be a single band of floating point or integer elevations.

If you run `gdalinfo` on that file, you'll get a type `Byte`:

```
Band 1 Block=8473x1 Type=Byte, ColorInterp=Gray
```

It looks like this is mostly building data. Was it generated from something else and saved as an image?

**Comment by gibranparvez** [comment]
Interesting. So QGIS calls 8-bit integers bytes by default, and my other geotiffs have this format, so I'm not sure why this makes it any different. There's not really a setting to say "Int8", its just "Byte" in the dropdowns. Let me use gdal translate to try to explicity set it again and see if it changes.

It's stereophotogrammetric data that we didn't edit elsewhere.

**Comment by gibranparvez** [comment]
Re-saved and the data type was set properly. Thanks. Weird stuff.
