### ISSUE TITLE
Tiling issue with asset id: 23265

### ISSUE THREAD

**Issue by stevenjh** [AnalyticalGraphicsInc/cesium-ion-community#165]
Revit bridge model, exported as IFC, converted from IFC to GLTF in FME for upload to ion.

**Comment by OmarShehata** [comment]
Looks like the issue is that the glTF is referencing a .bin file, but that file wasn't uploaded alongside the glTF. Can you try upload the glTF together with this file and let me know if it works?

**Comment by stevenjh** [comment]
Having all the  files in there definitely helped thanks, I hadn't realised it was a multi part file!
