### ISSUE TITLE
Cesium visualization issue with asset id: 1

### ISSUE THREAD

**Issue by wowill5** [AnalyticalGraphicsInc/cesium-ion-community#166]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
Can you describe what the problem you're seeing is? Are you getting an error? Can you attach a screenshot or a link to a code example on Sandcastle (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/) ?

**Comment by OmarShehata** [comment]
@wowill5 I'm closing this now, but feel free to follow-up with more information if you're still having trouble!
