### ISSUE TITLE
Terrain asset not properly integrated into cesium terrain

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium-ion-community#17]
From @tkazik in https://github.com/AnalyticalGraphicsInc/cesium/issues/6651

---

Hi folks

I am encountering some issues in cesium ion's composer: I created a locally flat terrain in QGIS and exported it as geotiff, which can be loaded into cesium's composer (basically following this [tutorial](https://cesium.com/docs/tutorials/getting-started/)). When zooming closer to the asset, it vanishes...some sort of clipping issue, see:

![cesium_terrain_asset_short](https://user-images.githubusercontent.com/15689124/40878472-11ebc122-6692-11e8-91b3-d15653801150.gif)

Thx for any hints and tipps!

PS: geotiff is here:
[outputRiad_700m_skew.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2065165/outputRiad_700m_skew.zip)

**Comment by mramato** [comment]
@tkazik thanks again for submitting this issue.  Did you use all default settings when processing the terrain?  I processed it locally using the file you provided and it appears to look correct for me:

![terrain](https://user-images.githubusercontent.com/1495196/40925433-b1941a8e-67e7-11e8-9007-71c430f52906.gif)

**Comment by tkazik** [comment]
Thx for you quick replies!

@hpinkos Thx for moving this over to the ion repo.
@mramato Sorry, I should have been a bit clearer:

I get the same (correct) results as yours if I use these settings at import (base: WGS84):
![base-wgs84__ref-wgs84](https://user-images.githubusercontent.com/15689124/40927889-2ce8479a-6820-11e8-98a4-4e62dd62d293.png)

However, my screen capture is based on these settings (base: cesiumWorldTerrain):
![base-cesiumworldterrain__ref-wgs84](https://user-images.githubusercontent.com/15689124/40927906-394171b0-6820-11e8-9d37-f351c5d1ea5c.png)
 
So the issue seems to be related to the cesium world terrain. Background info: My goal is to have cesium world terrain as a basis and add multiple assets on top of it.

**Comment by tkazik** [comment]
@mramato Are you able to reproduce the issue if you use cesium terrain as basis?
Or am I missing something? Thx a lot!

**Comment by hpinkos** [comment]
Hi @tkazik, I was able to reproduce the error you're seeing after setting WGS84 as the height reference.  We'll let you know when we have a chance to debug the problem with the tiler.  Thanks for reporting this!

**Comment by tkazik** [comment]
Just to make sure to be crystal clear:

This issue occurs with both reference height settings (WGS84 and EGM96).
The Base Terrain is what matters: The WGS84 Ellipsoid is ok, but using the Cesium World Terrain as base terrain causes issues.

Thx a lot!

**Comment by tkazik** [comment]
Any new on this one? This is quite an important aspect/buying point for ION for us.
Also, it would be nice to have the option to upload multiple terrain files for different locations on top of the cesium world terrain, while the cesium world terrain gets finer and more accurate in the future.
Appreciate your work and looking forward to your progress!

**Comment by hpinkos** [comment]
Hi @tkazik, sorry for not getting you an update sooner.  I don't think our tiling team has had a chance to look into this bug yet, but it's something that is high on our priority list.

As for your second point, our goal is for the terrain converter to work exactly as you described.  If you upload terrain files for multiple locations and select Cesium World Terrain as the base layer, it should work with way already.

I'll let @mramato or @tfili give you further details on this.  Thanks for following up!

**Comment by tfili** [comment]
Hi @tkazik
I figured out what is going on here. In most cases when a user puts new terrain on an existing tileset, it will be higher resolution. In this case your terrain actually lower resolution than what we have.

Whats happening is that your terrain goes down to level 11, but once we zoom in enough for level 12 (which I double checked does exist) we load the higher res tiles from Cesium World Terrain.

This isn't really a case that we took into account, as we expected people to use localized higher res terrain. In your production use case, will you have higher res terrain than what CWT has or will you have terrain that is lower res, but potentially has other features built in such as buildings?

**Comment by tkazik** [comment]
Thank your for the update and debugging!
For the time being we are mainly interested in creating locally flat terrain where CWT is bumpy. Although it is a bit waste of space, I am fine with creating high resolution flat terrain.
Follow-up question: How can I determine the level available of the CWT?
Thx again!

**Comment by tfili** [comment]
@tkazik We recently updated our World Terrain, so check out the new version to see if you still need it. I threw together a sandcastle example that will let you click a spot on the Globe and it will tell you the max level. It prints it to the console.

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dVPJjtswDP0VNZdxgEBGr82CTo20EzTpBE3QXgwUiswkwmgxJNnTTJF/H3p3lupgm9Tj4yNN5swSD9YyocmUROBEpii3wDz8NlYm2+ouGI5jHesc0bmAV7AI1vDaBPwqfcEDL83IaI8xYB9G5F+sCZ46xdqaXCRgPzWOWJ8r5tqmmDk5IUwJB9QfQQf7THMvDEpoyAoVLGdCsp2Qwp9QSxPed487tOOgAWGVdlqa9XX1DEOyMpkDYnKsDfOSgzQ7IN4QB1A6OLPeHCxLj4KT1DhRiOpSHJlO5HVfNthJ0JuUcZjnoP1TBQpKAZQzbKgb1kJqAurAL3Sa+ceq6rZ8hdIUcrRtKI7Yk5pMmQTIh+m0S43eFTrp6vnn+mnx49tFYCO7qAoDmO66w5kCy2gq+MtcSpE6I5I2O20qH1VNpWWfKDTA6m/2sxQSa00J7HEskqBNOrzR1NfVdrstKup56R6nJGqYepw3ChpOCTlIJOsPCeVGYbNhxf4KlallAXn067rIoC+j+VH9w412RgKV5hCU9Negc2fWn+fR/6Zje0qBLudft3+i5SL6PhyTdj1iPRgNJs6fJMwqms9CpcZ6klkZUBp6UKnEpXXhLuMv4Cl35WRNwiZokoiciGQaD662NB4QLplzeLPPpNyIN4gHs0mI+IswaVgi9OEZN0SyUwE5fpwtKyeldBKieRvljZE7hkkuvdW+rkBnd3O9GaO+ZN5je+/eO4blwh1E/X4H

**Comment by tkazik** [comment]
Perfect, thank you very much @tfili!
Hopefully my last issue is the following: The height of my geotiff does not match the terrain data of CWT. 
Using QGIS, I rasterized the following area as tiff at an altitude of 650m:
![qgis](https://user-images.githubusercontent.com/15689124/45345214-ede15900-b5a5-11e8-89d4-dd95716d1062.png)

I would expect, the terrain to be slightly above the rest in CWT, which is at about 625m at that area. However, the appearance is the following:
![cwt_appearance](https://user-images.githubusercontent.com/15689124/45345343-60eacf80-b5a6-11e8-88bf-0e3ac859f202.png)

I tried both references (wgs84 and EGM96), but had no luck. Any hints or advice from your side?
Thank you very much!

PS: geotiff is here
[riyadh_export_at_400x400_3.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2369933/riyadh_export_at_400x400_3.zip)

**Comment by tfili** [comment]
@tkazik I'm looking at the tiff you provided in gdalinfo and the min and max values are both 0. It looks like you set the `NoData` value to 650.

![image](https://user-images.githubusercontent.com/1652382/45437954-dd9fab80-b683-11e8-9fc3-d1647c3dc5e8.png)

I ran your tif throught the Raster Calculator in QGIS with the following
![image](https://user-images.githubusercontent.com/1652382/45438290-c1503e80-b684-11e8-96e0-44aba0ea95b1.png)

Now the gdalinfo looks better
![image](https://user-images.githubusercontent.com/1652382/45438336-de850d00-b684-11e8-8378-4619a59cfced.png)

and Cesium looks correct as well

![image](https://user-images.githubusercontent.com/1652382/45438351-ea70cf00-b684-11e8-970c-a348b71e8a62.png)

Hope that helps

**Comment by tkazik** [comment]
Wow, that is perfect, @tfili! Excellent support, I really appreciate your help!
@hpinkos, issue can be closed, thank you.

**Comment by hpinkos** [comment]
Thanks @tkazik!  Glad we were able to help.
