### ISSUE TITLE
Cesium World Terrain - artifacts along coastllines

### ISSUE THREAD

**Issue by stevenjh** [AnalyticalGraphicsInc/cesium-ion-community#170]
I've found a number of strange spikes occurring around the coastlines of New Zealand.

This picture is taken in Auckland City harbour, at the north end of the harbour bridge. The spikes are about 30m in height and there are instances of this throughout the contry.

![image](https://user-images.githubusercontent.com/1258872/57737111-94b26200-76fe-11e9-8d45-6e02fe59f4db.png)

Thanks!

**Comment by stevenjh** [comment]
This doesn't look to be isolated to NZ, just came across the same thing in Australia

 38.10670°S, 144.36468°E

**Comment by OmarShehata** [comment]
Thanks for reporting this @stevenjh. As part of curating Cesium World Terrain we combine multiple different data sources and run various quality checks to remove erroneous data. I think this might be a class of error that we're not checking for right now. It looks like they're waves that were interpreted as heights.

You can use the Cesium Viewer app to link directly to a specific view (the URL updates as you move the camera). Here I think is one if the views (or close) to your first screenshot:

https://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html?view=174.7720745609311%2C-36.828571058275976%2C156.82738474996015%2C107.0241404749281%2C-21.227395475673664%2C359.81070088585466

If you can add links to some of the ones you found in NZ as well that would be helpful. Are they all around the coast like this?

**Comment by stevenjh** [comment]
I've had a look around some various parts of the world coast line and haven't found many instances of this. But it seems somewhat regular throughout NZ. It's like they're gaps between where the land dtm ends and the water begins and default/base values are spiking through?

This angle captures the issues right across Auckland harbour if you look closely.
Inland water bodies and giant 'waves' across the whole inner harbour..
https://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html?view=174.79839241830652%2C-36.85237453545534%2C133.58263362786786%2C308.26562353748636%2C-0.43759971841855966%2C0.14487732787393032

Top of the South Island of NZ
https://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html?view=173.02135244769718%2C-41.02940117885602%2C218.3649912577255%2C342.20111144710074%2C-15.363745484839326%2C0.06033421325409874

Bottom of the South Island of NZ
https://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html?view=168.97389970701727%2C-46.664340395617046%2C288.05896383511543%2C103.67748604395113%2C-16.146933672904176%2C359.80560098036153

Melbourne, Australia
https://cesiumjs.org/Cesium/Apps/CesiumViewer/index.html?view=144.3577873792604%2C-38.11448922723302%2C441.0439070614334%2C51.11595424118366%2C-19.406910744409316%2C359.84599018637573

Cheers!

**Comment by OmarShehata** [comment]
Updating this to be general artifacts along coastlines. I believe the issue is due to the source data in these areas recording waves as elevation heights. There's a few more areas of this [reported in this forum thread](https://groups.google.com/d/msg/cesium-dev/_NjkUrNhvmA/9xvo3089AQAJ). The easiest way to find these is to go to a [CesiumJS viewer](https://cesium.com/cesiumjs/cesium-viewer/index.html?) and type in the lat/lon separated by space or comma:

129.144821, 35.154470

![image](https://user-images.githubusercontent.com/1711126/70741982-90791200-1cea-11ea-81e1-ca1c565daecd.png)

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, or if you find any more artifacts, please continue to report them on community forum!
