### ISSUE TITLE
issue uploading las files "unable to load all asset files" error

### ISSUE THREAD

**Issue by pedalpete** [AnalyticalGraphicsInc/cesium-ion-community#172]
We've been attempting to upload a point cloud data set from [City of Melbourne](https://data.melbourne.vic.gov.au/Property-Planning/City-of-Melbourne-3D-Point-Cloud-2018/2dqj-9ydd) 

The original upload failed, so we made a 2gb sub-sample of the data which also failed as seen below
![image](https://user-images.githubusercontent.com/319482/58224461-3e2dcf00-7d61-11e9-9af6-ef10b1cf096b.png)

Is there a recommended size of data we should be uploading? Any other info I can give you? 

Uploaded using Chrome 74.0.3729.169

**Comment by OmarShehata** [comment]
Thanks for reporting this @pedalpete. I've been looking into a similar issue lately. Can you tell me if there are errors in your browser console when this happens? And also:

* How many files are you uploading?
* What's your network upload speed? How long does it take before it fails?
* What's your location (city/state/country) ?
* Are you behind any sort of corporate firewall?

**Comment by pedalpete** [comment]
- I'm uploading a zip file which contains a sub-folder with 121 files. I've just tried again without the subfolder and get the same result
- 0.73mbs, fails in about 5 minutes. 
- I'm in Sydney Australia, this also failed in Bendigo Australia
- No firewalls

There is an issue (likely unrelated) where the % counter during uploading never gets higher than `0.60%`

**Comment by OmarShehata** [comment]
Thanks for the info @pedalpete . One more thing: Can you see if the browser reports any errors in the console or network tab when the upload fails?

**Comment by pedalpete** [comment]
Apologies, I checked before, but forgot to write. Nothing in the console, network tab didn't have anything interesting either. No response on the request and nothing interesting that I could pick could out in the header

**Comment by pedalpete** [comment]
I'm going to close this issue @OmarShehata I tried again today and the upload worked. Not sure if it is something you fixed on your end, or something else. I am definitely on a faster network today, but Bendigo's network speed (where it also failed last week) would have been similar to what I'm running today. 

Thanks for your help.

**Comment by OmarShehata** [comment]
Thanks for confirming this @pedalpete. We just pushed out a fix today that should help with this as well, so hopefully anyone else who was seeing issues here should be able to upload now.
