### ISSUE TITLE
Tiling issue with asset id: 29190

### ISSUE THREAD

**Issue by tietoajukka** [AnalyticalGraphicsInc/cesium-ion-community#176]
OBJ model from RealityCapture.

What could be the problem with this data?

**Comment by OmarShehata** [comment]
Looks like there's a data error here. One of the files (`Immola_GK29_shifted_0000103.obj`) is a model with no geometry. Can you try removing that file and re-uploading?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're still having issues here, please post on the community forum!
