### ISSUE TITLE
Search for assets by ID

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/cesium-ion-community#177]
It would be nice to able to search for assets by ID in the `My Assets` view. As an example use case, someone could be collaboratively building an application and they could want to see the asset on ion for debugging or for relocation. The application code probably won't contain the asset name but it's likely to contain the asset ID.

**Comment by OmarShehata** [comment]
It would be nice to have the search bar pop this up for convenience. For now you could you just go to https://cesium.com/ion/assets/{id}

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
