### ISSUE TITLE
uploading obj files "unable to load all asset files" 

### ISSUE THREAD

**Issue by 3DGISKing** [AnalyticalGraphicsInc/cesium-ion-community#178]
I have a 16 GB obj file.
I am going to upload it to ion.
But failed. I tried several times, still the same.
Why? What shall I do?

**Comment by 3DGISKing** [comment]
﻿
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
4
s3.amazonaws.com/ass…339nJwGQVm5gR0A--:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
﻿
​

**Comment by OmarShehata** [comment]
Thanks for reporting this @3DGISKing. I appreciate you providing the console errors you're getting. To help us debug this, can you tell me:

* How many files are you uploading?
* What's your network upload speed? How long does it take before it fails?
* What's your location (city/state/country) ?
* Are you behind any sort of corporate firewall?

**Comment by 3DGISKing** [comment]
1. A: only one file. 16 GB size
2. About 1 MB/s. 30~40 min
3. China/Jilin/Yanji. But we are using VPN(Los Angeles) 
4. No

I am very sorry to telling this story. I am using paid account.
Let me know your idea.
Thanks

Sent from Mail for Windows 10

**Comment by OmarShehata** [comment]
We just pushed out a fix today that should help with this @3DGISKing. Can you try uploading now and let me know if it works?

**Comment by OmarShehata** [comment]
I'm closing this now, but please feel free to follow up or open a new issue if you're still having trouble! You can also see all the new changes we've been doing in the new changelog here: https://cesium.com/ion/changelog
