### ISSUE TITLE
Support tiling of point clouds with CSV input

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#179]
This is potentially related to supporting point clouds as plain text PTX files (see https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/34), but it might be nice to allow for uploading a CSV file X/Y/Z or Lat/Lon/Altitude, and whatever per-point metadata, and have ion support tiling that. 

Is this something you'd use or find helpful? (If so please chime in here or 👍 this issue!) Is there a standard set of column names we should support, or should we have the user choose when uploading? I think the easiest may be to specify what the coordinate column names should be, and anything else gets interpreted as per-point data.

As an incidental feature, this could help support a lot of formats that we don't already tile yet. For example, [in this forum discussion](https://groups.google.com/d/msg/cesium-dev/Q52IojlZ8AM/UH2OuUOtBAAJ) the question of how to tile [GRIB](https://en.wikipedia.org/wiki/GRIB) data came up (GRIB is a "is a concise data format commonly used in meteorology to store historical and forecast weather data"). It sounds like it can be easily converted into a CSV like this and then tiled with ion.

CC @lilleyse

**Comment by OmarShehata** [comment]
Just got another request over email for adding support for this in the context of including temperature/color data for each point. It would be really cool to be able to just have arbitrary per point data like this I think.

**Comment by andrewforman** [comment]
+1 
I have the same use case (GRIB and all) and was hoping to find for a clean way to inject lat/lon/alt/additional data into a diffuse point cloud.

**Comment by OmarShehata** [comment]
This may be another use case to support a generic CSV file with points (or whatever format is native to this type of data):

https://github.com/AnalyticalGraphicsInc/cesium/issues/8166

> I got a InSAR data，and It has about ten million points tissue through CSV，covers a wide range of areas. I want to conversion it to 3D Tiles.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/support-tiling-of-point-clouds-with-csv-input/10499
