### ISSUE TITLE
How to create a terrian ?

### ISSUE THREAD

**Issue by X-DX** [AnalyticalGraphicsInc/cesium-ion-community#18]
Respected Sir,
My problem is that I don't want to use the existing terrains, like cesium world terrain but instead wanted to create my own terrain. I have been working on this topic since last week but am not able to create my own terrain. Is it possible to create my own terrain using cesium ion, or I will end up using only the 'cesium world terrain'.
Actually I have collected .dem files, for some specific regions, and I want to build terrain for those regions.
Can you please help me out in this matter? 
or can you give me some  examples of how to create a terrian from an .tiff file ?

**Comment by mramato** [comment]
Hi @X-DX, thanks for your interest in ion.  We have a Getting Started tutorial which includes creating terrain from .tiff files here: https://cesium.com/docs/tutorials/getting-started/

By default, uploaded tiffs will not use Cesium World Terrain, so any data you upload will be just your data.

If you have multiple regions you would like to turn into a single terrain dataset, you just need to upload multiple files at the same time.

I hope that helps get you started.  If there is anything unclear the in the tutorial or if you have any additional questions, feel free to reply to this issue.

Thanks!
