### ISSUE TITLE
Tiling issue with asset id: 30099

### ISSUE THREAD

**Issue by dodecaphonic** [AnalyticalGraphicsInc/cesium-ion-community#180]
My image consists of satellite imagery of a snowed area, in EPSG:32719. It is as folows:

```
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  377396.262, 6313758.370) ( 70d19' 1.22"W, 33d18'29.94"S)
Lower Left  (  377396.262, 6307875.170) ( 70d19' 4.09"W, 33d21'40.92"S)
Upper Right (  385327.862, 6313758.370) ( 70d13'54.56"W, 33d18'33.08"S)
Lower Right (  385327.862, 6307875.170) ( 70d13'57.25"W, 33d21'44.08"S)
Center      (  381362.062, 6310816.770) ( 70d16'29.28"W, 33d20' 7.03"S)
Band 1 Block=19829x32 Type=Byte, ColorInterp=Red
Band 2 Block=19829x32 Type=Byte, ColorInterp=Green
Band 3 Block=19829x32 Type=Byte, ColorInterp=Blue
```

I can work with it fine using GDAL or QGIS, but can't get it processed here. I've also tried a smaller version with EPSG:4326 -- same deal.

**Comment by dodecaphonic** [comment]
FYI: I've cut a small window into the image with gdal_translate, keeping it in the same reference system, and it was processed just fine.

**Comment by OmarShehata** [comment]
Thanks for reporting this @dodecaphonic. I believe this is the same issue as https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/168. We're looking into this now. I'll hopefully have more information on when a fix is going to be available by next week.

**Comment by dodecaphonic** [comment]
Thank you very much. I'll watch that issue.

**Comment by OmarShehata** [comment]
@dodecaphonic I've just restarted the job, and it looks to have completed! Can you confirm that you can see it in your account and it looks correct?

**Comment by dodecaphonic** [comment]
It did! Thank you very much.
