### ISSUE TITLE
Failed to tile model with uppercase extension

### ISSUE THREAD

**Issue by klucg** [AnalyticalGraphicsInc/cesium-ion-community#182]
Asset ID: 30390

**Comment by OmarShehata** [comment]
I think this may be due to the model being named `<name>.DAE` instead of `<name>.dae`. Can you confirm that it works for you by renaming and re-uploading?

**Comment by OmarShehata** [comment]
We've just released a fix for this, you can see it in the changelog here: https://cesium.com/ion/changelog#2019-07-09. I've just re-tested it and can confirm it works! 

Let me know if you're still having any issues with this.
