### ISSUE TITLE
Terrain with custom base layer fails to tile

### ISSUE THREAD

**Issue by jheijari** [AnalyticalGraphicsInc/cesium-ion-community#183]
Asset ID: 30822

I can't get my terrain tileset tiled. I'm trying to use my previous lower LOD terrain tileset as a base terrain, but it's stuck at tiling 5%. When I use Cesium World Terrain as a base terrain, everything works fine.

**Comment by OmarShehata** [comment]
I'm looking into this now - just to confirm, does this tile successfully without any base terrain?

**Comment by OmarShehata** [comment]
Just an update here, we've just made a big fix to the terrain tiler erroneously outputting too many tiles, which may have been the cause here. This should be deployed by early next I think, I'll update this issue once that's up.

**Comment by OmarShehata** [comment]
Just an update: I tried to retile this yesterday, but it looks like this is still an issue.

**Comment by jheijari** [comment]
> I'm looking into this now - just to confirm, does this tile successfully without any base terrain?

Yes, asset id 32169 has the same source data without any base terrain.

**Comment by OmarShehata** [comment]
We've just deployed a fix for this, and I've restarted the job and it now completes. If you're still having issues feel free to follow up here or open a new issue!
