### ISSUE TITLE
All requests blocked in Firefox 68b

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#184]
This was reported by [Noelle Leigh on Twitter](https://twitter.com/noelle__leigh/status/1139607069869445122). It seems like all requests to ion are getting blocked with CORS errors. I can recreate this using the latest [Firefox 68b](https://www.mozilla.org/en-US/firefox/beta/all/).

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.cesium.com/1/layer.json. (Reason: missing token ‘accept’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.cesium.com/1/layer.json. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.cesium.com/5741/tileset.json?v=1. (Reason: missing token ‘accept’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.cesium.com/5741/tileset.json?v=1. (Reason: CORS request did not succeed).
```

You can see this on any Sandcastle: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Picking.html

@mramato Is this just a simple matter of changing the request CesiumJS is making? Or a change in the response from ion?

**Comment by mramato** [comment]
At first glance this looks like a Firefox bug/regression, not an ion or CesiumJS bug.  You should open an issue in Bugzilla and report back here

**Comment by OmarShehata** [comment]
I opened a bug report here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1559795

Feel free to vote on it/correct anything I said there.

**Comment by mramato** [comment]
Bug report looks good to me.

**Comment by OmarShehata** [comment]
Just an update here, this was indeed identified as a bug, and should be fixed in Firefox 69. The debate now seems to be around whether it's too late to fix to Firefox 68, or if it can be some 68.1 version. 

I think we should leave this open until it's fixed in the latest released Firefox, that way if there's a version out without the fix users can find this.

**Comment by mramato** [comment]
I chimed in on the FF issue.  This seems like a major regression on their end and nothing in the spec seems to back the arbitrary limit they imposed.

**Comment by mramato** [comment]
We've worked around the problem on our end, still disappointed they shipped with the regression in place.
