### ISSUE TITLE
Tiling issue with asset id: 31957

### ISSUE THREAD

**Issue by imenjomaa** [AnalyticalGraphicsInc/cesium-ion-community#187]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
Thanks for reporting this @imenjomaa . This seems to tile fine using the latest, development version of the 3D Tiling pipeline, so it looks like it was a recent fix that hasn't been deployed yet. 

I'll update this issue once the fix is live.

**Comment by imenjomaa** [comment]
I use CityEngine to export a KML file of fews of building models. When i
upload the file in to Cesium On, it warning this problem:We're having
trouble with your data. To help fix it, please open an issue in our Github
repository.




Le lun. 24 juin 2019 à 22:19, Omar Shehata <notifications@github.com> a
écrit :

**Comment by OmarShehata** [comment]
Thanks for the additional information @imenjomaa . We should have a fix for this up this week. I'll get back to you once it's deployed.

**Comment by imenjomaa** [comment]
Ok thanks

**Comment by mramato** [comment]
Sorry for the lack of a reply here @imenjomaa.  This data now tiles but looks kind of funky.  When I opened the KMZ you uploaded directly in Google Earth, there were a bunch of errors reported with the models. Are you sure this data is valid?

I restarted your asset, so you can now view it in Cesium, but the errors in the data means the geometry is not quite right (but seems to match Google Earth).

**Comment by OmarShehata** [comment]
Since this is now tiling successfully in Cesium ion, I'm going to close this.

@imenjomaa feel free to follow up if you're still having issues here, or open a new issue.
