### ISSUE TITLE
Tiling issue with asset id: 32043

### ISSUE THREAD

**Issue by jzhe3** [AnalyticalGraphicsInc/cesium-ion-community#188]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
It looks like you uploaded a Shapefile, which Cesium ion doesn't currently support. Do you have a way of converting that to a CityGML or something like that? You can see a full list of supported formats here:

https://cesium.com/docs/tutorials/uploading/

**Comment by OmarShehata** [comment]
I'm closing this now @tomorrgod but feel free to follow up or open a new issue if you're still having trouble!
