### ISSUE TITLE
3D model from Rhino fails to tile

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#189]
Hi guys, I tried to upload an OBJ file I exported from Rhino and it failed. Asset ID: 32024.

Could you let me know why?

Thanks,

**Comment by OmarShehata** [comment]
Looks like this produced an internal error. It seems the asset was deleted, so I can't debug any further. Are you able to re-upload it and let me know the new asset ID?

**Comment by pablocbre** [comment]
Hi Omar, I'll do that and let you know the asset id.

Also, before I forgot to point that the tiling process did start and went all the way up to 66%, then got stuck in there.

**Comment by pablocbre** [comment]
New ID is 32573, right now it's "Retrieving Data for Processing".

**Comment by OmarShehata** [comment]
Thanks for re-uploading! I can see it getting 66% stuck as well locally, so I don't think it's a memory issue in the ion platform. I'm surprised because it looks like this model isn't particularly huge file-size wise. 

I'm going to try investigating this more and update back here.

**Comment by pablocbre** [comment]
Okay, thanks a lot Omar. Looking forward to your findings.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
