### ISSUE TITLE
Access to asset metadata

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#19]
I would like to be able to retrieve metadata for an asset, especially bounding box, for terrain and imagery.  Additionally, it would be nice if I could specify bounding box and/or position information for assets that don't have easily discovered values.

**Comment by hpinkos** [comment]
Thanks for the suggestion @GatorScott!  If anyone has ideas for what other metadata would be helpful, please let us know.

**Comment by OmarShehata** [comment]
There is an issue open for getting the extents of terrain after tiling here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/152

You can also request an asset's metadata here with the REST API: https://cesium.com/docs/rest-api/#operation/getAsset

So you _could_ store a JSON object in the description and essentially use that as your metadata store. But if this is a common use-case it might be nice to have a more user-friendly non-ad-hoc solution.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/get-bounding-box-for-asset-through-cesium-ion-rest-api/10386
