### ISSUE TITLE
Add support for tiling georeferenced JPEG files

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#190]
Asset 33263 is a collection of JPEG files with associated world files (JGW).  Please add the ability to specify the spatial reference system associated with the image set, in this case WGS84.  GDAL supports this via the a_srs option.

**Comment by OmarShehata** [comment]
Thanks for submitting this @GatorScott. So just to clarify, the JGW file does not contain the spatial reference system used? So you'd have to enter that separately when uploading to ion?

**Comment by OmarShehata** [comment]
This is now supportedWe're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
