### ISSUE TITLE
Change in property naming?

### ISSUE THREAD

**Issue by pablocbre** [AnalyticalGraphicsInc/cesium-ion-community#191]
Hi guys,

I wanted to confirm whether the following change has happened in Ion's 3D tiling process. We think that the automatically generated properties 'latitude', 'longitude' and 'height' have been renamed to 'Latitude', 'Longitude' and 'Height'.

A bit of context: 

I usually work with CityGMLs that contain many buildings. In our code, we use a lot the properties 'latitude' and 'longitude' for several purposes. 

Yesterday we uploaded a new layer and many parts of our code related to flying to buildings started to raise errors. After doing some research, we realised that our code was looking for 'latitude', 'longitude' and 'height' in lowercase, but the layer had 'Latitude', 'Longitude' and 'Height' with the first character in uppercase.

We examined assets uploaded weeks and months ago and all of them had those properties in lowercase.

So, could you confirm if it's a change in the Ion tiling process, and if so, whether it will be permanent?

**Comment by OmarShehata** [comment]
You are correct, in addition to those 3 becoming uppercase, two properties were removed: `CityGMLObjectID` and `numberOfRenderedPrimitives`. Changing them to uppercase was done to make the property names consistent with the output for the other pipelines (for OBJs, point clouds etc). 

So yes, this should be a permanent change, and this was something that should have been communicated better. There does exist a changelog (https://cesium.com/ion/changelog) but it isn't up to date. We're working on updating that and making it easier to follow any breaking changes like this. Hopefully should start seeing that this week or early next week. I apologize for the inconvenience here!

**Comment by OmarShehata** [comment]
The changelog has been updated! So you can now see all updates, including this naming change: https://cesium.com/ion/changelog
