### ISSUE TITLE
KML file with no 3D models produces internal error

### ISSUE THREAD

**Issue by giphahne** [AnalyticalGraphicsInc/cesium-ion-community#193]
Asset ID: 34235

**Comment by OmarShehata** [comment]
This is the same issue as: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/192#issuecomment-511539818. The uploaded file does not contain any 3D models.

I'll leave this open until we can improve the error reporting displayed here.

**Comment by OmarShehata** [comment]
This has been resolved! See the response here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/192#issuecomment-519205584
