### ISSUE TITLE
OBJ with TIFF images fails to tile

### ISSUE THREAD

**Issue by Skrotice** [AnalyticalGraphicsInc/cesium-ion-community#194]
Asset ID: 34256. It's a 3D model in obj with mtl and textures.

[105012 (2).zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/3388405/105012.2.zip)
[105012 (2).zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/3388406/105012.2.zip)

**Comment by OmarShehata** [comment]
The issue here is that the uploaded images are TIFF, whereas Cesium ion currently only supports JPEG/PNG.

We're working on adding support for TIFF files, but in the meantime, can you try converting the input to JPEG/PNG and let me know if it works?

**Comment by Skrotice** [comment]
It works when I convert the input to JPEG.

**Comment by OmarShehata** [comment]
ion will now ignore unsupported images (such as TIFF), and we're working on implementing a warning system so you can see which files were ignored and why.
