### ISSUE TITLE
Tiling issue with asset id: 34275

### ISSUE THREAD

**Issue by Skrotice** [AnalyticalGraphicsInc/cesium-ion-community#195]
<Please provide a short summary of your data.>I am trying to upload an obj which is transformed from .max. But when I exported the obj with uv the ion could not process it, and it worked without uv.

**Comment by Skrotice** [comment]
Tiling success with asset id:34272

**Comment by OmarShehata** [comment]
At first glance, this seems like the same as https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/194, but it looks like one model with TIFF images is indeed tiling successfully, so I'll have to investigate if that's going through a different code-path for some reason.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
