### ISSUE TITLE
KML file with no 3D models produces internal error

### ISSUE THREAD

**Issue by 18801268763** [AnalyticalGraphicsInc/cesium-ion-community#196]
Asset ID: 343202. This a piece of sample 3D Tiles,I wanna test it on my server,but somehow it didn't work.

**Comment by OmarShehata** [comment]
This is the same issue as https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/192#issuecomment-511539818. You can directly load this into CesiumJS as I describe there, although in your case it looks like you might want to upload the imagery directly to tile that. 

You can see a list of the currently supported formats here: https://cesium.com/docs/tutorials/uploading/

I'll leave this open until we can improve the error reporting displayed here.

**Comment by OmarShehata** [comment]
This has been resolved! See the response here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/192#issuecomment-519205584
