### ISSUE TITLE
Add support for gltf 2.0 models

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#2]
Hello,

I am trying out Cesium ION and wanted to try a few models, but they all seem to fail. I was trying out this GLTF file:
https://drive.google.com/file/d/1i0W4O2UkM9vQze85UC2ZwLRtwht62OTP/view?usp=sharing
It opens fine in the built-in Windows viewer:
![image](https://user-images.githubusercontent.com/1240481/39622820-d525d9ea-4f93-11e8-85ce-66db0dc7799f.png)

But when I upload it to Cesium ion, I get an error:
 There is an unexpected error and we are unable to view your asset

The asset id in cesium is 4430, if you need, but the issue should be easy to reproduce

I'll post separate issues for the other problems
Thanks,
Fabien

**Comment by hpinkos** [comment]
Hi @fnicollet!  3D Model support on Cesium ion is still in beta, and we currently only support glTF 1.0 models.
This appears to be a glTF 2.0 model.  We hope to update to support glTF 2.0 later this year.  Thanks!

**Comment by mramato** [comment]
@hpinkos I've re-opened this issue.  We won't want to close this until @fnicollet's use case is actually implemented.

@fnicollet, sorry that you have been running into issues.  @hpinkos is correct in that our glTF support is still at 1.0 and in early beta.  As soon as our pipeline is updated for 2.0, I will verify the model you linked to works correctly and update this issue.

We are also in the process of improving our UX to better indicate beta features.  If you would like to opt out of being a beta user so that you only see features ready for production, just let us know and we can flip that switch.

Thanks again for trying out Cesium ion!

**Comment by fnicollet** [comment]
Hello @hpinkos and @mramato and thanks for your two answers,

I would rather stick with the beta version, so that I can give you feedback on what works and what doesn't. 
I'll probably open some issues that you can close easily, but at least if other users stumble on the same issue, they can find it on github.

In the meantime, maybe add a feature to your backlog, such as adding an error message to the end-user when the asset could not be imported (where you can just say that the uploaded asset is in unsupported format gltf 2.0)

Fabien

**Comment by akolymparis** [comment]
I would like to chime in just to say I have stumbled on the same issue.

Gltf 2.0 files that seem to validate as correct and without errors on the online validator and that also load just fine in VSCode's renderer produce the error mentioned above.

On the other hand, a Gltf 1.0 file I had created in my previous implementation which did show one error and some warnings in the validator did load just fine, while another gtlf1.0 file seems to be stuck in Processing at 25%.

**Comment by fnicollet** [comment]
Can you host the gltf files somewhere? It will probably help the cesium
staff reproducing the issue

**Comment by akolymparis** [comment]
Certainly.
Keep in mind that these are produced from an exporter we implemented using the models produced by this project: https://github.com/KhronosGroup/glTF-CSharp-Loader

The gltf 2.0 that doesn't Load is this one:
https://drive.google.com/file/d/1L8IRwAMdEaPIaVx5ayFLqWExjAOcPR3Z/view?usp=sharing
It is reported as having no errors on this validator:
http://github.khronos.org/glTF-Validator/
and it also has no errors and renders correctly inside VSCode's GlTF Tools (v.2.1.12)

The Gltf 1.0 model that loads in ion is this one:
https://drive.google.com/file/d/16xwCC2-7-BRnL5aNYhkrJ70o40stIVP4/view?usp=sharing

The gltf 1.0 file  that is stuck on 25% processing is this one:
https://drive.google.com/file/d/1__WaaUhMwmRrxgNIBhTWIaLs9eUQwHcB/view?usp=sharing

The gltf 1.0 files both load and render fine in this online viewer:
https://www.virtualgis.io/gltfviewer/

I hope these help.

**Comment by hpinkos** [comment]
Thanks @akolymparis!  Having the files will definitely help us debug.  We'll give you an update once we have a chance to look into this.

**Comment by tkazik** [comment]
I think I would rename this feature request into something like "support for gltf 2.0 models" to make it clearer. Looking forward for the gltf 2.0 support...keep up the good work!

PS: CesiumJS supports gltf 2.0 since 1.36 (https://github.com/AnalyticalGraphicsInc/cesium/pull/5641)

**Comment by hpinkos** [comment]
Thanks for the suggestion @tkazik!  I did update the title to make this easier to track and for other users to find.

While Cesium supports glTF 2.0, our glTF pipeline currently does not.  We run all models through the glTF pipeline to optimize them for efficient streaming on the web.  We have a 2.0 branch started, but haven't had a chance to finish it yet.  We'll give you guys an update once we add this support.  Thanks!

**Comment by lilleyse** [comment]
glTF 2.0 is now supported in ion.
