### ISSUE TITLE
Unable to access cesium in Iraq

### ISSUE THREAD

**Issue by nabazgharib** [AnalyticalGraphicsInc/cesium-ion-community#200]
Hi, I want to build a project based on cesium, but unable to access the website.

![image](https://user-images.githubusercontent.com/4522358/61518757-ffd82780-aa12-11e9-8f0a-7388c4a4cdff.png)

**Comment by OmarShehata** [comment]
Hey @nbaghm, unfortunately this is a known issue, see Matt's answer here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/31#issuecomment-420769860

Hopefully we're able to revisit this policy soon. Feel free to follow the discussion in that linked issue.
