### ISSUE TITLE
KML+COLLADA fails to tile with clamping on terrain

### ISSUE THREAD

**Issue by truijllo** [AnalyticalGraphicsInc/cesium-ion-community#203]
Asset ID 35113. error in tiling process, I don't know the reason .....

**Comment by OmarShehata** [comment]
Thanks for reporting this @truijllo. This error seems to happen while clamping to terrain. I'm sure entirely why yet but I'll investigate more and update this issue.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're still having issues, please post on the community forum!
