### ISSUE TITLE
glTF fails to tile

### ISSUE THREAD

**Issue by unionTime** [AnalyticalGraphicsInc/cesium-ion-community#204]
Asset ID: 35189
3dmax export *.obj
obj2gltf convert *.obj to *.gltf

error:
We're having trouble with your data. To help fix it, please open an issue in our Github repository. 
If you don't have a GitHub account, email support@cesium.com with the asset ID: 35189.

**Comment by OmarShehata** [comment]
Thanks for reporting this @unionTime. I'm looking into this specific issue, in the mean time, it might work if you either upload the OBJ directly, or use `--separate` flag for `obj2gltf` to have a separate geometry buffer.

Let me know if that helps.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
