### ISSUE TITLE
MacOS temporary files cause job to fail

### ISSUE THREAD

**Issue by lym95** [AnalyticalGraphicsInc/cesium-ion-community#207]
Asset ID 37219

**Comment by OmarShehata** [comment]
@lym95 this is failing due to the temporary files being uploaded under the `__MACOSX` directory. These files have an `.obj` extension but are not valid OBJ files. 

Try re-uploading without that folder and it should work.

**Comment by OmarShehata** [comment]
Cesium ion now ignores the `__MACOSX` directory so it should prevent errors like this in the future. You can see the full changelog for today's update here: https://cesium.com/ion/changelog#2020-03-31
