### ISSUE TITLE
Cannot clamp small models to terrain

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#210]
This came up with the ion getting started tutorial: https://github.com/AnalyticalGraphicsInc/cesium/issues/8084

If you try to tile `AGI_HQ.kmz` with Cesium World Terrain as a terrain reference, it'll come out on the ellipsoid (so the same height regardless of whether or not you pick terrain). This seems to affect only small models, and was introduced in [the 2019-08-07 change log](https://cesium.com/ion/changelog#2019-08-07).

**Comment by fnicollet** [comment]
Hello,

I am also having the same issue with a CityGML file (not sure it's considered as "small" or not, it is 200Mb zipped with textures). Selecting the "Clamp to terrain" option with "Cesium World Terrain" during upload seem to have no effect on the visualisation, the model is still "floating" in the air:
![image](https://user-images.githubusercontent.com/1240481/73166991-4c559b80-40f7-11ea-9c0d-ae687d06b4db.png)

The only difference seems to be that on the clamped asset, Cesium Ion loads the world terrain as well.

Clamped asset ID: 69219
Not-Clamped asset ID: 69109

The CityGML dataset can be downloaded here:
https://download.data.grandlyon.com/files/grandlyon/localisation/bati3d/LYON_6EME_2009.zip
Then uploading one of the GML from that zip file, for instance "LYON_6EME_BATI_REMARQUABLE_2009.gml"

Thanks,
Fabien

**Comment by OmarShehata** [comment]
The original issue has been fixed. I think the issue with the CityGML above is that it's not using one of the tags that Cesium ion clamps to ground:

> When terrain clamping is enabled, CityGML will adjust the height of the following object types:
CityFurniture
GroundSurface
Track
Road
Railway
Square
ReliefFeature
LandUse
TransportationObject

From: https://cesium.com/docs/tutorials/uploading/.

Note that we're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

For any follow up questions, please open a new topic in the community forum!
