### ISSUE TITLE
Failing to convert DAE models

### ISSUE THREAD

**Issue by sksun** [AnalyticalGraphicsInc/cesium-ion-community#212]
Asset ID: 38854. error for model without texture

![image](https://user-images.githubusercontent.com/7529648/63609222-51269880-c609-11e9-8e81-74d69f1fb58d.png)

**Comment by OmarShehata** [comment]
Thanks for reporting this @sksun . I think there might be several issues here, one of which might be a race condition while converting some of the models here. I've restarted this job on your account, and it tiles successfully, but the bounding volume for the tileset seems much larger than it should be. Although I can see these buildings in CesiumJS when zooming in to where they are.

We'll look into it and update this issue.

**Comment by sksun** [comment]
Hi, Shehata

Thanks for your help!
However, the models still missing their colors. Is it possible to solve this?
By the way, how is the status for our previous report (Error while reading COLLADA texture (#202) )?

B. R.

Kevin Sun 孫樹國 博士
CEO 總經理
Omniguider Inc. 鴻圖股份有限公司
Tel:+886-2-5569-1686 ext. 13905 
Mobile: +886-920-053-114 

寄件者: Omar Shehata
傳送時間: 2019年8月24日 上午 02:05
收件者: AnalyticalGraphicsInc/cesium-ion-community
副本: sksun; Mention
主旨: Re: [AnalyticalGraphicsInc/cesium-ion-community] Tiling issue withasset id: 38854 (#212)

Thanks for reporting this @sksun . I think there might be several issues here, one of which might be a race condition while converting some of the models here. I've restarted this job on your account, and it tiles successfully, but the bounding volume for the tileset seems much larger than it should be. Although I can see these buildings in CesiumJS when zooming in to where they are.
We'll look into it and update this issue.

**Comment by OmarShehata** [comment]
@sksun so it looks like the issue here is that the models are referencing materials with textures that don't exist, so Cesium ion replaces that with a default white textures, which overrides the model colors. Whereas Google Earth does not rendering any textures at all so the underlying colors are visible.

Are you able to re-export your models without the invalid textures? Was this exported from Sketchup or something else?

**Comment by OmarShehata** [comment]
Hey @sksun , we've fixed the initial issue so the model should now be tiling succesfully. It will still appear as white since Cesium ion will replace the "missing" textures with white. Re-exporting it without any textures should correctly display the model colors.
