### ISSUE TITLE
Unable to upload all asset file

### ISSUE THREAD

**Issue by Grkmus** [AnalyticalGraphicsInc/cesium-ion-community#215]
I can not upload data to the cesium ion. I tried to upload reichstag.gml as in the tutorial, it starts to upload getting %100 and suddenly fails by giving error "Unable to upload all asset file". I also tried to upload data from FME using this tutorial. https://cesium.com/docs/tutorials/integrating-with-fme/ but it also failed as well. Am I doing something wrong or is this an issue related to cesium ion. Thanks for your help.

**Comment by OmarShehata** [comment]
It sounds like you're doing the right thing @Grkmus . Can you try uploading the building model in this tutorial:

https://cesium.com/docs/tutorials/getting-started/#loading-your-own-data

Do you get the same error? If so, can you open your browser's developer console to see if there are any errors in the console or network tab reported when the upload fails?

**Comment by OmarShehata** [comment]
Also @Grkmus if you can tell me your username and a date/time of when the upload failure happened it'll help us see if it's an issue we can resolve on our end.

**Comment by Grkmus** [comment]
Hi!
Thank you for quick response. I tried with this tutorial but it didn't worked as well. I took two quick snapshots of what I get and what has been printed on developer console. 
The date/time of this attempt is 27.08.2019 19:15. My username is tosungo.
![image](https://user-images.githubusercontent.com/9647128/63793062-8bdd4900-c907-11e9-8b4e-6e04d023de35.png)
![image](https://user-images.githubusercontent.com/9647128/63793031-76681f00-c907-11e9-8a5e-d0f78596d2de.png)

**Comment by Grkmus** [comment]
Have you had a chance to review this issue? Thanks for your efforts.

**Comment by OmarShehata** [comment]
@Grkmus it looks like part of the issue may be that `assets.cesium.com` seems to be inaccessible from your network. Can you try this test link?

https://assets.cesium.com/ion-credit.png

If it works, it should display the Cesium ion logo. If it doesn't, can you tell me what you see?

**Comment by Grkmus** [comment]
Hi! Thanks for your reply. Today I have tried to upload the reichstag.gml again and it worked! I don't know what you have changed on the system or what I did different but, it is working now. :+1: To be more informative for those who are having this particular problem; I would like to give more information about what was the issue but, I don't know what has changed since I had this problem. Hopefully it is working for everyone now. Thanks for your support!

**Comment by OmarShehata** [comment]
Thanks for trying it again and updating this issue @Grkmus ! The only thing I can think of is if some configuration changed in your network. Did you get a chance to try out the test link (https://assets.cesium.com/ion-credit.png) when it wasn't working? Does that link currently work for you now?

**Comment by OmarShehata** [comment]
I'm closing this but feel free to post any more info if you have it, or follow up if the issue occurs again.

**Comment by Grkmus** [comment]
Yes I have tried the link that you provided and could seen the logo. So, I think it is working now.  Thanks.
