### ISSUE TITLE
Tiling issue with asset id: 39089

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium-ion-community#216]
Hi ,
My KMZ file is not able to 3d tile using cesium ion. I have converted my .dgn file to shape file using ARCGIS and then to  KMZ file using ARCGIS. And also i converting into KML using google earth, cesium ion is not allowing to upload. Please help me resolving the issue.

**Comment by OmarShehata** [comment]
Cesium ion doesn't currently support tiling vector data. There's a feature request for this here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/130. The KML/COLLADA files you can upload to Cesium ion are 3d models where the location of each model is specified by the KML file (you can see an example of this type of data in the [getting started tutorial here](https://cesium.com/docs/tutorials/getting-started/#loading-your-own-data)). 

The good news is you can view this data directly in CesiumJS! You can drag and drop it in this viewer link to test it out:

https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html

Here's a code example of how to load it in CesiumJS:

https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=KML.html

**Comment by OmarShehata** [comment]
Another alternative is if you can export your file as something like CityGML, you could tile that on Cesium ion.
