### ISSUE TITLE
Cesium visualization issue with asset id: 39869

### ISSUE THREAD

**Issue by bertt** [AnalyticalGraphicsInc/cesium-ion-community#217]
Data: Zip file with GML data

**Comment by OmarShehata** [comment]
This tiling job seems to have completed successfully. Can you describe what the issue is that you're seeing? @bertt

**Comment by bertt** [comment]
ah yes looks good. Saw an error message fairly soon.

**Comment by OmarShehata** [comment]
It sounds like this asset is working as expected - if you're running into any trouble feel free to follow up here or open a new issue!
