### ISSUE TITLE
Uploading Shapefiles as CityGML produces unhelpful error

### ISSUE THREAD

**Issue by Xclelo** [AnalyticalGraphicsInc/cesium-ion-community#218]
Asset ID: 40048

**Comment by OmarShehata** [comment]
Hey @Xclelo ! Were you able to get your data uploaded to Cesium ion? We don't support uploading shapefiles, but if you can convert them to CityGML or something else (with tools like Safe FME etc.) you can then upload them to ion.

You can see a list of all the currently supported formats on ion here: https://cesium.com/docs/tutorials/uploading/
