### ISSUE TITLE
Uploading a 3D model

### ISSUE THREAD

**Issue by wendyHYR** [AnalyticalGraphicsInc/cesium-ion-community#22]
Hello,
I tried uploading a 3D model to Cesium ION, but I can't find the access to uploading the 3D model in Cesium ION.
![image](https://user-images.githubusercontent.com/41276109/42741437-d937a6dc-88e4-11e8-911e-953ee963c749.png)
So, how can I uploading a 3D model to Cesium ION. I'll test it for my paper.
Thanks
Wendy

**Comment by hpinkos** [comment]
Hi Wendy! 3D model support is currently in beta and we have a bit of work to do before we release it to all ion users.  We want to make some updates to our glTF pipeline to support glTF 2.0 first.  We'll give you an update when this feature is ready.  Thanks!

**Comment by NicolaiLolansen** [comment]
What is the status on uploading 3D models, in the formats listed as "supported"? I have tried uploading .obj, .dae and .gltf files with weird errors such as "parents of undefined is undefined" and the like. The .gltf file works in my offline version of cesium, but the ion asset does not. 

Is the tiling pipeline finished, or still in development?

**Comment by mramato** [comment]
@NicolaiMogensen where are you seeing 3D Models listed as supported in Cesium ion?  They are still in beta and any public documentation listing them as supported should be updated to reflect that.  We don't currently have an ETA of when obj/dae to glTF conversion or direct glTF upload will be in production.

CesiumJS on the other hand, has full glTF support but does not read other model formats.

I apologize for the confusion.

**Comment by NicolaiLolansen** [comment]
@mramato Well in the Cesium ion interface there is an "upload asset" functionality. In the blue information box it lists all the "supported" formats. But i guess it's not implemented yet then. I did not find any documentation on it. 

![image](https://user-images.githubusercontent.com/11227437/45550809-4de93100-b82c-11e8-9a95-a1a46bc9546f.png)

If you upload .obj it even allows you to "3D Tileset" it. The file uploads and shows as "3D Tileset" in the asset list, but does not work. 

![image](https://user-images.githubusercontent.com/11227437/45550922-a3bdd900-b82c-11e8-8f7c-76eb560ad4a8.png)

I guess this is expected, but maybe the information box should be updated then

**Comment by mramato** [comment]
@NicolaiMogensen it looks like you are in the ion beta. beta features are noted by the little beaker icon next to the asset type. This should actually work for you.  Can you share 4.obj with us?

**Comment by NicolaiLolansen** [comment]
@mramato Gotcha. Yes I can share it, but I have experienced a bit with the coordinate system. What is the best way to "orient" the file, and in which coordinate system do you prefer 3D files to be in. If I place it in WGS84, what do I do with the z-coordinate, is it meters over terrain, or something else?

My .gltf files are in a local coordinate system relative to some center point, which then "fits" once it's added to the scene.

**Comment by mramato** [comment]
glTF upload support for 3D Tiles tiling is now available in ion.  We also have greatly improved overall obj/dae/gltf compatibility since this issue was written.  

I've also written up #131 to cover supporting conversion and serving of glTF models instead of 3D Tiles.  I'm going to close this, but please let us know if you have any additional questions/problems.  Thanks!
