### ISSUE TITLE
Update asset without changing asset ID

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#220]
It would be nice to be able to update an asset without changing its asset ID. For example, we recently made an update to the AGI HQ in our Sandcastle examples to use the correct material (see https://github.com/AnalyticalGraphicsInc/cesium/pull/6973/files). This involved updating the asset ID in all the applications that use it. 

This also came up over email.

**Comment by gvanwagner** [comment]
I would love this functionality for a project that I am working on.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/add-ability-to-update-an-asset-on-cesium-ion/10523
