### ISSUE TITLE
SketchUp model fails to tile with Draco compression

### ISSUE THREAD

**Issue by VnGIS** [AnalyticalGraphicsInc/cesium-ion-community#221]
Asset ID 43053. My sketchup file can not rendering.

**Comment by OmarShehata** [comment]
@VnGIS it looks like the issue here is that it fails to do the geometry compression this model (that's the "Draco compression" option). 

If you turn off this option when uploading to Cesium ion, it should work. We'll look into fixing this and I'll update this issue when a fix is deployed.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're still having issues here, please post on the community forum!
