### ISSUE TITLE
glTF -> 3D Tiles is hung, possibly because it has lines?

### ISSUE THREAD

**Issue by kring** [AnalyticalGraphicsInc/cesium-ion-community#223]
We uploaded a glTF (actually GLB) to Ion, and processing has been hung for about 24 hours now:
https://cesium.com/ion/assets/43825

Tried glTF too but got the same result:
https://cesium.com/ion/assets/43921

The model displays fine in Cesium and in the Windows glTF viewer, but is slightly unusual in that it has lines (not just triangles), and it has an extension that indicates to our app that the lines should be drawn with a polygon offset so they look good. Ideally Ion would pass through the lines and the extension, but it at least shouldn't hang. :)

**Comment by OmarShehata** [comment]
Thanks for reporting this @kring! Looks like this the asset is actually failing to tile, but the failure isn't reported, so it will appear to hang forever. 

We'll look into it and see if it is the lines or something else.

**Comment by OmarShehata** [comment]
Good news, I am able to tile this successfully locally, so it's likely an issue with the environment the jobs run on the online platform.

However, it doesn't pass through the custom extension, but that should be easy to support.

**Comment by kring** [comment]
Thanks for taking a look @OmarShehata! Depending on how long it'll take to fix the online platform, do think you could send us the converted tileset in the meantime?

**Comment by OmarShehata** [comment]
@kring I've uploaded the tiled asset under the name "buildings - uploaded by Admin" to your account. Although it looks like it might be hard to see any definition in the buildings without the lines (which we currently only support for KML/COLLADA input, I opened a separate issue for this here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/228).

**Comment by russellar4** [comment]
I am having a similar issue for asset 55043.  It seems to be stuck Tiling.  Any assistance greatly appreciated.

**Comment by OmarShehata** [comment]
Just to loop this in, asset 55043 turned out to be a different issue https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/246.

**Comment by russellar4** [comment]
If it helps with troubleshooting. Asset 47481 is the same CAD model but imported from a fbx and it imported ok.  
We can't use fbx for our application because our tool for reprojecting the models to ECEF can't output fbx only obj or glb.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
