### ISSUE TITLE
glTF with missing resource is not caught

### ISSUE THREAD

**Issue by BobHu14** [AnalyticalGraphicsInc/cesium-ion-community#225]
Asset ID 44920

**Comment by OmarShehata** [comment]
Thanks for reporting this @BobHu14. It looks like the issue with the uploaded glTF is that it's referencing shaders that were not uploaded:

```
"fragmentShader": "\\bob\\3ddata\\FL\\F\\F001\\fuzimiao010FS",
"vertexShader": "\\bob\\3ddata\\FL\\F\\F001\\fuzimiao010VS"
```

I also noticed there's a DAE included. If you upload just the DAE and the images it should tile correctly.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
