### ISSUE TITLE
Failed to tile FBX model

### ISSUE THREAD

**Issue by zubryan** [AnalyticalGraphicsInc/cesium-ion-community#226]
Asset ID 45122. I uploaded a fbx file with 2GB size, after uploading, it showed as follow. 
Is it an issue with tiling?
![image](https://user-images.githubusercontent.com/129747/65656116-42406500-e051-11e9-9652-15107ba2715e.png)

**Comment by OmarShehata** [comment]
Thanks for reporting this @zubryan. At first glance this looks like a bug on our end. We'll look into it and update this issue.

**Comment by zubryan** [comment]
Ah ok, update me when you have some progress, I just wanna try some big models.

**Comment by zubryan** [comment]
@OmarShehata is there an update?

**Comment by OmarShehata** [comment]
@zubryan we don't have a fix yet but we've narrowed it down to a bug that specifically affects FBX models.  What are you using to author/generate this model? You may be able to work around this in the mean time if you're able to export it another format like glTF and upload that.

**Comment by zubryan** [comment]
@OmarShehata  that's good, but it seems that Navisworks cannot export gITF. Let me try FBX2glTF first.

**Comment by zubryan** [comment]
FBX2glTF failed to change fbx to gITF. The process took several hours and was stuck in loading fbx as follow:
`mesh 19417: LcOaExGeometry (skinned: NO)`
Maybe the model is too big?

**Comment by OmarShehata** [comment]
Thanks for the additional info @zubryan. It is possible spitting up the model into 2 or more smaller piece could fix it. You could try uploading all these smaller pieces together to Cesium ion and it'll automatically combine them together.

**Comment by zubryan** [comment]
@OmarShehata I've already tried many pieces to upload to ion, but it failed after uploading and all files were removed automatically on ion. It has more than 10,000 fbx files.

**Comment by OmarShehata** [comment]
Can you tell me what the asset ID for that was @zubryan ? What did you use to split the models? 

Also, you can zip the files before uploading so that you're only uploading one zip file to make that process easier.

**Comment by zubryan** [comment]
I tried zip file, the error as follow, asset id: 48855, but file was removed automatically. @OmarShehata 
![image](https://user-images.githubusercontent.com/129747/66970160-fcf6dc80-f0be-11e9-999a-4d14154b0e26.png)

**Comment by OmarShehata** [comment]
@zubryan it looks like it failed to upload. How long does this take to upload before it fails? Does this only happen with the zip file (or does it happen if you try to upload the original FBX again now) ? How big is the zip file?

Can you see if there are any errors in the browser console or network tab when the failure occurs?

**Comment by zubryan** [comment]
It's an issue with Chinese Great Firewall :-(
It's working now but the rendering looks not good, many stuff missing. Asset ID: 49141
![image](https://user-images.githubusercontent.com/129747/67092289-6cfd8380-f1e1-11e9-8e9a-3c815cf401cd.png)

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This asset has been deleted, so I can't confirm if this is still an issue, but for any follow up questions or discussion please use the community forum!
