### ISSUE TITLE
Add line support to CityGML tiling

### ISSUE THREAD

**Issue by chaitanyajalluri** [AnalyticalGraphicsInc/cesium-ion-community#227]
Asset ID: 44970. The data contains the distribution power lines. It is in polyline-m format.

**Comment by OmarShehata** [comment]
Thanks for reporting this @chaitanyajalluri. Cesium ion doesn't currently support tiling `LineString` nodes in CityGML, so I've marked this as a new feature request.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
