### ISSUE TITLE
ASC file has missing SRS

### ISSUE THREAD

**Issue by bkkite** [AnalyticalGraphicsInc/cesium-ion-community#230]
Hello, 

Asset ID 46970. When i try to upload a file from National center of Geographical information (Spain), where there are several files with Digital terrein information in asc format appear this fail: 

Error: Missing or invalid spatial reference system
File: PNOA_MDT05_ETRS89_HU30_0519_LID.asc

Could you tell me more about this problem? What can i do?

**Comment by OmarShehata** [comment]
Hey @bkkite , thanks for reporting this issue! It looks like this file does not define any spatial reference system, which Cesium ion needs in order to correctly tile it.

Is this from a publicly accessible dataset? Can you post the link to it here?

**Comment by bkkite** [comment]
_Is this from a publicly accessible dataset? Can you post the link to it here?_

Yes, it is. Follow this link -> http://centrodedescargas.cnig.es/CentroDescargas/locale?request_locale=en. Then go to Digital Elevation Models and at bottom you can choose Digital Terrain Model - DTM05.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions on how to fix the missing SRS issue in your data, please post a new topic on the community forum.
