### ISSUE TITLE
Cesium-ion-SDK on npm

### ISSUE THREAD

**Issue by philip-firstorder** [AnalyticalGraphicsInc/cesium-ion-community#231]
Is there a link for the Cesium-ion-SDK on npm, so I can declare it in my package.json file?

The only repository I could find is https://www.npmjs.com/package/cesium, which is CesiumJS (without measurements)

As an alternative I downloaded the .zip file -> unzipped contents -> archived as .tar.gz file in Terminal using
`tar -cvzf cesium-ion-sdk-1.62.tar.gz Cesium-ion-SDK-1.62/*`
 and edited package.js:
`"cesium": "./cesium-ion-sdk-1.62.tar.gz",`

**Comment by OmarShehata** [comment]
Thanks for opening this issue @philip-firstorder ! There currently isn't an npm package for the ion SDK, but it's something we're interested in supporting. 

If others are also interested, please :+1: or comment here to let us know!

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
