### ISSUE TITLE
 map.scene.postRender.removeEventListener does not remove a listener

### ISSUE THREAD

**Issue by YordanYanakiev** [AnalyticalGraphicsInc/cesium-ion-community#233]
**map.scene.postRender.removeEventListener** seems like to not remove actually a listener which were attached to it.

**Comment by mramato** [comment]
@YordanYanakiev Here is a [complete example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=dZBPa8MwDMW/isklDgSHnZuGsbJbYbBuO+Xi2mpn6sjBVly60e8+J1lgf6hu0tPvPaEoPYsGzuDZmiGc2QaCGTrxNs14rqZ245CkQfB5sWqxxcOAioxDpqS1e6lOPChAKBmZDgr22SJLpRwGZ0FYd+STkNjriM+BYmJE7wK99loSCKn1YwSkrQmUJM8X+zl1J1ErGchOmy/OJc0/DEQOef4M0UVgC5qXbDmSF9/33Ir10CX0dvK1WGVlVge6WGhmq3vT9c4TG7zlQlQEXW+TVaj2gzoBCRXCSNbVAtXaRGb0us3+fLTNmLIyhKQcBmt35gParKmrtP8Ls05qg8enCN7Ky7jyftds56EQoq5S+5+i+Uk/HL8A) which logs to the console until you hit the remove button. Everything is working as expected.

If you are still having issues, please re-open this issue with a reproducible test case and/or sample code and in the future please include steps for reproduction in any new issues you may open.

Thanks.
