### ISSUE TITLE
about WebGL2RenderingContext

### ISSUE THREAD

**Issue by Longbao521** [AnalyticalGraphicsInc/cesium-ion-community#234]
`var canvas = viewer.scene.canvas;
    if(!canvas){
      console.log('....');
    }else{
      console.log(canvas);
      var gl = canvas.getContext('webgl2');
      console.log(gl);
    }

    var canvas_2 = canvas.cloneNode(true);
    document.body.appendChild(canvas_2);
    var ctx = canvas_2.getContext('webgl2');
    console.log(ctx);`
Why cesium canvas is not available the WebGL2RenderingContext

**Comment by OmarShehata** [comment]
If you're trying to use CesiumJS with WebGL 2, you'll need to initialize the viewer this way:

```
var viewer = new Cesium.Viewer('cesiumContainer', {
    contextOptions: { requestWebgl2: true }
});
```

Although note that there are some known bugs with CesiumJS running with WebGL 2: https://github.com/AnalyticalGraphicsInc/cesium/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+webgl2

**Comment by Longbao521** [comment]
Yes，but i failed at that postProcess,the texture can not render

**Comment by Longbao521** [comment]
if I run in the webglRenderingContext,it will run well,but in the webgl2RenderingContext.it does not look that well.

**Comment by OmarShehata** [comment]
Can you post a full [Sandcastle](https://sandcastle.cesium.com/index.html?) example of your code that I can run? You can click "Share" to get a link that you can post here.
