### ISSUE TITLE
Tiling issue with asset id: 52205

### ISSUE THREAD

**Issue by terre-virtuelle** [AnalyticalGraphicsInc/cesium-ion-community#239]
Hie,
I can't upload a citygml file with TINRelief for 3DTiling
 <cityObjectMember>
    <dem:ReliefFeature gml:id="TIN_73_104">
      <dem:lod>2</dem:lod>
      <dem:reliefComponent>
        <dem:TINRelief gml:id="TIN_73_104_0">

Thank's

**Comment by OmarShehata** [comment]
@terre-virtuelle Cesium ion doesn't currently support tiling terrain features in CityGML. As a workaround, if you can export your terrain as a GeoTIFF, or a DEM file you can upload it to Cesium ion. You can then upload a CityGML file with buildings in it to clamp it to that terrain if needed. 

There's a full list of all the source formats that can be tiled into terrain here: https://cesium.com/docs/tutorials/uploading/

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're still having issues here, please post on the community forum!
