### ISSUE TITLE
Support reading geographic metadata from Blender OSM plugin

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#240]
This [came up on the forum](https://groups.google.com/d/msg/cesium-dev/fRN4VEogQB4/eX49N_tGBAAJ). There is a Blender OSM plugin that allows you to import OSM buildings which can then be exported to ion:

https://github.com/vvoovv/blender-osm

It also has an option of georeferencing the model. I'm not sure whether it embeds that location in the model or exports a sidecar file etc, but supporting this could be an easy way to get OSM -> 3D Tiles in Cesium ion.

CC https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/232

**Comment by OmarShehata** [comment]
Alternatively this is something that could be handled in the Cesium ion Blender plugin (https://github.com/AnalyticalGraphicsInc/cesium-ion-blender-addon) since the ion REST API allows you to pass a location for the tileset.

**Comment by baffioso** [comment]
https://github.com/domlysz/BlenderGIS also enables import of georeferenced geometries into Blender and would be amazing if the Cesium ion Blender plugin could preserve this information. Maybe @domlysz has any comments on this one?

**Comment by OmarShehata** [comment]
It would certainly be great to hear what kind of format BlenderGIS reads in the georeferenced metadata,    since we have been considering adding support for either some of the ones mentioned in this issue https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/39 or developing some JSON format that can be used to describe the location of each model.

**Comment by domlysz** [comment]
More infos here
https://github.com/domlysz/BlenderGIS/wiki/Georeferencing-management

vvoovv osm addon use another approach with an on the fly projection
https://github.com/vvoovv/blender-osm/wiki/Georeferenced-Blender-Scene
https://github.com/domlysz/BlenderGIS/issues/10

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We do have a separate issue we're tracking internally for tiling OSM data directly (which is how Cesium OSM Buildings was created: https://cesium.com/content/cesium-osm-buildings/). If anyone is working on any tools/documentation that make it easier to import this data into Cesium ion please share on the forum!
