### ISSUE TITLE
In the Cesium Workshop tutorial, the New York 3D Tiles fail to load (HTTP 404)

### ISSUE THREAD

**Issue by vhive-jonathan-carse** [AnalyticalGraphicsInc/cesium-ion-community#242]
![image](https://user-images.githubusercontent.com/55695533/68575234-4ba45600-0474-11ea-9d42-16a70291e2dc.png)

**Comment by hpinkos** [comment]
Thanks @jonathanvhive, this is a known issue and we'll let you know when we have a solution.  You can keep track of the status here: https://github.com/AnalyticalGraphicsInc/cesium-workshop/issues/10
