### ISSUE TITLE
Tiling issue with asset id: 54652

### ISSUE THREAD

**Issue by fidli** [AnalyticalGraphicsInc/cesium-ion-community#243]
Hello,
I have a gLTF and a .bin file.

When I upload them manually (and spy on POST request), they upload and pipeline works.

Following this tutorial (https://cesium.com/docs/tutorials/rest-api/)
Using same parameters (from the POST request I spied on) I can upload the files just fine. And everyhing seems ok.
But, in the ION web interface, I get a failure on tiling pipeline.

So, I downloaded the REST-api uploaded files from web interface and re-uploaded them manually, then It works. 
So I have a suspicion that this is a legitimate bug.

Here is a minimal python code, that reproduces this bug:

```
#!/usr/bin/python3
import requests
import boto3
import json
from botocore.exceptions import ClientError

if __name__ == '__main__':
	
	files = ["data.gltf", "data.bin"]
	ionToken = "" # provide Ion token here
	
	request = {
		"name": "test",
		"description": "",
		"type": "3DTILES",
		"options": {
			"sourceType": "3D_CAPTURE",
			"geometryCompression": "NONE"
		}
	}
	
	request = requests.post(url="https://api.cesium.com/v1/assets/", data=request, headers={"Authorization": "Bearer {}".format(ionToken)})
	response = json.loads(request.content)
		
	ion = boto3.client('s3', endpoint_url=response["uploadLocation"]["endpoint"], aws_access_key_id=response["uploadLocation"]["accessKey"], aws_secret_access_key=response["uploadLocation"]["secretAccessKey"], aws_session_token=response["uploadLocation"]["sessionToken"])
	
	for fileName in files:
		try:
			ion.upload_file(fileName, response["uploadLocation"]["bucket"], response["uploadLocation"]["prefix"] + fileName)
		except ClientError as e:
			print("Error occured while trying to upload to ION: " + str(e))
	
	request = requests.request(response["onComplete"]["method"], url=response["onComplete"]["url"], data=response["onComplete"]["fields"], headers={"Authorization": "Bearer {}".format(ionToken)})

```

Am I doing something wrong? Or is this really a bug?

**Comment by OmarShehata** [comment]
@fidli I think you need to change `data=request` to `json=request` since that sets the right content type when using the Python requests library. This was the same issue that solved: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/159#issuecomment-490075309

Let me know if that fixes it.

**Comment by fidli** [comment]
That fixed it. Thank you.
