### ISSUE TITLE
Large FBX fails to tile

### ISSUE THREAD

**Issue by tjhanson** [AnalyticalGraphicsInc/cesium-ion-community#245]
Asset ID 54990. large fbx file (4.3gb) with embedded textures. just says we are having issues with your dataset

**Comment by OmarShehata** [comment]
Thanks for reporting @tjhanson. This is the same issue as https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/226. As a workaround until we have a fix for this, you should be able to tile this either by exporting your model as a different format (such as glTF or OBJ) or exporting a collection of smaller pieces that Cesium ion will automatically fuse together.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This asset has been deleted, so I can't confirm if this is still an issue, but for any follow up questions or discussion please use the community forum!
