### ISSUE TITLE
How to add measurement tool to the viewer

### ISSUE THREAD

**Issue by Cezary885** [AnalyticalGraphicsInc/cesium-ion-community#249]
Hi,
I have a model from Reality Capture stored on Cesium Ion.
How to add measurement tool to the viewer?

**Comment by OmarShehata** [comment]
We're actually working on bringing this feature onto the Cesium ion platform! In the mean time, the Analytics SDK (which has the measurements as well as visibility analytics) is available with an on-premise license: https://cesium.com/ion-engine/

**Comment by Cezary885** [comment]
I contacted your sales team but I received no response

**Comment by OmarShehata** [comment]
@Cezary885 if you still haven't heard back, please reach out to support@cesium.com and we'll get it figured out.

**Comment by Cezary885** [comment]
Any progress on this measurement tool?

**Comment by OmarShehata** [comment]
Yes! This is now accessible as part of Cesium Stories:

https://cesium.com/blog/2020/01/28/cesium-stories/

So if you upload your data to Cesium ion, and then create a story, you can take distance, area and height measurements on it. Let me know if this works for you.
