### ISSUE TITLE
Process terrain with custom ellipsoid

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium-ion-community#25]
Ability to generate quantized-mesh terrain tiles with custom ellipsoids.

Brought up on the forum here: https://groups.google.com/forum/#!topic/cesium-dev/GefAAXtkiZI

> Ion generates quantized-mesh terrain tiles, which include a "horizon culling point", and that point is tied to the ellipsoid, which is (currently) always WGS84. So Maxime is right that changing the ellipsoid on the client will lead to culling problems. Modifying WGS84 on the client won't help, because the horizon culling point returned by Ion is still tied to the real WGS84.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/use-custom-ellipsoid-when-generating-3d-terrain-on-cesium-ion/4299/6
