### ISSUE TITLE
Large glTF model fails with "optimize" option

### ISSUE THREAD

**Issue by qizhaoheng** [AnalyticalGraphicsInc/cesium-ion-community#257]
big file. Asset ID 60967.

**Comment by OmarShehata** [comment]
It looks like the "optimize" option is causing this to fail - turning it both off should make it work.

For large models like this, you should choose "3D Model (tile as 3D Tiles)" to get a model that loads much faster and performs much more efficiently. Give that a try and let me know if that works for you.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
