### ISSUE TITLE
Cesium - Interscetion points

### ISSUE THREAD

**Issue by pradeepbaskandi** [AnalyticalGraphicsInc/cesium-ion-community#258]
Hello ,

Is it possible to find if any entity (e.g. a cylinder ) is intersecting a polygon ( at a height of 900Ft above the ground)

**Comment by OmarShehata** [comment]
Here's an answer to a similar question on the forum here: https://groups.google.com/d/msg/cesium-dev/G1prQsBM8j8/fne4h8mSAwAJ

Feel free to follow up there or let me know if you have any questions.
