### ISSUE TITLE
Write up token security best practices guide

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#26]
Questions regarding access token best practices recently came up on the Cesium forum: https://community.cesium.com/t/how-to-secure-ion-account/7308/2

We should create a document that explains best practices for our users.

We should also consider the suggestion of adding domain restrictions, and definitely expose and document the access token REST API in the future so users can automatically rotate tokens.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now, and you can also find info on best practices in the linked forum thread: https://community.cesium.com/t/how-to-secure-ion-account/7308/2?u=omar
