### ISSUE TITLE
Cesium visualization issue with asset id: 61288

### ISSUE THREAD

**Issue by lingling-007** [AnalyticalGraphicsInc/cesium-ion-community#260]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
Hey @lingling-007  - this asset seems to have been uploaded successfully. Can you tell me what issues you're having with it?

**Comment by OmarShehata** [comment]
I'm going to close this for now, but if you're still having issues feel free to follow up here or on [the Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev)!
