### ISSUE TITLE
KML/COLLADA fails to tile

### ISSUE THREAD

**Issue by BraveZhu1991** [AnalyticalGraphicsInc/cesium-ion-community#265]
We're having trouble with your data. To help fix it, please open an issue in our Github repository.

If you don't have a GitHub account, email support@cesium.com with the asset ID: 64104.

[kmz.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/4006661/kmz.zip)

**Comment by OmarShehata** [comment]
Thanks for reporting this @zhushuaibing . This is a bug on our end. I'm not sure what the exact cause is yet.

If you run into any other KML/COLLADA datasets like this that fail to tile, please let us know.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
