### ISSUE TITLE
GeoJsonDataSource loads points for the entire globe (even on the other side) slowing it down

### ISSUE THREAD

**Issue by Dosmi** [AnalyticalGraphicsInc/cesium-ion-community#266]
**Pictures speak better than words here:** _(but see more detailed description of problem below the photos)_
![image](https://user-images.githubusercontent.com/36490574/72396442-983a3500-3734-11ea-889c-a922e859b095.png)
![image](https://user-images.githubusercontent.com/36490574/72396476-af792280-3734-11ea-8d5b-9c35ebf33b10.png)

**This occured when testing Cesium on an older Android Phone (Samsung Galaxy S4, Android version 5.0.1, Cesium version 1.65, day of test 15th of January 2020. This induces extensive lag.** 

Switching to an older (1.4 I believe) version of Cesium fixes the .json loading problem and works very fast (no lag) and it loads as expected, showing only the coaslines that should be visible. Problem arises on the new version when loading a 'json' object as the new GeoJsonDataSource. 

**_The map .json file loads/works properly on a powerful computer and a flagship phone._**

**Comment by OmarShehata** [comment]
Thanks for reporting this issue @Dosmi. This sounds like a CesiumJS bug. If you can share the GeoJSON file causing this issue (or a smaller sample) I can open a bug report in that repository and isolate which version caused this issue. 

For reference you can easily test older versions of CesiumJS with the hosted Sandcastle. For example below is the Sandcastle for version 1.61:

https://cesium.com/downloads/cesiumjs/releases/1.61/Apps/Sandcastle/index.html?src=Offline.html

**Comment by OmarShehata** [comment]
@Dosmi I'm closing this issue here, but if you're able to share this file, feel free to follow up and we can open a bug report in the CesiumJS repo: https://github.com/CesiumGS/cesium.
