### ISSUE TITLE
Tiling issue with asset id: 66850

### ISSUE THREAD

**Issue by DEsiege** [AnalyticalGraphicsInc/cesium-ion-community#267]

**Comment by OmarShehata** [comment]
Our logs show this was an invalid CityGML file - were you able to resolve this @DEsiege ? Were you able to correctly visualize this file in other software, or where did you export it from?

**Comment by DEsiege** [comment]
Yes i was able to resolve this by converting the cityGML to 3d tiles using
FME quick transformation. I was able to correctly visualize it using FME
Data Inspector.
The Data was created using triangulator from FME.
I followed the tutorial on creating data from IFC 100 to Lod2 CityGML Data
https://knowledge.safe.com/articles/1023/bim-to-gis-basic-ifc-lod-100-to-lod-2-citygml.html

[image: image.png]
