### ISSUE TITLE
CLI modelconverter complains about collada file id: 67030

### ISSUE THREAD

**Issue by ghost** [AnalyticalGraphicsInc/cesium-ion-community#268]
When converting from collada to gltf, modelconverter.exe complains:

{"code":5,"debug":{"message":"Extra content at the end of the document\n"},"description":"Invalid File","filepath":"<path to file>.dae","type":"ERROR"}

Blender loads the file fine and XML Notepad shows no errors.
Re-export from Blender leads to the same error.
Let me know if this is a faulty collada file or if it has a structure unexpected by modelconverter.exe

**Comment by OmarShehata** [comment]
My best guess is this file might have Windows line endings vs Unix. If you're still having issues with this feel free to follow up here.
