### ISSUE TITLE
Error uploading tileset with non-latin characters

### ISSUE THREAD

**Issue by yangs1358145858** [AnalyticalGraphicsInc/cesium-ion-community#269]
Asset ID: 67572

**Comment by OmarShehata** [comment]
This asset seems to upload correctly if you rename it to just `B3dm.zip`.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
