### ISSUE TITLE
Investigate restricting tokens by domain or other properties

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#27]
This was suggested as part of the discussion linked to in #26.  I'm skeptical that it is a good idea because it will bloat the size of the token and also can be spoofed by clients (i.e. spoof the origin header) but it might be a good additional layer of security to prevent casual token copying.

**Comment by mramato** [comment]
A user has also requested the ability to restrict tokens by IP address.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
