### ISSUE TITLE
Error while uploading a zipped CityGML: Input does not contain any eligible features for tiling.

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#272]
Hello,

I have this error message:
Error: Input does not contain any eligible features for tiling.

When uploading a ZIP file containing a CityGML and the texture folder:
![image](https://user-images.githubusercontent.com/1240481/73169830-3d71e780-40fd-11ea-96c2-2954034f3a98.png)

You can download it here (600Mo):
http://drive-in.synaaps.com/telechargementdirect.php?refespace=5034&arbo=UHVibGlj&file=3c39325f3d4f2b4629c649a0a227c6b4&key=694abac5c9758840316a60d0adbf1824

Thanks for your help,
Fabien

**Comment by fnicollet** [comment]
Hello,

Do you have any idea on this issue? I can't seem to upload the simplest GML files, I always get this "Input does not contain any eligible features for tiling" error message.
I only have "Building" types in my GML file, does Cesium ION need other feature types in the GML to work properly?

Thanks!

**Comment by fnicollet** [comment]
Turns out it was an issue in my CityGML creation process. I was creating the CityGML file from FME, using the "Building" FeatureType only, but it looks like the CityGML Writer requires more attributes to be complete.
If anyone runs into this issue, before writing as CityGML, use the CityGMLGeometrySetter and pick:
```
citygml_lod_name: lod2MultiSurface
citygml_feature_role: boundedBy
```
Hope it helps,

**Comment by fnicollet** [comment]
(note for FME users, this article is very useful and has sample workspace you can work with: https://knowledge.safe.com/articles/72453/creating-a-textured-citygml-model.html)

**Comment by OmarShehata** [comment]
Thanks for posting your solution and links to the FME article @fnicollet ! I think it would definitely be useful to document exactly which features are supported in CityGML, and recommendations when exporting data from specific software like FME. I opened an issue here for documenting this: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/280
