### ISSUE TITLE
Document and expose Tokens REST API

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#28]
Currently, all token manipulation must be done via the UX while logged into ion.  Security best practices, such as automatic token rotation, require us to document an official Tokens API for users to be able to use programatically.

**Comment by mramato** [comment]
CC #26

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
