### ISSUE TITLE
Tiling issue with asset id: 72990 (CityGML with textures)

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#281]
Hello,

I uploaded a ZIP of a CityGML containing about 30K features (with textures) and at about 70% of the tiling process, it crashed. 
The CityGML is a file produced by RhinoCity, which I had to re-process with FME to add what appears to be mandatory attributes for Cesium ION.
Do you have a more precise error on your side?

Thanks!

**Comment by OmarShehata** [comment]
This does appear to be a bug in ion, I'm not sure what the exact cause is yet.

What attributes did you need to add with FME that weren't included in the RhinoCity export?

**Comment by fnicollet** [comment]
See this thread with the details:
https://github.com/CesiumGS/cesium-ion-community/issues/272#issuecomment-584141144

Fabien

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
