### ISSUE TITLE
Cannot position 3D Tileset using source model origin

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#282]
The goal is to position a 3D Tileset on Cesium ion using the source model's origin. For example, your model may look like this (screenshot from Blender):

![image](https://user-images.githubusercontent.com/1711126/74349916-f59cc280-4d82-11ea-8e7f-07642c9c31b4.png)

And you know what that lat/lon/heght this origin (0, 0, 0) is supposed to be at. So you upload this model to Cesium ion, enter the lat/lon in the "Adjust tileset" tool, but find that the position is incorrect. This is because Cesium ion will create a new origin at the center of the geometry:

![image](https://user-images.githubusercontent.com/1711126/74350330-97241400-4d83-11ea-9583-c0e8ace9892c.png)

In order to get this to work, you would need to use the Cesium ion REST API which allows you to pass a lat/lon/height when uploading the model. This will correctly position the model's origin at the given cartographic world position.

If this is something you'd like to see the Cesium ion UI support, please :+1: or comment here. Alternatively it may be useful to document/create a tutorial on this since it's not obvious this is the correct way to position it.

**Comment by OmarShehata** [comment]
This came up again on the forum a couple times:

* https://community.cesium.com/t/rendering-one-3d-tiles-asset-with-two-files-vs-two-assets-with-one-file-each/9305
* https://community.cesium.com/t/imprecise-3d-tile-rendering-coordinates/9432/4

**Comment by x4132** [comment]
What if you want to get Cesium to set the origin at the center of the geometry?

**Comment by OmarShehata** [comment]
@bluninja1234 I believe this is currently the behavior that happens if you upload your model and select "Tile as 3D Tiles", as either 3D Model or 3D Capture.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/how-to-correctly-position-3d-models-when-tiling-with-cesium-ion/10498
