### ISSUE TITLE
Display meaningful error for model with no geometry

### ISSUE THREAD

**Issue by sgj87** [AnalyticalGraphicsInc/cesium-ion-community#283]
Asset ID 73788

**Comment by OmarShehata** [comment]
@sgj87 it looks like this is a blank model so it fails to tile. I think the correct behavior here should be for Cesium ion to catch and report this error.

Can you tell me what your desired behavior here is? Where did you export this model from?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
