### ISSUE TITLE
Document how the point cloud tiler reads in metadata

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#286]
When uploading LAS/LAZ files, Cesium ion will pick up `Intensity` and `Classification` per-point properties. These properties can be styled in the 3D Tiles styling language. See:

https://sandcastle.cesium.com/index.html?src=3D%20Tiles%20Point%20Cloud%20Styling.html

(Note that this code example above uses `temperature` as a per-point property, which isn't a per-point property Cesium ion will pick up. It would probably be useful to update that example).

`Intensity` will be normalized from 0-255. 

An easy way to explore the per-point values in your point cloud is with the styling editor in Cesium Stories: https://cesium.com/blog/2020/02/18/3d-tiles-styling-with-stories/

**Comment by darkpaw** [comment]
I was just wondering how colour works with LAS files. The sandcastle example has coloured points:

https://sandcastle.cesium.com/?src=3D%20Tiles%20Point%20Cloud.html

But my LAS file in point format 2 with red, green, blue values shows up as 100% grey points.

So yes, some documentation would be nice!

**Comment by OmarShehata** [comment]
Hey @darkpaw, LAS files with RGB data should show up as colored. 

Can you tell me what the asset ID is for the asset that's showing up grey?

**Comment by darkpaw** [comment]
Thanks @OmarShehata - I didn't want to file a bug as it could well be that my file is bad.

It's 78922, the LAS was generated with pylas from some other point data.

**Comment by OmarShehata** [comment]
Thanks for sharing your asset ID @darkpaw. Looks like the issue there is that all points have the same color, so Cesium ion will ignore the color. It works the same way for Intensity and Classification values in order to keep the resulting tileset size small.

**Comment by darkpaw** [comment]
@OmarShehata Awesome thanks Omar! I wouldn't have expected it to do that. I will try the real colour values.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
