### ISSUE TITLE
Curious about model-tiler cmpt output

### ISSUE THREAD

**Issue by ghost** [AnalyticalGraphicsInc/cesium-ion-community#287]
Hi, I've noticed that the model-tiler produces cmpt, composite, tile formats that contain only a set of b3dm tiles. These cmpt tiles are in general larger than the single b3dm tiles.

I'm curious what the rational is? Why not just a bunch of b3dm's on their own?

Thanks

**Comment by OmarShehata** [comment]
Discussed over email, but the short answer is one reason you might want to use composite tiles in this way is to group together a set of b3dms that already exist instead of recreating a new b3dm.
