### ISSUE TITLE
Curious about the model-tiler REPLACE strategy

### ISSUE THREAD

**Issue by ghost** [AnalyticalGraphicsInc/cesium-ion-community#288]
Hi, I've noticed that the model-tiler will use the REPLACE strategy for tiles in such a way that the only difference between parent and child tile is the size of the texture map. The naming of the tile files gives it away e.g. 0material22_0.b3dm and 0material22_0_original_texture.b3dm.

I don't remember seeing a doc for this. I would like to know what triggers this decision (a map dimension > 1024 I'm guessing) and curious how the geometric error is computed in that case.

Thanks.

**Comment by OmarShehata** [comment]
Discussed over email - the tiling strategy depends on a lot of different factors. If anyone's running into issues with the 3D Tilesets you're getting from Cesium ion feel free to open an issue here or discuss on the community forum: https://community.cesium.com/
