### ISSUE TITLE
Model tiler instancing strategy

### ISSUE THREAD

**Issue by ghost** [AnalyticalGraphicsInc/cesium-ion-community#289]
Many building models contain highly instanced detailed geometry such as window assemblies, pipe assemblies or office furniture. I’m curious how the model tiler deals with these. A reasonable strategy might be to refer to the same b3dm tile several times throughout the JSON Tileset. Is that what should be expected?

**Comment by OmarShehata** [comment]
Discussed over email, Cesium ion doesn't currently use instancing for BIM/CAD inputs but it does for 3D buildings (or generally KML/COLLADA or CityGML input).
