### ISSUE TITLE
Document and expose asset retrieval API

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#29]
While it's completely possible to use ion assets from any client that supports the formats we use, it's not officially documented anywhere at this time.

See this forum post for reference: https://groups.google.com/forum/?place=forum%2Fcesium-dev&showsearch=true&hideforumtitle=true&fragments=true&parenturl=https%3A%2F%2Fcesiumjs.org%2Fforum%2F&theme=default#!topic/cesium-dev/oLv1S3OvsAo

**Comment by OmarShehata** [comment]
Does the API allow you to do things like set a tileset location? This came up on the forum here:

https://groups.google.com/forum/#!topic/cesium-dev/Xy9US3gDwfg

**Comment by OmarShehata** [comment]
How do you get a list of ion asset IDs forum question: 

https://groups.google.com/d/msg/cesium-dev/qB-xz1XooPo/qDYgsqVYAQAJ

**Comment by OmarShehata** [comment]
The REST API is now fully documented and exposed! See: https://cesium.com/docs/rest-api/ and a tutorial here: https://cesium.com/docs/tutorials/rest-api/ .
