### ISSUE TITLE
Tiling issue with asset id: 77489

### ISSUE THREAD

**Issue by 1392109** [AnalyticalGraphicsInc/cesium-ion-community#290]
![微信截图_20200228101405](https://user-images.githubusercontent.com/52774227/75504368-3a775900-5a13-11ea-8d47-5964dc114648.png)

![1](https://user-images.githubusercontent.com/52774227/75504403-55e26400-5a13-11ea-9cb0-853a026eb0d2.png)

**Comment by OmarShehata** [comment]
It looks like you only uploaded the `3D.gltf` file. You need to drag and drop both files into Cesium ion (or add them to a zip file and upload them). Let me know if that works.

**Comment by OmarShehata** [comment]
I'm going to close because uploading both files should resolve this, but @1392109 if you're still having issues please feel free to follow up.
