### ISSUE TITLE
vanishing 3d tiles on zooming out

### ISSUE THREAD

**Issue by hardreddata** [AnalyticalGraphicsInc/cesium-ion-community#291]
Hi,

I noted https://github.com/CesiumGS/cesium/pull/8600 with interest in the latest release.

Is the story below an example of this problem? When I zoom out slightly the red cube disappears, I think also dependent on window size

https://cesium.com/ion/stories/viewer/?id=24df180f-8dbf-4297-b4eb-af881394ce82

![image](https://user-images.githubusercontent.com/42530666/75719520-0197f680-5d29-11ea-9ccd-23fe810cf8ee.png)

The cube is https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/sourceModels/Box/Box.dae

I tried uploading the embedded .gltf example from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/1.0/Box/glTF-Embedded/Box.gltf as 3d tiles but got a tiling error. 

Any advice is appreciated.

**Comment by lilleyse** [comment]
It kinda looks like the tile's geometric error is too low. We'd have to fix this in the tilers. Thanks for opening the issue @RussellGrew.

**Comment by OmarShehata** [comment]
@RussellGrew have you experienced this issue with any other models?

**Comment by hardreddata** [comment]
Hi Gents,

Just going through my handful of assets 70921 will vanish completely, but 70924 (far less complex a model) will not. Both of these were shamelessly lifted from Sketchfab. 

Thanks for the help.

**Comment by OmarShehata** [comment]
@RussellGrew are you talking about these planes, that are not visible here:

![image](https://user-images.githubusercontent.com/1711126/75919522-b74b6e00-5e2b-11ea-8af5-8392d7ad9fe4.png)

But are visible here?

![image](https://user-images.githubusercontent.com/1711126/75919535-be727c00-5e2b-11ea-9f19-c8e8ba0f8baf.png)

If so, this is unrelated to the vanishing cube issue. The problem there is that the geometry needs to be double sided. You should be able to define this in the material in your model.

**Comment by OmarShehata** [comment]
> Just going through my handful of assets 70921 will vanish completely, but 70924 (far less complex a model) will not.

This was answered over support email, but to close the loop here, the issue with that asset was that material was not set to double sided, so pieces disappeared when looking it from the other direction. 

This is a different issue from the geometric error being too low for the cube above.

**Comment by hardreddata** [comment]
Hi @OmarShehata thanks for ensuring this issue is looked at. I removed reference to our CAD discussion from this post.

The two assets you refer to are in this story - the second one vanishes.

https://cesium.com/ion/stories/viewer/?id=69580393-2fdc-4465-80da-78e928bb0f6c 

This vanishing issue isn't impacting any of our work. It is more academic.

**Comment by OmarShehata** [comment]
Thanks Russell! This shows off the issue well, and this definitely seems like a geometric error bug (I love the choice of models here by the way).

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
