### ISSUE TITLE
stories cannot be unshared

### ISSUE THREAD

**Issue by hardreddata** [AnalyticalGraphicsInc/cesium-ion-community#292]
Hi,

I created and shared this story a while ago as a first test

https://cesium.com/ion/stories/viewer/?id=e288eded-abf1-4b62-9846-e7ff97865940

Our account now says "sharing is off" for this story as I toggled the switch to off.

I stopped sharing it a day or two ago but the share link still works. 

This isn't causing a problem. I just feel like the link should stop working when the story is no longer shared.

This used the WebODM Cesium plugin and example data set https://community.opendronemap.org/t/banana-dataset/2516 which is pretty cool.

Cheers.

**Comment by OmarShehata** [comment]
Thanks for the kind words @RussellGrew ! I actually cannot access this story. The reason you can see it is because you're logged in to your account. So you should be able to confirm this by logging out and trying it (or trying it in an incognito mode).

**Comment by hardreddata** [comment]
Thanks for the explanation. I can reproduce it.
