### ISSUE TITLE
Create a wall with inertial reference frame

### ISSUE THREAD

**Issue by nateblain** [AnalyticalGraphicsInc/cesium-ion-community#293]
Hi,

Is there a way to create either a wall entity with an inertial reference frame or create a plane entity with a circular boundary? Essentially what I need to do is create a circular plane that cuts through the center of a globe at a specified angle and which use an inertial reference frame when time passes. I am able to do everything I need with a wall by giving it the appearance of passing through a globe, but I cannot get an inertial motion reference frame working with it. I can get everything I need working with a plane as well, but in this case I need to have the plane display as a circle. I would be happy if I could get either the wall or plane working how I want it or if there is some alternative option.

Thanks!

**Comment by OmarShehata** [comment]
Hey @n-9891-b , would you be able to share a [Sandcastle example](https://sandcastle.cesium.com/index.html?) of your current attempt with the wall cutting through the globe?

**Comment by nateblain** [comment]
Correction to my question above: 
Regarding the plane rendering, although it operates properly by staying in place during inertial motion when the globe is turning, I need the orientation of the plane to stay the same in relation to the surface of the globe when in ecef mode.

Here are the requested example of the wall and plane. The wall is not actually cutting the globe but needs to have the appearance of doing so.
 
Wall: 
https://sandcastle.cesium.com/#c=hVRRTyIxEP4rPV7YTbDoqQ8nYM4g5kzUM0juHsSHujurjW2HTLsgmvvv13YXWNTohEA7nfnmm28mzAWxuYQFEBswAws2BCtLzf9EX9LO4nWIxglpgNppb2qmpihN5iQaJjMqEpuBgQ5zUkPKXsM78yYLVr1wjTmwb4PBCvsmeC+9k98MR1ej/dO0ynitfoIRuJJMr3L8W0HOPdlQcYJn8hlytkackDC2QNJ2A/GR8Qz1rHRwvgG5FI7kcxLJ95rca+gcCt94njTqpu/5BmZYFBZcuK15DQU5fxJm/3NegZlCA7VgmdBAgs/QyqBy2tsu5FbdbgpVXRx8WaUg1GN0IsBG0VQ8bnXXqLZFRyE+nbi11MmaRqduPd3MK46s2itegcwIxmByfxd5PpqDcRfSOv9CsXilfYbGOub73l7GYXAL465rQa4JZ0BumbyTOTZ4Cg8EYJPdDguftLPCGUMBBCaDM/It8fOr0XhyfnIRagddCfK/Qilfu2buSfp6YAPlpJ628ZlHrD3267cIwcKxR5APj67dqQLi1NAchUPtioFHzX1ZjdZ696dNnBCJ5a9YwCa3O3t7h9z3dHAQvr/vRvPHr+b+pe382P0A9y5tIGtppC51zcXzvg3i3jUjhAOSQjV6QoXEx6PTzWJUg64FfkHUE0zeyB1CWp1W37qlguMq9afUMyTHSlIJ510HeuZXF2z3vsyewPHMxrR+d5XUz+WcyXwwbb35C5u2WKaEtf6lKJW6kS8wbR33uz5+K02hyKV5+D0HUmIZQh73ji8qJ+e83/XX91kOUd0LaiD+Bw
Plane: 
https://sandcastle.cesium.com/#c=hVRta9swEP4rWr7EhqB0a/elScqyNIWwtCtpNhgEhmqfW1FZMic5fWP/fSfLjp2mbCIQ6aR7Xu4ObwWyrYRHQDZhGh7ZDKwsc/6zikX9pDrOjHZCasB+PNrojc5KnThpNJMJZpFNQMOAOZlDzF79PaMlMxZueG5SYB8mkwb7xkcvKchvZvOr+fF5HDJew59fCK5EPQqBPw3klsR6xrW5kE+Qsh3iGoW2mcHcthDvLZ6YvCgdLFqQS+FQPkWV+FFXew2dQkbG06jDGx/q9cpMlllw/rTTNRPoaCf08b91eWXKaKgLlogcUPDCWOmrHI/2iVzjtiUKLk7+y5KhyVfGCQ9bFU1V2z13HbY9OcqYh6nblTrayRjU1uO2X1XLwlzxAFIgrECndBZpOt+CdktpHd1gRR5q792R6/1RpOGzTmh3XZfjGk0B6J6jgyJX9s7hDgFsdDRg/hcPGpwVZICgE7hAMsQXV/PVejFdembPi5BeK6GByGvhpJEIwXrFUd1sTanslPVXNH5F9fxRunt2q0TywEzpFA1LfxDeNv079bsmVuWcdmenCXUsV0Le8ffjarH+/YtccfLVIqQ0vNoSk92H2WV+ik6OwuJUk3bfBcmFA5RCEcSu8MogX83Pufc4VcW9iI74525S7ZhyHJZweFFBvEX8upzOvrWjUrc+1PzFmHxtojcd8E96g97YumcFZyH1i8wLg46VqCLOhw5yKiTZHd6WyQM4ntgqbTxsksap3DKZTja9Nx+1TY8lSlhLN1mp1I18gU3vbDyk93tpyohU6rvvW0Alnv2T+49nyxDknI+HdDzMcsaoW4EdxL8

Desired behavior for the Wall is that it should stay put during inertial motion. I set the position but it doesn't work. However when I set the position with the plane it works fine for eci but I need it to stay fixed in relation to the surface of the globe in ecef mode.

**Comment by OmarShehata** [comment]
@n-9891-b I haven't figured out an answer, but have you searched for any relevant info on the Cesium community forum (https://community.cesium.com/) ?

I'm going to close this here since it isn't a Cesium ion specific question but feel free to open a new topic on the forum where others in the community might have some ideas.
