### ISSUE TITLE
Please add New South Wales (AU) 1m+5m DEM to Cesium World Terrain or Asset Depot

### ISSUE THREAD

**Issue by alfski** [AnalyticalGraphicsInc/cesium-ion-community#294]
Hi, the NSW Digital Twin https://nsw.digitaltwin.terria.io/ has a Cesium asset which includes the public 1m+5m DEM for the state.

Is there anyway we could get this DEM included in the Cesium World Terrain, or made available as an asset that other users can load into Cesium? Perhaps adding it to the Cesium Ion Asset Depot.

The new topography is a massive improvement over the existing DEM.

For example, comparing the Three Sisters rock formation in the Blue Mountains with CWT (left) vs NSW 1m DEM (right).

![image](https://user-images.githubusercontent.com/979009/76266542-ea727f00-62bb-11ea-8fb0-5bb47c7e281f.png)

DEM is likely from this source https://elevation.fsdf.org.au/

Cheers, Andrew

**Comment by hardreddata** [comment]
See also https://github.com/CesiumGS/cesium-ion-community/issues/256 where @kring selflessly offers up the terrain

**Comment by OmarShehata** [comment]
That looks awesome - I think that'd definitely be great to have as part of Cesium World Terrain. I'll update this issue once I have a timeline on that.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this request internally now. For any follow-up questions, please use the community forum!
