### ISSUE TITLE
Pick tileset in another tileset is not possible 

### ISSUE THREAD

**Issue by muratkendir** [AnalyticalGraphicsInc/cesium-ion-community#297]
Hi everyone,
In my scenario, i use two different tilesets. Second tileset is nested in first one and first one is transparent. (Think like buildings and condominium parts in building)

![2020-03-16 15_52_23-Window](https://user-images.githubusercontent.com/3502531/76760177-3a5eb380-679e-11ea-8c2d-040b1ba068c7.png)

I need to pick feature using click handler from nested tileset, not from first tileset.

I tried to use allowPicking function, but it seems like it is working correctly for primitives, not for tilesets streamed from ion. ([Sandcastle Link](https://sandcastle.cesium.com/#c=xZVrb+I6EIb/itsvpFJlLttWu1tanS6UbligF1JaKqQj4wzg4thZ2wGSo/7341zoAm1X2vPl8CWKM/PO+8zYplxGV4oIgxqgWRS0+4hQClojI1EsI4WYFIhoDUaPRB6DXSmwDxMScXORBXtyDgKdoRLE7dn4irJr1nbvE7faY652xd0xbbgn7jx8HDTaX7AN+ulfzW2QG3eTy1q31mLDuDrrPQzmHe8u6D7cm2HQ4r24kjwFw6OuNzx6as4/DQOXdRrt8MmK9ZLbuBsvGa31FvRqkLjP4dgNWglNCwb+s8srOnuvDSo0dk8ekmnc8+5XnWb2rHWarrb5q8f+kpGHVsV9lqueN610k/tlr9k9mtziEIBAT1x3u9xP2IyeqKj586Y1+HwLnfaCr1TnyzC4/rH89uiWTkdiJBZEoQWDJSjbCgHLoqV4kK05JZq9NqQwhAlQpUP0z0gg+zOglF26UXLBfJv9dTM7f3jbIU6Rmf4ixb+iX5O5A23HRgFPlAwu0sG5vlM9yONf7PPlwLrNfWJNQQCecjkGO9HQzDzQ5mJqK2lTlLQsRkWQEZbL/YBwjqjkUoGPxnIFOgc3jIOtVana+C3xULGAGbYAjYnvO7mPN3yfml4u8Kdkn2vHxycbdAeZ0Vc32NqVyxtG50xMt1E6RE3Bbn6wW/ebXG1j1P4HjOobjF8gtV2QCeE6JylsJlIGnnReEwoxLM0M1JJpcCaRoCY9zo6drFQHaMMjlUJLDpjLafH1dG2maFdRBlYGhO8UOPniFrsrdAjUSNVlK1ZwpJ2dEeHz3aPRp2n7+yGhcLkAYb7nQc5W6ymxAjpVKjRw2jMRRvb2SXlewRwF2t5Jr2Bp2QkQEyl4M07byCIch1KzNH2NvO6Fz5RTpGO7ZrkNLtq7DmUT9FHIzsDOipFtdX2386W9VmG3EEFMIyENyrRSHXsrp9b3SmsH78l85MhuxN+llUYj8UZXgZUSG4svb8hRelsQQUFO3jsNBVIG/v6GK62prUBxfjJK8Pf2tkn/A2Wxje29d/jRrvPiEHDnsuX93ei4jR8Hp/uH+3VtYg7nefZfLAilMulJdjAuGwhCTgzo8jiyLg2mOtue9fI6qe6zBWL+2Wh/59If7SPK7d+p/TKJOO+zBEb75/Wyjd9K45L4dt7XC1CcxDYkN1KfVc87+SeMcb1sX9Oyu9lGSj4makP5Xw))

I also used drillPick function to get whole tilesets and then filtered picked features by tilesets.
It is working, but i don't want to use this method, because of performance issues. ([Sandcastle link](https://sandcastle.cesium.com/index.html#c=vVZtU+I6FP4rWb9QRm5oEXYWAefuILpFERUU3WXHCWmAYJp0kxQG7vjfb/oCttX79fKhbznnPE+e8xKqVXApEdegSxQN/f4IIIyJUkALsBWhBFRwgJQiWk15YgNdwaFH5ihk+ntsPBavhIMOKJFtfzm7xHRI++7DznVuqKtcft/AXfer+xo8PXb7TWiM/niXr8bIPRmsnu3hZOAMRg4dTC786/HdyfOkp58n/dVwZNee/bvNcNz3B5PH5fC8R6+7/eCnCXazu9sOthuKazdrfPm4c1fBzPUvdjgC9L2Vy2xzZ0vP2A7GD/ZwPHCG58/24MmGs8mTN77RP19c7KvFn/DqSvUeZtiu36NB82niPdVFr/bQ+IEnotSa8ilfIwnWlGyINHvkZJNqBR/jb1YJx69dwTWinMhSuZX4YOQTifI+3fiblYSDChNOyjEISCFg4gXnbDsW1j/RQvLziNKUIx0l5DQfUmrzhPgJnEvhn5OFJERZtSZ06o1K3YGO06w0bLtc2QcTkhJDNgp1CjIQ0W9JkEf5Apza0K7klwKq8dJg/5UCD5Bewlv3ZfjYu3+5GD7cF+ylYMyYm0Dv39+Sx7fyQVlNGTHl5RidsqrAQFKfaromCiLPsxK/7Lbj28n5OPHPShVKdgrei/WeKFPJmMTyfI9q2fWsr81mvV7es5nyiNCeClR6y0ghcRm4UbScBcSCCXkKSnIxQ1at0aiA94sNa41yKbftAw5iTGxuKX6NFO+AOWKKFIWp/c/CfLOdxreCMAfKtSJlLcOUcUJxJ4Rv6na/wzQOFHpJ5IYqYs1DjuMatoiUQpZBTkauBCOQiUW62srplugSq1AQxSzTObC+pAoZerdC0QhnFAaBMA3ixUhZhNJ4SRWYSbFRprM9QRTgQgOVOIBsEBj39NuewRJxjxWnwQibtuOjAGHSW5v2+pEY5VrdNLcJoKJgaQwYic6D0EzSCCgjjyTKDNiYdYIaESLecLYiWKtiUXiSMhalJfWDQUq9nEqT84aM8IVegrMOcA4ZmAsJrAhoZYLbLXNrg8+8zMrxcS5v1WpXeATMiCkNIIkvTG2mrmBOkA4NJxDVGEBSoi3YLKkZJEiSWPDIjS/iE+fQGO+xP3D/tfoNUzvwpdM5tEm5OMny3FXAKCbWqmJ23MrMI5BWWDKDzRQ2AqScjQx5ZPt3a28W0dqbUa404piI+WcteJFY5ejF6ZQiIFJvb8y8j9KZRoMLom+zS1b5ALp3TbPXycfYp+fd9pBRmmSUmozuc3h8TD8oVqRVRPhFf7fyHtl+ynkeg5KZh+b2ybZyluVcNjLJSC6V/2qv8TYg8Lp3MX7pXrvdq3ILHFWO2vHgPkui/E39uJHN0LMgrGriBwyZk7I6C01SNcQqbsR2de/U9ugaUK8zPSqc6NMjgJn5E2RW5iFjI7oj06OzdtXY59yYiM/O4ZpIhraRydI5u04+QgjbVfP60UsLwWZIZiL+Cw))

So, i need a function like allowPicking to restrict a tileset for mouse handlers, but keep visible at the same time. Any suggestions?

**Comment by OmarShehata** [comment]
> It is working, but i don't want to use this method, because of performance issues.

I think this is the right way to do this. If CesiumJS implements a method like you suggest I think this is what it will do under the hood. 

I'm closing this since I believe it's possible to do what you're describing, but feel free to follow up here or on the forum (https://community.cesium.com/) if you're still having issues.
