### ISSUE TITLE
Model appears rotated

### ISSUE THREAD

**Issue by hataken1566** [AnalyticalGraphicsInc/cesium-ion-community#298]
I placed a square model, but the model is rotating.
I created a square model so that the square corners would be in the positions of the red circles, but that didn't work.
Changing the position of the model changes the size of the rotation angle.
Center point exactly fits.
The length of one side of the rectangle is 1000m.

Why does the model rotate? Please give us somebody feedback.

【Asset ID】84671

【share URL】
https://sandcastle.cesium.com/#c=7VddUyo5EP0rKV7AKirMMJ+waK2Cq8MVWBT1YvEyzgSJzCRskpGLW/737cwAAnXdug8+3Afjg5PO6ZPuPklXqNXQhQiZQm0iaZZ2b1AYRURKpDha8UwgyhkKpSRKTliBwQFnOCbTMEvUaQ4e8Tlh6BiVyao7e7yI6IB2g9vXwOzTQAbs2onagRvMF9/v2t0GBtA/8cUcQMGy9zqbDzpnaY+az+PXoXE1Gjr99FyNR3d00DbnD/e3dr/z1/yhc2v17sf0qt1dPABZb3S+HHR6QN5/frTOkmgVuPeweWQFGsPGq26ssePvQzp4Pjf7o6dlfzS2e51ZA49/eH1pP8fD1XDufJuHo56TXTrnlzdnw8t7/+bqtX559tI7ffhWt8t/TNiEvYQCvVCyJAKSZGS5Lha+y22VcpRP25ypkDIiyke5V8SZVGjBJVW6iMcbr3YoFHyFzMJTwdPrMIZvWaljy7M906obDd/1DMevIgO79YbpW7Zre7brezbYTMPQ9AX5jIAzewJuY2tbUBXN9iyCJ8meYbY4SOSy4Plbu14DurImrhZs1ZzifVsuKIFc99MawTGSUy5SiWcHdMMsVEQwgFc25ajqII621V1AIagk72xwxq6JhAMYkbxKp/oIBnHFtxueeTRhCAZWM8Iq04xFeSQVsXY4Qv8WAD00OwRL1QrICxFxPqdE4jCOKztYPTYBNrdf1X3ATvLN3ckBLOUxSZrogF2PTNAm2sS6v/z2Pn3TxdkmUcQdhSkRIZ4mqxE/jDsmUlFWaNL84Kh1yJMgRFZMy8WGaxq2bXsNy/aqSBvshuN4htuwTduEc+YYBjaOfhLQ26b8HOovliDbjgZECC72BNBHhicEJ/xpvbrl2covSNymIkpIG6qZ37L/UepdoU/IUue4Vo5BdaF05QvwZijK40GhvmT0aabQkqoZ4plK4IqX1y4kSehCaq+dhCVJaY8yLk5/UAlLBjarB6vh8werxV5NZOrAduypvkA0THak5QkX+Pq8s4NaRwcgJTKCarVN7GkGt/aRwOYKwRXdAqHJx1QuknC1lmTCfqaK+YmCOI4NLa1u+H59LYhjOJbpQ+vzTN3yfk89jN9Jj/on6+GbUH3fLfRwbMN1LRusWqEvPX5BD+szG5brNDzPg65lvusB/QoeAp7/pccv6WF/sh4GlN73Gtt+ZXuOBf8s70uPj/TQf6VqqSXVKiEnxeqfNF1woeABlFQwrimSgicUvvaYRXOicCSldm7VNk6tmL4gGh9PSgcv7EkJRQn8KoGVaZYkN/SVTEonrRrg99wSnj9EBy9E6BhL60BaM/PkqljCGLdqMNXbHnorzpPHUOww/wc

**Comment by OmarShehata** [comment]
Responded over email but adding my response here too: You may need to apply an orientation transform to correctly orient your model depending on its location on the globe. You can do this in 2 ways:

You can use the Cesium ion geolocator tool to rotate it: https://cesium.com/docs/tutorials/integrating-with-3ds-max/#geolocating-your-data

Or you can apply a rotation with code as shown here, relative to the direction of North at that location: https://sandcastle.cesium.com/index.html?src=3D%20Models.html

I'm closing but feel free to follow up if you're still having issues.
