### ISSUE TITLE
Photogrammetry model fails to tile

### ISSUE THREAD

**Issue by lydonchandra** [AnalyticalGraphicsInc/cesium-ion-community#300]
Hi, 

Had an issue with tiling.

Message: 
"We're having trouble with your data. To help fix it, please open an issue in our Github repository.
If you don't have a GitHub account, email support@cesium.com with the asset ID: 87597. "

Could you please have a look?
Thanks

**Comment by OmarShehata** [comment]
Thanks for reporting this @lydonchandra. This is a bug on our end. I'll update this issue once there is a fix or a suggested workaround.

**Comment by jo-chemla** [comment]
Hi, subscribing to the issue  since I had the same problems, tiling a 100M textured mesh with 3x16k jpg textures in either obj, fbx or glb with or without draco compression. Just following for knowing the fix or workaround, Thanks !

**Comment by lydonchandra** [comment]
workaround is to have multiple smaller meshes, in our case 10+ obj files (instead of 1 massive obj file). For us, this can be done easily when exporting.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
