### ISSUE TITLE
Cesium visualization issue with asset id: 88395

### ISSUE THREAD

**Issue by ohadmanor** [AnalyticalGraphicsInc/cesium-ion-community#301]
Hi,

When I try to load 3D tiles with validation error (I can load it on https://gltf-viewer.donmccurdy.com)

![image](https://user-images.githubusercontent.com/9347444/78468560-ccb10200-7721-11ea-99e8-9a085b5b9400.png)

**Comment by OmarShehata** [comment]
The issue was that the 3D Tileset contained invalid materials, discussed on the forum here: https://community.cesium.com/t/3d-tiles-building-shadow-become-lines/9248/7?u=omar
