### ISSUE TITLE
Photogrammetry with large texture fails to tile

### ISSUE THREAD

**Issue by ozcanork** [AnalyticalGraphicsInc/cesium-ion-community#302]
I previously uploaded 3D tiles for the same region with asset id (16085), it worked fine. But, when I uploaded this high quality version of the same project (88060), I got this message on the "Adjust tileset location" screen as follows: 
- We're having trouble with your data. To help fix it, please open an issue in our Github repository.

**Comment by OmarShehata** [comment]
This is a bug with having source images that are too large. What did you use to export this? Do you have an option of exporting the texture into several image files?

Also make sure to select the option `3D Capture` for photogrammetry.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
