### ISSUE TITLE
Tiling issue with asset id: 88236

### ISSUE THREAD

**Issue by enmarkalo** [AnalyticalGraphicsInc/cesium-ion-community#303]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
The issue here is that the CityGML file provided contains features that Cesium ion doesn't currently support.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you have any follow up questions, please post on the community forum!
