### ISSUE TITLE
I was looking for a way to convert KMZ [with model] files to 3d tiles without using cesium ion and FME.

### ISSUE THREAD

**Issue by vishmitha19** [AnalyticalGraphicsInc/cesium-ion-community#306]

**Comment by mramato** [comment]
@vishmitha19 our 3D Tiling pipeline is also available for purchase as an offline command line tool so it can be integrated into offline or non-cloud-based workflows. You can read more about it at https://cesium.com/3d-tiling-pipeline/  or [Contact sales](https://cesium.com/contact/sales/) if you are interested in evaluating it.

**Comment by OmarShehata** [comment]
In addition to what Matt said above, @vishmitha19 if there's any specific features you'd like to see Cesium ion support we'd be happy to hear it! Feel free to follow up here or on the Cesium community forum (https://community.cesium.com/).
