### ISSUE TITLE
Support additional LAS point cloud metadata

### ISSUE THREAD

**Issue by KeyboardSounds** [AnalyticalGraphicsInc/cesium-ion-community#308]
Is there a way to attach extra metadata (not just Intensity and Classification) to individual points in a .las point cloud?

Rather than hard-coding the colours in the .las file, I'd love to be able to use the 3d tiles styling language to assign colours according to the attributes of each point- eg. temperature, or signal strength. LAS 1.4 supports extra dimensions, and it would be great if the tiler could read those and add them to the batch table.

**Comment by OmarShehata** [comment]
This isn't currently possible but it is on our roadmap!

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
