### ISSUE TITLE
Tiling issue with asset id: 92445

### ISSUE THREAD

**Issue by zhangquangong** [AnalyticalGraphicsInc/cesium-ion-community#311]
We've encountered a problem with your data:

Error: Invalid File
File: tileset.json

If you'd like more help, open an issue in our Github repository or email support@cesium.com with the asset ID: 92445.

**Comment by OmarShehata** [comment]
It looks like you're uploading a GeoJSON file. Make sure to select the GeoJSON option when uploading and it should work: 

![image](https://user-images.githubusercontent.com/1711126/79874272-24a06780-83b6-11ea-92e7-f9dd396493db.png)

**Comment by zhangquangong** [comment]
Thank you. I seem to understand. In fact, I expect a large number of vector data to be displayed. I understand that the way to convert to 3dfiles should be a good choice in terms of performance and data volume, and realize the following way of calling.


viewer.scene.primitives.add(new Cesium.Cesium3DTileset({ url:Cesium.IonResource.fromAssetId(92435) }));





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Omar Shehata"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上9:55
收件人:&nbsp;"CesiumGS/cesium-ion-community"<cesium-ion-community@noreply.github.com&gt;;
抄送:&nbsp;"权功"<914668983@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CesiumGS/cesium-ion-community] Tiling issue with asset id: 92445 (#311)





 
It looks like you're uploading a GeoJSON file. Make sure to select the GeoJSON option when uploading and it should work:

**Comment by OmarShehata** [comment]
We don't currently support tiling vector data into 3D Tiles, but is on your roadmap, see: https://github.com/CesiumGS/cesium-ion-community/issues/130.

**Comment by zhangquangong** [comment]
Thank you for your quick answer. Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Omar Shehata"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上10:21
收件人:&nbsp;"CesiumGS/cesium-ion-community"<cesium-ion-community@noreply.github.com&gt;;
抄送:&nbsp;"权功"<914668983@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CesiumGS/cesium-ion-community] Tiling issue with asset id: 92445 (#311)





 
We don't currently support tiling vector data into 3D Tiles, but is on your roadmap, see: #130.
