### ISSUE TITLE
Tiling issue with asset id: 94388

### ISSUE THREAD

**Issue by yowich** [AnalyticalGraphicsInc/cesium-ion-community#312]
<Please provide a short summary of your data.>
Cesium Ion reported me this error:  We're having trouble with your data. To help fix it, please open an issue in our Github repository. If you don't have a GitHub account, email support@cesium.com with the asset ID: 94388. It has been stopped at 9.00 % for tiling over a day. 

What do I need to do?

**Comment by OmarShehata** [comment]
@yowich this looks like it's a photogrammetry model.

Make sure to select "3D Capture" when uploading. Let me know if that works.

**Comment by yowich** [comment]
That worked! Thanks!

**Comment by OmarShehata** [comment]
Great - thanks for confirming!
