### ISSUE TITLE
Improve zoom button sensitivity in Stories

### ISSUE THREAD

**Issue by hardreddata** [AnalyticalGraphicsInc/cesium-ion-community#313]
Consider the example story in https://cesium.com/blog/2020/01/28/cesium-stories/

With my mouse wheel I can effectively zoom toward and up against the terrain but no further. This is nice.

If I hit the '+' navigation button above the 'home' icon I easily overshoot my target. It looks like the below following one press after a fresh start

![image](https://user-images.githubusercontent.com/42530666/80339337-c4bc2c00-88a1-11ea-9977-2288af97cebd.png)

I am not sure if this constitutes an issue. 

I was using the laptop without a mouse during social distancing...

**Comment by hardreddata** [comment]
For completeness, I can press '-' and normal service resumes

![image](https://user-images.githubusercontent.com/42530666/80339480-1369c600-88a2-11ea-9c53-287dbffdcc1d.png)

**Comment by mramato** [comment]
Thanks for opening this issue, @RussellGrew. The on screen navigation buttons, especially `+` and `-` can certainly use some improvements. We'll use this issue to track updates to that behavior. I don't have a specific ETA, but hopefully we can make it work more like middle-mouse scrolling so that controls have a consistent "feel"

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/improve-zoom-button-sensitivity-in-cesium-stories/10526
