### ISSUE TITLE
Tiling issue with asset id: 94910

### ISSUE THREAD

**Issue by mholthausen** [AnalyticalGraphicsInc/cesium-ion-community#314]
I've uploaded the CityGML source file (https://www.offenedaten-koeln.de/dataset/3d-stadtmodell-koeln-0) to the tiling pipeline and it stopped with the following error:
```
We've encountered a problem with your data:

Error: Invalid spatial reference system
File: ETRS89/ETRS89/ETRS89/tile_0_10/LoD2.gml
Spatial Reference System: urn:ogc:def:crs,crs:EPSG::25862,crs:EPSG::5783

If you'd like more help, open an issue in our Github repository or email support@cesium.com with the asset ID: 94910.
```
Is this CRS not transformed into the Cesium CRS?

**Comment by OmarShehata** [comment]
You'll need to replace the CRS with just `EPSG:5783`. 

Also heads up that w're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

For any follow up questions/issues please use the community forum!
