### ISSUE TITLE
Asset id 95630 stuck on tiling - very large gltf

### ISSUE THREAD

**Issue by KeyboardSounds** [AnalyticalGraphicsInc/cesium-ion-community#315]
Asset id 95630 appears to be failing to tile, although no error message has popped up yet. It's an absurdly large gltf, (~1.2 GB) which might have something to do with it.

**Comment by KeyboardSounds** [comment]
I tried using the 3D Capture setting instead of the 3D model one for asset ID 95844 but I got an error message.

**Comment by OmarShehata** [comment]
Thanks for reporting this @KeyboardSounds . This does look like a bug on our end.

We may have a potential fix this. Since your ion account has dedicated email support, can you reach out to `support@cesium.com` ? We can work with you to test this fix or otherwise suggest workarounds for your data.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
