### ISSUE TITLE
exception case for invalid dataset

### ISSUE THREAD

**Issue by cr8tpro** [AnalyticalGraphicsInc/cesium-ion-community#316]
Hello 
I am a huge fan of the Cesium and ion pipeline but there needs to be added one case for an exception.
I converted GeoTIFF files to gltf and uploaded to cesium ion.
I think it must be stuck as it's not a valid type of gltf.
At least there should be an alert like "it's not a valid type"
If a dataset is small then we won't feel any problem but if the dataset is huge and it needs to wait much time and when I notice it's invalid type then I should investigate again after a long time.

**Comment by OmarShehata** [comment]
@cr8tpro thanks for the kind words! Can you tell me the asset ID ? If you upload an invalid file Cesium ion will give you an error saying so, unless there's a bug here.

Is what you're trying to tile a digital surface model or terrain model? You can upload the GeoTIFF directly to ion if it's terrain to visualize it in 3D.

**Comment by OmarShehata** [comment]
I'm going to close this but if you're still having issues @cr8tpro feel free to add your asset ID here or follow up on the Cesium community forum (http://community.cesium.com/).
