### ISSUE TITLE
Invalid glTF error is not caught

### ISSUE THREAD

**Issue by fadelkoto** [AnalyticalGraphicsInc/cesium-ion-community#319]
Hello, I tried to visualize my data using Cesium Ion. 

My data is lod 3 mesh data from pix4d that I already converted to glb format. 

I converted it using converter developed by @fanvanzh.

It was succesfully uploaded to Cesium Ion, but it resulted error when I try to open the visualization as shown in figure below:

![image](https://user-images.githubusercontent.com/36468837/83148323-1c47f480-a0f9-11ea-8033-5140b670bdf3.png)

**Comment by fadelkoto** [comment]
Actually I want to visualize my georeferenced 3D mesh model in Cesium. 

Any idea how to solve this problem?

Thank you.

**Comment by OmarShehata** [comment]
Hey @fadelkoto  - this is seems to be an invalid glTF. 

What is the source format you're exporting from Pix4D? If it's OBJ/FBX/DAE you can upload that directly to Cesium ion.

**Comment by fadelkoto** [comment]
Hey Omar,

The pix4d file format is OSGB. I tried to upload the obj file format, it succeed. However the obj and other formats from pix4d (except for osbg and slpk format) is not georeferenced. Pix4d also stated this in their documentation:

https://support.pix4d.com/hc/en-us/articles/204606535-How-to-visualize-the-3D-textured-mesh-with-georeference

So I want to have my 3d model located in Cesium exactly in its position based on its coordinates.
Hope you can help me.

Thank you.

**Comment by OmarShehata** [comment]
Cesium ion doesn't currently support geoferenced photogrammetry meshes, see: https://github.com/CesiumGS/cesium-ion-community/issues/39

The Pix4D doc suggests this approach which does work with Cesium ion:

> Some external viewers permit you to add the offset of this file and place the 3D Textured Mesh at its correct position. If this is used, the 3D Textured Mesh will have the same precision as the mesh in the rayCloud of Pix4Dmapper. 

You can do this either by uploading your model, and then geolocating it with the visual editor, but that will currently cause the model origin to change from the original model (see https://github.com/CesiumGS/cesium-ion-community/issues/282).

So what you'd need to do to get it in exactly the right place is use the ion REST API. This allows you to pass in a longitude, latitude and height where the model origin should be on the globe.

**Comment by fadelkoto** [comment]
Hey Omar, 

I am actually new to this API things. I followed the tutorial and succeeded to upload the Reichstag.zip file to the Cesium Ion.

But for my case, as you stated before, I need to pass additional information regarding the location. 
Where and how can I add the parameter defining the location of my model in the part of the .js script? Is it in the body part? & how?

![image](https://user-images.githubusercontent.com/36468837/84034815-1ffe3580-a99b-11ea-8646-11bb3cebba1d.png)


Thank you

**Comment by fadelkoto** [comment]
I found the soultion I think. I will try.

![image](https://user-images.githubusercontent.com/36468837/84035156-a286f500-a99b-11ea-9168-dadb8684a651.png)

**Comment by OmarShehata** [comment]
@fadelkoto that is correct. Hope that worked for you. If you have any additional questions you can follow up in the Cesium forum here: https://community.cesium.com/

**Comment by OmarShehata** [comment]
Another invalid glTF reported here: https://github.com/CesiumGS/cesium-ion-community/issues/337

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

I think this has been fixed now. For any follow-up questions, please use the community forum!
