### ISSUE TITLE
Tiling issue with asset id: 108230

### ISSUE THREAD

**Issue by TomekBuCS** [AnalyticalGraphicsInc/cesium-ion-community#322]
I have a problem with tiling data uploaded via Cesium Ion. 
First I had problem with uploading all the files, but after packing those into zip file I managed to upload them all. 
The model is a COLLADA (DAE) file from Bentley ContextCapture

**Comment by OmarShehata** [comment]
I think it may be the fact that the models are inside a subfolder that's causing this error. Can you try re-zipping it such that all the models are in the root of the zip and re-uploading to confirm if this is the problem?

**Comment by TomekBuCS** [comment]
I have zip just the files and re-upload them, but there is still an error. The new asset ID: 108505.

**Comment by OmarShehata** [comment]
@TomekBuCS this is actually a different error now. I'm not sure this job is failing but we're going to investigate and update this issue.

**Comment by OmarShehata** [comment]
@TomekBuCS we've just deployed a fix for this issue. I've gone ahead and restarted this job, and it's tiled successfully now. Let me know how it looks!

**Comment by TomekBuCS** [comment]
Thank You @OmarShehata It looks fine, I will have a better look to it tomorrow, but thank you for all the help
