### ISSUE TITLE
Tiling issue with asset id: 108963

### ISSUE THREAD

**Issue by lanvada** [AnalyticalGraphicsInc/cesium-ion-community#323]
"We're having trouble with your data"?
Is there an error log？

**Comment by OmarShehata** [comment]
Sorry for the slow response here @lanvada . The issue is that you selected "tileset.json" as the entry point to your 3D Tileset, but this file does not exist. You must enter the filename of the entry JSON when uploading your 3D Tiles to Cesium ion.
