### ISSUE TITLE
Tiling issue with asset id: 109502

### ISSUE THREAD

**Issue by Cezary885** [AnalyticalGraphicsInc/cesium-ion-community#324]
I am trying to upload a FBX model with the texture in it from Pix4D and a 3D line in SHP format. Something went wrong, can you help?

**Comment by OmarShehata** [comment]
This was the same bug as https://github.com/CesiumGS/cesium-ion-community/issues/322. We've fixed the issue and pushed a fix. I've gone ahead and restarted this job and it's now been successfully tiled. Let me know how it looks!
