### ISSUE TITLE
About ellipse of outlineWidth is not work

### ISSUE THREAD

**Issue by Mirror-Yu** [AnalyticalGraphicsInc/cesium-ion-community#325]
Dear Cesium Team
I found that the outlineWidth property of the ellipse doesn't work。I wrote 10, but it's still only 1。
![image](https://user-images.githubusercontent.com/52779170/84098385-ae28f900-aa39-11ea-9119-26b147cf458d.png)
Any idea how to solve this problem?

Thank you.

**Comment by OmarShehata** [comment]
Hey @Mirror-Yu 

This is a limitation when running on Windows. You can read more about this here: https://github.com/CesiumGS/cesium/issues/8577.

I encourage you to search the Cesium forum (https://community.cesium.com/) for your questions or open a new topic there for any questions you have while creating your app.
