### ISSUE TITLE
Cesium viewer not filling containing div element

### ISSUE THREAD

**Issue by superahoy** [AnalyticalGraphicsInc/cesium-ion-community#326]
I have create a React App with a  cesium viewer instance in a nested div. Essentially

div id="root" style="background-color:blueviolet;"
   div class="cesium-viewer"
   div id="components"
div // end-root

The components div is a hidden div and has a width/height/border of 0, its just a place holder for some cesium overlays.

I noticed when clicking on my React components that the globe no longer mapped cleanly to the browser window. A thin line appears on the bottom of the cesium window, and a vertical scrollbar appeared. When I click on the globe I get a stutter and the viewer resizes to fill the div again and the line disappeared. I forced the root div background to blue-violet and I can see that the line I am seeing is the root div element. I have attached a screenshot of what I am seeing. 

The other side effect I am getting is if I attempt to sample the globe by converting the mouse input to coordinates is that cesium hard crashes somewhere. The second screenshot is the cesium popup stack trace. If I have selected the globe and there is no root div bleed-through I am able to sample the globe as expected.

![image](https://user-images.githubusercontent.com/66656898/84101091-3a580380-a9db-11ea-9ae6-c20adda16ff8.png)

![image](https://user-images.githubusercontent.com/66656898/84101704-86577800-a9dc-11ea-8032-9d9b82598e40.png)

**Comment by OmarShehata** [comment]
Hey @superahoy  - can you post your issue on the forum (https://community.cesium.com/) ? This repository is for bug reports with Cesium ion. 

Are you able to reproduce the crash in Sandcastle (as the instructions here describe https://community.cesium.com/t/how-to-share-custom-sandcastle-examples/9828?u=omar) ? That'd help us determine if it's a bug in the library or not.
