### ISSUE TITLE
3D Buildings fail to tile

### ISSUE THREAD

**Issue by Ring-r** [AnalyticalGraphicsInc/cesium-ion-community#330]
Hi,
I have uploaded OBJ files as 3D Tiles with next parameters (asset ID 104504):
- there are 316447 OBJ files in one zip archive;
- each file is a single model of building (LOD1);
- total compressed data size 164.85 MB;
- OBJ data contains coordinates are in ECEF SRS.

There was an error in process of 3D Tiles conversion, as I understand.

Could you please provide me with the information what went wrong?
Is it in an unsupported data format?
Are there too many files?
Any other issues with my data I should look into?

**Comment by OmarShehata** [comment]
@Ring-r this is likely a bug triggered by the large number of individual files, but we're still investigating to confirm. 

Can you tell me a bit about how these models were generated? What software did you export them from, or are you using your a custom pipeline? If you are able to generate KML/COLLADA as described in this blog (https://cesium.com/blog/2020/04/09/kml-collada-metadata/) you should be able to tile this on Cesium ion. You would need either one KML file specifying the longitude/latitude/height of each model, or split this information across multiple KML files. The building models would need to be centered such that the origin is at the bottom of the building. This way you can take advantage of clamping the the buildings to terrain if needed. 

There's an example KML/COLLADA in this tutorial here for reference: https://cesium.com/docs/tutorials/getting-started/#loading-your-own-data

**Comment by Ring-r** [comment]
@OmarShehata, these models were generated by [ELiT (EOS LiDAR Tool)](https://eos.com/eos-lidar/). 
As a developer of this tool I am evaluating if we can use cesium.ion as a third-party tool.

I am going to convert data to one KML and use it in cesium.ion.
Thank you for the links, It helps me to get the final result more promptly.

**Comment by OmarShehata** [comment]
Great - let us know if you have any more issues here. The other advantage of using the KML/COLLADA input is you'll be able to clamp the buildings to the underlying terrain during the tiling step (whether that's Cesium World Terrain or your own custom 3D terrain).

**Comment by Ring-r** [comment]
I’ve converted our data to KML/COLLADA and created one KMZ file.
I’ve checked cesium.ion processing with 100 models in such format (Asset ID: 113390). It works correctly.
I’ve run processing for all necessary models (Asset ID: 113439). As a result I have "Retrieving data for processing..." since 6/17/2020.

1. It's been a while since I submitted data for processing and it is still processing. Is there some kind of internal queue for requests?
2. Should I use fewer files? Could you please specify what is the current maximum number of models cesium.ion can process?
3. Is there a restriction on the number of models for different pricing plans?

**Comment by OmarShehata** [comment]
@Ring-r this is a bug on our end. This job failed but the error is not reported. In general, (Cesium ion has a job timeout of 24 hours, so any job that lasts longer than that and has not error'ed is a bug). There is no difference in terms of number of models or time for different pricing tiers.

We'll need to investigate more to determine whether or not this bug is caused by the number of files.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
