### ISSUE TITLE
Tiling issue with asset id: 1

### ISSUE THREAD

**Issue by hyunjiklee** [AnalyticalGraphicsInc/cesium-ion-community#332]
<Please provide a short summary of your data.>

**Comment by OmarShehata** [comment]
Hey @hyunjiklee  - that asset ID seems to be incorrect (asset ID 1 is Cesium World Terrain which is included in your account by default). Can you provide a screenshot if what you're seeing?

**Comment by hyunjiklee** [comment]
Thank you for your comment. I am checking the problem of my model

**Comment by OmarShehata** [comment]
I'm going to close this for now but if you have any more info @hyunjiklee feel free to follow up here or on the community forum: https://community.cesium.com/.
