### ISSUE TITLE
Tiling issue with asset id: 114251

### ISSUE THREAD

**Issue by thailekha** [AnalyticalGraphicsInc/cesium-ion-community#333]
![Screenshot from 2020-06-22 11-35-19](https://user-images.githubusercontent.com/10671610/85317896-6021e580-b47c-11ea-8b02-1d70d4051ec2.png)

The asset was uploaded on 18/6/2020. Some more error logging I got when streaming the asset on my web app:
![Screenshot from 2020-06-22 10-17-24](https://user-images.githubusercontent.com/10671610/85318145-b68f2400-b47c-11ea-8bc4-5de4e8f6325b.png)
![Screenshot from 2020-06-22 10-19-20](https://user-images.githubusercontent.com/10671610/85318151-b858e780-b47c-11ea-85cc-75f021074d01.png)

I've generated a token for my account instead of using the default token so the following input might can be irrelevant, but I notice that the assets I uploaded to Ceisum prior to the change on 2020-06-12 render just fine
![Screenshot from 2020-06-22 10-22-44](https://user-images.githubusercontent.com/10671610/85318261-e4746880-b47c-11ea-84d0-c160841ba2bf.png)

**Comment by OmarShehata** [comment]
Can you tell me your username or email associated with your account?

**Comment by thailekha** [comment]
My username: thai.le
Email: thai.le@sedsystems.ca
Thanks in advance for looking into this!

**Comment by OmarShehata** [comment]
I think this should be fixed now. Can you try re-uploading your asset to confirm?

**Comment by thailekha** [comment]
Thanks! What was the problem? Was it a bug in the enhancement process and will it happen again?

My web app uploads assets to Cesium depending on the users' interaction. So there won't be just the asset 114251. And it will be a hassle if the bug happens again. I just double-checked and things are working for now though.

**Comment by OmarShehata** [comment]
We're still investigating this issue to make sure it does not happen again. I'll post here again once we have an update.

**Comment by OmarShehata** [comment]
We have confirmed that this was a bug introduced with a recent deployment. We've verified and fixed the issue. Thank you for reporting this!

**Comment by kbratsy** [comment]
Hi, I have the same problem. I am getting the same error.
Can you please fix my account too?
Account Information:
Username: kbratsy
e-mail: atasoy.kubraa@hotmail.com
@OmarShehata

**Comment by kbratsy** [comment]
Hi, I have the same problem. I am getting the same error.
Can you please fix my account too?
Account Information:
Username: kbratsy
e-mail: atasoy.kubraa@hotmail.com
@OmarShehata

![Error](https://user-images.githubusercontent.com/34754399/99250932-92faba80-281d-11eb-9e3f-00b22959e4c3.PNG)
![Error2](https://user-images.githubusercontent.com/34754399/99250930-92622400-281d-11eb-9127-6b57cdd01932.PNG)
