### ISSUE TITLE
Allow positioning pre-tiled 3D Tiles

### ISSUE THREAD

**Issue by wujie-gis** [AnalyticalGraphicsInc/cesium-ion-community#334]
Asset ID 116432. Hello, the function of correcting the position cannot be realized, what is the reason?  
“Adjust Tileset Location”

**Comment by OmarShehata** [comment]
Right now only 3D Tiles created with Cesium ion can be repositioned with that tool. We're considering allowing pre-tiled 3D Tiles to be moved as well. It may partially require the tool generating the 3D Tiles to provide some additional metadata that ion can read.

What did you use to generate this 3D Tileset?

**Comment by wujie-gis** [comment]
cesiumlab,I used the 3D Tiles generated by this slicing tool to successfully transform the position on cesium。

**Comment by hyunjiklee** [comment]
Thank you for your kindness!!

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
