### ISSUE TITLE
Tiling issue with asset id: 116608

### ISSUE THREAD

**Issue by okansafak** [AnalyticalGraphicsInc/cesium-ion-community#335]
I can not upload cesium 3d tiles zip data that export from agisoft. what is the problem?
![cesium](https://user-images.githubusercontent.com/13871403/85563955-868b8080-b636-11ea-9ce8-6071255db95e.png)

**Comment by OmarShehata** [comment]
@okansafak the ZIP file you uploaded is a pre-tiled 3D Tileset, so you need to selected "3D Tiles" as the format when uploading.

If you'd like to use Cesium ion's tiling pipeline for tiling your models, you'll need to export the source model (as OBJ or glTF etc), upload that to Cesium ion and select "3D Capture" as the upload type.
