### ISSUE TITLE
Tiling issue with asset id: 117718

### ISSUE THREAD

**Issue by Kellollo** [AnalyticalGraphicsInc/cesium-ion-community#336]
<Please provide a short summary of your data.>
![7e9b65c0a17a474897c85e587bffa2f3](https://user-images.githubusercontent.com/65897256/85924696-899ca000-b8c6-11ea-9c5e-cf73f808e232.jpeg)

**Comment by OmarShehata** [comment]
@Kellollo you uploaded a COLLADA model, with a `.gltf` file extension. This should have a `.dae` file extension. 

I see you're using SketchUp, have you tried using the Cesium ion SketchUp plugin? https://cesium.com/blog/2019/06/06/sketchup-plugin/

Let me know if that works.
