### ISSUE TITLE
Tiling issue with asset id: 121396

### ISSUE THREAD

**Issue by yutaro-cloud** [AnalyticalGraphicsInc/cesium-ion-community#339]
After uploading CityGML, I got the following error.
> We're having trouble with your data.To help fix it, please open an issue in our Github repository.

Previously, if I registered the exact same data, I was able to register correctly.
Do you know why?
The data is as follows.

---
<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns:smil20="http://www.w3.org/2001/SMIL20/" xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/2.0" xmlns:pfx0="http://www.citygml.org/citygml/profiles/base/2.0" xmlns:luse="http://www.opengis.net/citygml/landuse/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:frn="http://www.opengis.net/citygml/cityfurniture/2.0" xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:tex="http://www.opengis.net/citygml/texturedsurface/2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:wtr="http://www.opengis.net/citygml/waterbody/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:app="http://www.opengis.net/citygml/appearance/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:gen="http://www.opengis.net/citygml/generics/2.0" xmlns="http://www.opengis.net/citygml/2.0"
	xsi:schemaLocation="http://www.opengis.net/citygml/2.0 http://schemas.opengis.net/citygml/2.0/cityGMLBase.xsd  http://www.opengis.net/citygml/appearance/2.0 http://schemas.opengis.net/citygml/appearance/2.0/appearance.xsd http://www.opengis.net/citygml/building/2.0 http://schemas.opengis.net/citygml/building/2.0/building.xsd http://www.opengis.net/citygml/cityfurniture/2.0 http://schemas.opengis.net/citygml/cityfurniture/2.0/cityFurniture.xsd http://www.opengis.net/citygml/vegetation/2.0 http://schemas.opengis.net/citygml/vegetation/2.0/vegetation.xsd http://www.opengis.net/citygml/generics/2.0 http://schemas.opengis.net/citygml/generics/2.0/generics.xsd http://www.opengis.net/citygml/transportation/2.0 http://schemas.opengis.net/citygml/transportation/2.0/transportation.xsd http://www.opengis.net/citygml/waterbody/2.0 http://schemas.opengis.net/citygml/waterbody/2.0/waterBody.xsd http://www.opengis.net/citygml/landuse/2.0 http://schemas.opengis.net/citygml/landuse/2.0/landUse.xsd http://www.opengis.net/citygml/relief/2.0 http://schemas.opengis.net/citygml/relief/2.0/relief.xsd">
	<gml:name>503010631</gml:name>
	<gml:boundedBy>
		<gml:Envelope srsName="WGS84">
			<gml:lowerCorner srsDimension="3">130.04023525 33.4678221669999 8</gml:lowerCorner>
			<gml:upperCorner srsDimension="3">130.0418175 33.4700428609999 8</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
<cityObjectMember><bldg:Building>
		<gen:stringAttribute name="meshcode1"><gen:value>5030</gen:value></gen:stringAttribute>
		<gen:stringAttribute name="meshcode2"><gen:value>503010</gen:value></gen:stringAttribute>
		<gen:stringAttribute name="meshcode3"><gen:value>50301063</gen:value></gen:stringAttribute>
		<gen:stringAttribute name="meshcode"><gen:value>503010631</gen:value></gen:stringAttribute>
<bldg:lod1Solid><gml:Solid><gml:exterior><gml:CompositeSurface>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.041771117 33.4687447189999 8</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 8</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 8</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 8</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 8</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.041771117 33.4687447189999 8</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 8</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 0</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 0</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 8</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.041783944 33.4687923329999 8</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 8</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 0</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 0</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 8</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.0418065 33.4687879719999 8</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 8</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 0</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 0</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 8</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.041793056 33.4687394719999 8</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 8</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 0</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 0</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 8</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
	<gml:surfaceMember><gml:Polygon gml:id="8"><gml:exterior><gml:LinearRing>
		<gml:pos>130.041771117 33.4687447189999 0</gml:pos>
		<gml:pos>130.041783944 33.4687923329999 0</gml:pos>
		<gml:pos>130.0418065 33.4687879719999 0</gml:pos>
		<gml:pos>130.041793056 33.4687394719999 0</gml:pos>
		<gml:pos>130.041771117 33.4687447189999 0</gml:pos>
	</gml:LinearRing></gml:exterior></gml:Polygon></gml:surfaceMember>
</gml:CompositeSurface></gml:exterior></gml:Solid></bldg:lod1Solid></bldg:Building></cityObjectMember>
</CityModel>
---

**Comment by OmarShehata** [comment]
I don't think it's an issue with your data, there's an error on our side that we're investigating now.

**Comment by OmarShehata** [comment]
@yutaro-cloud this issue has been fixed. If you re-upload your asset it should work now. Can you confirm it works for you?

**Comment by yutaro-cloud** [comment]
@OmarShehata   Thank you very match!!!!
I was able to register correctly.
I didn't know if it was a "data" problem or a "Cesium ion" problem, so I was very worried.
Thank you very match!!!!
