### ISSUE TITLE
Tiling issue with asset id: 121430

### ISSUE THREAD

**Issue by ZENUAV** [AnalyticalGraphicsInc/cesium-ion-community#340]
It's a geotiff exported from DroneDeploy.
I've done loads of these, this one wont process?
It's is one of the larger ones though?

**Comment by OmarShehata** [comment]
I don't think it's an issue with your data, there's an error on our side that we're investigating now.

**Comment by ZENUAV** [comment]
Thanks, let me know when to try again.

Jason

Sent from my iPhone

On 8 Jul 2020, at 13:59, Omar Shehata <notifications@github.com> wrote:

﻿

I don't think it's an issue with your data, there's an error on our side that we're investigating now.

**Comment by OmarShehata** [comment]
@ZENUAV the issue has been fixed now, we've restarted all the affected jobs. This job should be complete now.
