### ISSUE TITLE
AssetId: 120610  - Uploading a geotiff throws an error

### ISSUE THREAD

**Issue by naththeprince** [AnalyticalGraphicsInc/cesium-ion-community#341]
Tried to upload a geo-tiff which is downloaded from MAXAR SecureWatch - GetMap api. Trying to use this image on Cesium as an asset, created an asset from ION portal and REST API, in both the cases I see an error like this

![Screenshot 2020-07-09 at 1 05 50 PM](https://user-images.githubusercontent.com/3014054/87010982-f0825900-c1e4-11ea-8016-45438c7177fa.png)

This .zip file has the .tif file.
[geoserver-GetMap.tif.zip](https://github.com/CesiumGS/cesium-ion-community/files/4895226/geoserver-GetMap.tif.zip)

Maxar SecureWatch GetMap https://gcs-docs.s3.amazonaws.com/SecureWatch/en-us/Miscellaneous/DevGuides/WMS/WMS_Map.htm#

**Comment by OmarShehata** [comment]
Hey @naththeprince , the GeoTIFF you uploaded does not contain a defined spatial reference system, so Cesium ion can't place it in the correct place on the globe. If there's a way to download a version of this with the additional metadata that'd work.

It looks like the documentation you linked to from Maxar shows they have a WMS url. You can load this directly in CesiumJS, see: https://sandcastle.cesium.com/index.html?src=Web%20Map%20Service%20(WMS).html. 

If you have any follow up questions, please see the Cesium community forum: https://community.cesium.com/. That'll be the fastest way to get an answer.
