### ISSUE TITLE
GeoCoder unable to find certain addresses

### ISSUE THREAD

**Issue by Stephen-Haynes** [AnalyticalGraphicsInc/cesium-ion-community#342]
The geocoder tool is unable to find addresses that exist within Google maps, and yet is able to find addresses nearby. For example:

1300 Martin Luther King Jr Dr, Allentown PA, USA cannot be found, and no results are returned even from within the same city. This is the address of the county water filtration plant.

Here is an image of the returned results:
![image](https://user-images.githubusercontent.com/44399234/87607561-f629f280-c740-11ea-87e7-f7f83ee6bb1c.png)

1350 Martin Luther King Jr Dr, Allentown PA, USA does work with the GeoCoder as expected, and the autocomplete quickly identifies it.

This is only one example but I've encountered numerous other address omissions in long developed areas, is this due to incomplete data in the geocoder geoJSONs or is there a way to allow nearby number addresses to be included in search results if they are relevant. It seems to me that the search should be weighted country, state, street, number to provide the most accurate results given incomplete data in the database.

**Comment by OmarShehata** [comment]
Thanks for reporting @Stephen-Haynes. This is something we'd like to improve in Cesium ion, both in terms of updating the available address data as well as overall better filtering/ordering of the results.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/improve-cesium-ions-geocoder/10520
