### ISSUE TITLE
assetsID:124270 upload 3dtiles zip converted by cesiumlab only show the boundingVolume.

### ISSUE THREAD

**Issue by lxydft** [AnalyticalGraphicsInc/cesium-ion-community#345]
i converted osgb file to 3dtiles by cesiumlab. it is normal at the project. i uploaded a zip file in ion.I confirmed the tileset.json when I uploaded it.I'm not sure what documents are missing.

**Comment by OmarShehata** [comment]
Thanks for reporting @lxydft . I believe this is a bug on our end. We'll investigate and update this issue with more information.

**Comment by lxydft** [comment]
Thanks for your quick response.

**Comment by OmarShehata** [comment]
So this issue is triggered due to the "+" characters in the filenames. You can workaround this for now by removing those characters from the filenames and tileset.json. 

There's some more discussion on this here: https://github.com/CesiumGS/3d-tiles-validator/issues/208

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
