### ISSUE TITLE
Tiling issue with asset id: 126810

### ISSUE THREAD

**Issue by dabenhuang** [AnalyticalGraphicsInc/cesium-ion-community#348]
We're having trouble with your data. To help fix it, please open an issue in our Github repository.

If you don't have a GitHub account, email support@cesium.com with the asset ID: 126810.

**Comment by OmarShehata** [comment]
@dabenhuang you need to select "3D Capture" when uploading since this is a photogrammetry model. Let me know if that doesn't work!

**Comment by dabenhuang** [comment]
Thank you. I'll try

**Comment by dabenhuang** [comment]
> @dabenhuang，由于是摄影测量模型，因此上传时需要选择“ 3D Capture”。让我知道那是否行不通！

Thank you. I'll try
