### ISSUE TITLE
Tiling issue with asset id: 127979

### ISSUE THREAD

**Issue by TJPovey** [AnalyticalGraphicsInc/cesium-ion-community#349]
Uploaded a zip file containing several .obj files generated from a combining a point cloud model with a photogrammetry model. 
Originally uploaded as a 3D Model by accident, this did upload and was tiled but lower LOD was skipped. 
The error came when I uploaded as a 3D capture. Uploaded fine but failed on tiling.

**Comment by OmarShehata** [comment]
This has now been fixed!

Also, we're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. So for any follow up questions, please post on the community forum!
