### ISSUE TITLE
Ability to specify SRS for CityGML files

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#35]
In some cases, CityGML files do not specify a spatial reference system (SRS) which is required for any viewer visualize or convert the data.  We could deal with this in ion in 3 ways:

1. Detect a missing SRS as part of the upload process.  This should be possible for small files, but may prove difficult for mult-gigabyte citygml files (we'll have to experiment with how fast the browser can scan the file).  We can detect it on the server either way.

2. Allow the user to specify or override the SRS through the UX.  Our offline tools can already do this, we just need to expose it.  This can happen pre-upload.

3. If data without an SRS is uploaded to the server (either because we failed to detect it client side or because it came in via the REST API outside of our control) we can let the set the SRS after-the-fact and then reconvert the data.

**Comment by OmarShehata** [comment]
Places this came up:

* An unrecognized SRS came up in this issue: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/147. The suggested workaround was to use an EPSG based SRS.
* Ungeoreferenced CityGML fails to tile https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/57

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're interested in this feature, please open a new topic in the community forum!
