### ISSUE TITLE
maximumHeight doesn't work in viewer.flyTo

### ISSUE THREAD

**Issue by Mirror-Yu** [AnalyticalGraphicsInc/cesium-ion-community#350]
Dear Cesium Team

dataSource.entity of the height is undefind, so I use the maximumHeight ,but the maximumHeight doesn't work in viewer.flyTo

Any idea how to solve this problem?

Thank you.

**Comment by OmarShehata** [comment]
Can you post a Sandcastle of your issue? See: https://community.cesium.com/t/how-to-share-custom-sandcastle-examples/9828
