### ISSUE TITLE
Tiling issue with asset id: 134445

### ISSUE THREAD

**Issue by pepocho08** [AnalyticalGraphicsInc/cesium-ion-community#351]
Hi,

I had an issue while I was trying to updload my 3D Layer to Cesium ION. The Layer ID is  134445  

Is a GML zipped.

Thank you so much,

Pep

Pep Estelrich
CBRE Spain | Business Analytics
Edificio Castellana 200 | Paseo de la castellana, 202. Planta 6 | 28046 Madrid
Sigue a CBRE España en 
Twitter @CBRE_ES | Youtube | Blog Inmotendencias en Expansion.com | LinkedIn

**Comment by OmarShehata** [comment]
It looks like this CityGML does not have a valid spatial reference system.

What software did you use to export this? Or what are you currently using to visualize it?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

If you're still having issues here, please post on the community forum!
