### ISSUE TITLE
S3 and createReadStream objects not defined

### ISSUE THREAD

**Issue by aryanxk02** [AnalyticalGraphicsInc/cesium-ion-community#357]
I was trying out Cesium ion Rest API, while going through its documentation and while trying to run index.js, the above objects from AWS and fs turned out to be not defined in the terminal. Shall I fix the bug and make a PR. 

```
console.log('Asset created. Uploading Reichstag.zip');
    const uploadLocation = response.uploadLocation;
    const s3 = new S3({
        apiVersion: '2006-03-01',
        region: 'us-east-1',
        signatureVersion: 'v4',
        endpoint: uploadLocation.endpoint,
        credentials: new AWS.Credentials(
            uploadLocation.accessKey,
            uploadLocation.secretAccessKey,
            uploadLocation.sessionToken)
    });
```
```
    await s3.upload({
        Body: createReadStream(input),
        Bucket: uploadLocation.bucket,
        Key: `${uploadLocation.prefix}Reichstag.zip`
    }).on('httpUploadProgress', function (progress) {
        console.log(`Upload: ${((progress.loaded / progress.total) * 100).toFixed(2)}%`);
    }).promise();
```
Also I had one question, how exactly do I install package.json and package-lock.json in my directory?

**Comment by aryanxk02** [comment]
Okay I get it, I probably might have missed accessing it from the respective modules.
Mainly because I tried importing these modules by:
```
 import { S3, Credentials } from 'aws-sdk';
 import { createReadStream } from 'fs';
 import request from 'request-promise';
```

**Comment by shehzan10** [comment]
@aryanxk02 Thanks for the update. Has that resolved your issue or are you still seeing something similar?

You can copy the `tutorials/rest-api` directory to your project under the Apache 2.0 license.

**Comment by aryanxk02** [comment]
@shehzan10 it was my mistake, I actually didn't see the errors in my code! :)
