### ISSUE TITLE
is it only working with the Reichstag file ? 

### ISSUE THREAD

**Issue by badoubadou** [AnalyticalGraphicsInc/cesium-ion-community#358]
If I change the Reichstag file for the House.laz file, then I get : "ion detected a problem with the uploaded data".
In the asset page I have : We were unable to process your data due to the following issue:
Error: None of the source data files you uploaded are applicable for creating a 3D Tiles asset. You can see a list of supported formats in the [Tiler Data Types and Formats guide](https://cesium.com/learn/3d-tiling/tiler-data-formats/).
Read about what [data formats are supported](https://cesium.com/learn/3d-tiling/tiler-data-formats/) on Cesium ion.
If I upload directly to the asset page on cesium the same file, it's working fine.

**Comment by mramato** [comment]
@badoubadou you also need to change the `options.sourceType` from `CITYGML` to `POINT_CLOUD`. If all you did was change the sample to upload a laz file, it still thinks you are trying to tile from CityGML as the source format.

**Comment by badoubadou** [comment]
@mramato ah my bad, I overlooked the source type. thanks.
