### ISSUE TITLE
Cesium Custom terrain stuck at tiling 5% (.tif extension)

### ISSUE THREAD

**Issue by Saradhaa-Navifly** [AnalyticalGraphicsInc/cesium-ion-community#360]
Hello,
I am facing issues with Custom cesium terrain when uploading it as .tif extension its not executing and is stuck at tiling 5% even when we upload multiple times. Assest ID is 1387430. I have used World terrain as base Terrain

**Comment by shehzan10** [comment]
Hi @Saradhaa-Navifly - Please reach out via the community forum for issues with Cesium ion tiling. https://community.cesium.com/c/cesium-ion/9
