### ISSUE TITLE
Support for zip file uploads

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium-ion-community#37]
ion has support for uploading files and folders, but it would be convenient to upload a zip file for tiling.

Mentioned here: https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/36#issuecomment-427249880

**Comment by mramato** [comment]
ion now supports zip uploads. You can read all about it here: https://cesium.com/blog/2019/03/07/zip-uploads/
