### ISSUE TITLE
GeoTIFF of Antarctica not rendered as expected

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#38]
My asset (id = 7541) is not being rendered as grayscale image as expected.  Here it is as rendered in QGIS

![image](https://user-images.githubusercontent.com/4126790/46962890-49ee4000-d072-11e8-995c-69d21c5f92a2.png)

and in Sandcastle preview

![image](https://user-images.githubusercontent.com/4126790/46963313-545d0980-d073-11e8-8131-25cab0dc58f1.png)

Parts of what I expected to see are visible around the edge of the circle (wherever that came from).

**Comment by hpinkos** [comment]
Thanks for reporting this @GatorScott!  We'll look into the problem and get back to you when we have more information.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
