### ISSUE TITLE
Support for IFC -> 3D Tiles

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#40]
Overall, this is something we've wanted to do for a while, but it was recently requested on the Cesium forum: https://groups.google.com/d/msg/cesium-dev/51C7HM4Vz6o/84RpbGLjBgAJ

**Comment by russellar4** [comment]
Supporting geo-referenced OBJ or FBX files would be a good start to supporting IFC.  As a lot of CAD software that exports IFC can also export 3D models in OBJ, etc.

Just a thought.

**Comment by TJPovey** [comment]
Any more news on this by any chance? This is required to retain the embedded properties of each element within the model, these can be lost when converting a BIM model to OBJ. 

If not i'll look into using ifcOpenShell toolkit, although this may prove difficult for models originally created in Revit - if we want to retain materials.

**Comment by OmarShehata** [comment]
@TJPovey it's something we'd like to support, but I don't have a timeline for this at the moment. 

Right now to get per-feature metadata when creating 3D Tiles on Cesium ion you would need to upload KML/COLLADA as described here https://github.com/CesiumGS/cesium-ion-community/issues/201#issuecomment-513325239 or CityGML.

**Comment by TJPovey** [comment]
Thanks @OmarShehata , i'll look into it

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
