### ISSUE TITLE
Support RVZ -> 3D Tiles

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium-ion-community#42]
Overall, this is something we've wanted to do for a while, but it was recently requested on the Cesium forum: https://groups.google.com/d/msg/cesium-dev/51C7HM4Vz6o/84RpbGLjBgAJ

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
