### ISSUE TITLE
Opacity control for using the model placement widget

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#43]
When moving models into location using the placement tool, it would be nice to be able to adjust the opacity of the model, so that it can be lined up easier with features of the underlying terrain model.

Please add an opacity control to adjust the transparency of the model, for the purpose of adjusting it's location and rotation.

**Comment by hpinkos** [comment]
Thanks for the suggestion @outsider787!  We were actually just talking about this yesterday.  We need to make some changes to CesiumJS to support changing the 3D Tiles opacity, but this is a feature we would like to add.

**Comment by OmarShehata** [comment]
I'd definitely like to see this as well! My current trick is to push the tileset height down as a way to easily see what's underneath without losing my place.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
