### ISSUE TITLE
Missing polygons

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#44]
I've created an asset in Cesium Ion, however upon close inspection (when you get up close to the model) there's many missing polygons.
http://construkted.com/cesium/FF_Statue_test-01/
If you get close to any of the statues in this model, you can see a good percentage of polygons missing.
The model is a 9 million polygon model.

How can I fix this?

**Comment by hpinkos** [comment]
@outsider787 is this what you're talking about?

![image](https://user-images.githubusercontent.com/3451886/47296390-19615580-d5e0-11e8-9733-691f3b4442a9.png)

Were these triangles in the source model?  Are you able to share the source model with us for testing?
Thanks!

**Comment by Construkted-Reality** [comment]
Hi,
The source model doesn't have any holes or missing triangles.
I've done a bunch of tests with various mesh sizes and decimated to various levels by different programs, I keep getting similar results. Missing polygons in the model.

The latest model I uploaded to Cesium Ion is assetId 8281. It's only a 1.4 million poly mesh, and exhibits the same behavior on the statues.
You can download the source model here: http://aonsen.homeip.net:8888/cesium/

**Comment by hpinkos** [comment]
Thanks for the info @outsider787!  One of our developers is working on fixing the problem, and we'll give you an update once the fix is live on cesium.com

**Comment by Construkted-Reality** [comment]
What is the problem? Does it have to do with really small triangles?
I don't see the problem happening in areas where the triangles are larger. Just where they are really small.

**Comment by hpinkos** [comment]
@outsider787 yes, I believe we had a check in our tiler that was incorrectly throwing out small triangles.

**Comment by likangning93** [comment]
@outsider787 a little more insight here, we ran into a lot of user data that had zero-area triangles, so we built the ability to automatically remove zero-area triangles into our tiler. The implementation had a bug that we found thanks to this issue, so thanks for your help!

**Comment by Construkted-Reality** [comment]
Glad I could help :)

Has a fix been implemented on the live site?

**Comment by hpinkos** [comment]
@outsider787 not quite yet, the fix is under review right now.  Once it is deployed we'll let you know and we'll close this issue.

**Comment by lilleyse** [comment]
Hi @outsider787, the fix is now deployed. I tested out your model and it looks great now.
