### ISSUE TITLE
Expose some 3D Tiles in the Asset Depot

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#45]
I think something that would be really cool for new users is having some nice examples of pre-tiled data on the asset depot. I was working on putting together some demos using Cesium's classification primitives, and having some assets I can pull from/test with would be really nice.

Sandcastle does have all these sample tilesets in the examples, but it would be nice if they were all in one place/can be accessed and searched in ion.

**Comment by hpinkos** [comment]
Thanks @OmarShehata!  Adding 3D Tilesets to the Asset Depot is definitely on our roadmap.

**Comment by OmarShehata** [comment]
This is part of a larger and ongoing effort now. We did recently add a point cloud of Montreal (see https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Montreal%20Point%20Cloud.html) and 6 high resolution photogrammetry of cities around the world (see https://cesium.com/blog/2019/06/04/vricon-partnership/). 

I'm closing this since it's not a specific feature/issue, but if anyone has ideas for what they'd like to see up there, or have data to share, definitely reach out to us!
