### ISSUE TITLE
Only one texture map is used

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#46]
In models that have multiple texture maps, it appears that only one texture map is used. The other texture maps are either ignored, or they are not mapped properly to the model.

**Model with 1x8k texture**
![1x8textures](https://user-images.githubusercontent.com/13057505/47564471-26898780-d8f3-11e8-8eb1-884d0a2c0665.JPG)

**Model with 2x8k textures** - (The ground has the correct texture, but the building and the trees have a messed up texture)
![2x8textures](https://user-images.githubusercontent.com/13057505/47564506-3bfeb180-d8f3-11e8-83e3-6dd3cec65303.JPG)

The  original obj and texture files I uploaded to Cesium Ion, can be downloaded here:
http://aonsen.homeip.net:8888/cesium/

**Comment by hpinkos** [comment]
Thanks for opening this issue @outsider787!  And thanks for sharing your obj.  Bug reports like this help make our tilers better for everyone.  Our graphics team is looking into the issue, and we'll give you an update when we have it.

**Comment by likangning93** [comment]
Hi @outsider787,

Thanks again for making your source data available to us!

Out of curiosity, what software was used to generate this model? I noticed that a lot of vertices in your model have texture coordinates beyond the [0, 1] range, which is kind of strange from a computer graphics perspective. We haven't seen this with output from other 3D scanning software like ContextCapture or AGISoft Photoscan.

**Comment by likangning93** [comment]
Ah whoops, just realized it's in the obj. This is `RealityCapture` output.

**Comment by Construkted-Reality** [comment]
That is correct. 
The files came straight out of Reality Capture version 1.0.3.4987.

I will redo this test using Agisoft Photoscan v 1.4.4 to see if the problem persists between programs.

**Comment by Construkted-Reality** [comment]
Verified that Photoscan v 1.4.4 doesn't exhibit this problem with multiple texture files. 
All files load just fine into Cesium Ion.

**Comment by lilleyse** [comment]
Hi @outsider787, this fix is also deployed. Thanks again!
