### ISSUE TITLE
Multiple 16k textures not working

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#47]
Cesium Ion is giving me an error when I upload a model with multiple 16k textures.
The model I uploaded has 4 x 16k textures.
I have tried other models that have 1 x 16k texture, and that works.
At the same time, I have uploaded 16 x 8k textures, (which is the same texture size as of 4 x 16k textures) and that also worked just fine.
![image](https://user-images.githubusercontent.com/13057505/47814351-d3b13500-dd23-11e8-806e-3954864dfdb4.png)

The model I'm trying to upload can be downloaded from:
http://aonsen.homeip.net:8888/cesium/RC-D02-21-5mil-4x16kTextures2.zip

**Comment by hpinkos** [comment]
Thanks for the bug report @outsider787!

@likangning93 can you take a look at this?

**Comment by Construkted-Reality** [comment]
Is there any progress on this issue?

**Comment by hpinkos** [comment]
@outsider787 no sorry, we haven't had a chance to look into this yet. I know @likangning93 would really like to fix it though!  We'll give you an update as soon as we have one.

**Comment by mramato** [comment]
@outsider787 I have good news.  We released a significant update to our photogrammetry tiler last night and it can now handle this model and many other models with large, scattered textures.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/1495196/49812030-7ea90b80-fd32-11e8-8afe-75c61d7f0748.png)

Thanks again for filing an issue and please let us know if if you run into any other problems.
