### ISSUE TITLE
Generate terrain or mesh from point clouds

### ISSUE THREAD

**Issue by whalleyms** [AnalyticalGraphicsInc/cesium-ion-community#49]
I'm trying to achieve better tree visualization for low-altitude (helicopter) simulation visualization. Since I can't input las files into ion as terrain I'm using the following process:

1. Download las files from the USGS NationalMap

2. Use las2las to keep only first returns:
     > las2las -v -i $1 -o filtered.las --first-return-only

3. Use las2ogr to create a shape files:
    > las2ogr -i filtered.las -o filtered.shp -f "ESRI Shapefile"

4. Use goal_rasterize to create a GeoTiff:
   > gdal_rasterize -3d -tr 1 1 filtered.dbf filtered.tif

5. Use gdalwarp to add the spatial reference set to the tif:
    > gdalwarp -s_srs '+proj=utm +zone=18 +datum=NAD83' -t_srs '+proj=utm +zone=18 +datum=WGS84' filtered.tif filteredFinal

6. Upload the final GeoTIff to ion.

The results look OK although I'm probably going to have to do some more tuning to improve the appearance.

Any ideas out there?

Thanks, Matt.

**Comment by lilleyse** [comment]
Hi @whalleyms

Another approach I came across is to convert LAS to TIFF using PDAL and GDAL:

https://stackoverflow.com/a/47718177.

I haven't tried it myself but it may help simplify those steps.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
