### ISSUE TITLE
Add the ability to "scale" the raster values during upload (gdal_translate)

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#5]
Hello, 

I tried to upload this GEOTIFF to Cesium ION:
http://drive-in.synaaps.com/telechargementdirect.php?refespace=3851&arbo=UHVibGlj&file=e7c482631ed18e60c9994cbaa66010ce&key=41660fcc121e88cc783e3e62a2069d86

The upload/processing steps work, but then the result is kind of flat ...:
![image](https://user-images.githubusercontent.com/1240481/40055608-d36df5b6-5848-11e8-8c0d-298b6a2a9235.png)

The data is actually not great, the raster values are between 0 and 183:
![image](https://user-images.githubusercontent.com/1240481/40055703-1d08f82e-5849-11e8-973e-6a55853dc1bc.png)

While the actual altitude is about 2000 meters. With GDAL, you can use gdal_translate (http://www.gdal.org/gdal_translate.html) to "re-scale" the raster values, with a command line like
```
gdal_translate MNT_PNRC_L93_projected.tif MNT_PNRC_L93_projected_scale.tif -scale 0 183 0 2000 -ot Float32
```

It would be nice to be able to set those values while importing to Cesium ION, instead of modifying the input data beforehand

Fabien

**Comment by hpinkos** [comment]
Thanks for opening all these issues @fnicollet! We really appreciate the feedback.  Most of the team is at the FOSS4G conference this week, but we'll take a closer look at everything to see what's going on soon.

**Comment by fnicollet** [comment]
Ah, I couldn't make it to the FOSS4G this year, too bad! There is no rush

**Comment by mramato** [comment]
@fnicollet Thanks for the use case.  This should be fairly straightforward to implement because we already provide scaling of terrain data via the `Height Unit` terrain option, it just doesn't allow users to specify custom scaling because we weren't sure how common data like this was in the wild.

The way it would work is you would tell us how pixel values map to meters.  So if 0-183 pixel value is really 0-2000 meters, you would specify a value of `10.92896174863388` (i.e. 183/2000).

Does that sound like it would satisfy your use case?

Thanks

**Comment by fnicollet** [comment]
A better solution would be to set both the min and max. Having a value
starting with 0 doesn't mean that the lowest altitude is actually 0? Might
be more generic

Le lun. 21 mai 2018 18:39, Matthew Amato <notifications@github.com> a
écrit :

**Comment by OmarShehata** [comment]
It is also possible to use CesiumJS's `terrainExaggeration` (see https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Terrain%20Exaggeration.html) to do this at runtime.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
