### ISSUE TITLE
Usage page showing 0 usage

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium-ion-community#54]
Reported by @Tugark in https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/20#issuecomment-427250960'

> I don't see any usage statistics yet. At least during the time of these comments (beginning of October), there should be some usage, since I was experimenting with CesiumION then.

**Comment by hpinkos** [comment]
@mramato this came up again recently.  Can you take a moment to look into it?  I wasn't able to reproduce this locally.  Could it be a network thing?

**Comment by mramato** [comment]
This is on the schedule for this project cycle.  We believe it's a scalability issue and that's why it only happens in production.

**Comment by Tugark** [comment]
Glad to hear you're working on it!

On a related note, I can't seem to view the usage statistics for the last year. Whenever I choose "Last year" on the usage statistics, I get an internal server error. Looking at the console, I see a 504 response from api.cesium.com; and I also get a CORS message, saying that api.cesium.com has been blocked from origin https://cesium.com.

**Comment by Whaat** [comment]
Any update on this issue?  Thanks

**Comment by OmarShehata** [comment]
Looks like a fix went out for this on March 20th. All logs should now be accessible. @Whaat are you still seeing issues? Feel free to follow up here or open a new issue with what you're seeing.
