### ISSUE TITLE
Tiling issue with asset id: 10240

### ISSUE THREAD

**Issue by muratkendir** [AnalyticalGraphicsInc/cesium-ion-community#56]
Data has been created by instructor in following web site in FME: 
(https://hub.safe.com/templates/citygml-create-solitaryvegetationobject-with-implicit-representation)

models are valid and final gml file created on EPSG:900913 coordinate system. I already opened citygml file with fzkviewer successfully. Do you know whats is wrong with this file definition?

**Comment by lilleyse** [comment]
Hi @muratkendir, thanks for the bug report. It does seem to be a valid CityGML file.

We'll update this issue once we figure out why processing failed.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
