### ISSUE TITLE
Tiling issue with asset id: 10574

### ISSUE THREAD

**Issue by hungdn580** [AnalyticalGraphicsInc/cesium-ion-community#58]
Can not upload dae file with texture to cesium ion!

**Comment by lilleyse** [comment]
Hi @hungdn580,

The file seems to have failed during geometry compression. I'll update this issue once we have a fix in place. Thanks!

**Comment by lilleyse** [comment]
Hi @hungdn580,

The problem has been fixed and asset 10574 has been corrected in your account.

Thanks again!
