### ISSUE TITLE
Tiling issue with asset id: 10877

### ISSUE THREAD

**Issue by firstgle** [AnalyticalGraphicsInc/cesium-ion-community#60]
Two DEM files have been uploaded, but Tiling failed. Please help me to fix this issue. 
Thanks a lot

**Comment by hpinkos** [comment]
Hello @firstgle,  our tiling team will take a look at this soon and give you an update.  Thanks!

**Comment by OmarShehata** [comment]
This tiles successfully on Cesium ion now, but I'm not sure if it looks quite right/if it has the right geolocation. 

Note that we're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. If you have any follow up questions, please post on the community forum!
