### ISSUE TITLE
Cesium visualization issue with asset id: 11542

### ISSUE THREAD

**Issue by Brunel119** [AnalyticalGraphicsInc/cesium-ion-community#64]
<Please provide a short summary of your data.> Hi I upload my .kmz file. The tiles process is Fine, but for the preview console says "We're having trouble with your data. To help fix it, please open an issue in our Github repository."

**Comment by hpinkos** [comment]
Thanks for opening up the issue @Brunel119.  We'll look into this soon and give you an update once we figure out what the problem is.

**Comment by Brunel119** [comment]
> Thanks for opening up the issue @Brunel119. We'll look into this soon and give you an update once we figure out what the problem is.

Thx alot.

**Comment by mramato** [comment]
@Brunel119 with the updates we put into place yesterday, this data now tiles successfully.  If you still have any questions or problems, please let us know.  Thanks again for filing an issue.
