### ISSUE TITLE
Feature Request: More Imagery Providers/Cesium ion as Key-Store

### ISSUE THREAD

**Issue by leylines** [AnalyticalGraphicsInc/cesium-ion-community#65]
Hi there,

I have the idea to use Cesium-ion to store all my auth-tokens and personal keys in a central place. This was originally posted in the cesium-dev-group (see below).

So in cesiumjs i just refer to the services that i get through ion as asset and just need one access-token (from cesium-ion). I already use this for bing (with my personal key), Mapbox (with my accessToken) and the ESRI-basemaps (without key) and would love to extend this to more services such as OpenWeatherMap (appid=mypersonalkey => OpenStreetMapImageryProvider), Stamen (without key => OpenStreetMapImageryProvider) and maybe others.

Thank you for your time,

Jörg

https://groups.google.com/forum/#!topic/cesium-dev/wii8Q4JVozs

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

This issue has been moved here: https://community.cesium.com/t/support-pre-tiled-wmts-tms-imagery-in-cesium-ion/10503
