### ISSUE TITLE
Image tiling issue for asset id: 11768

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#66]
Four of these images overlap in UTM and I expected the result to look similar to this:
![image](https://user-images.githubusercontent.com/4126790/49451287-dda7d700-f7ac-11e8-8668-5669607a56e1.png)

**Comment by mramato** [comment]
In ion it looks like there is black banding around the images, most likely due to nodata or transparency getting lost at some point in the tiling process. This should hopefully be a straightforward fix.

Thanks for submitting an issue.

**Comment by mramato** [comment]
Sorry the long delay here, but we deployed an update yesterday that fixed this issue. Thanks again for reporting.
