### ISSUE TITLE
Cesium visualization Question How to load texture with Obj

### ISSUE THREAD

**Issue by Brunel119** [AnalyticalGraphicsInc/cesium-ion-community#68]
I can upload obj file, it seems good but I can not load texture with my obj file. How can I fix it? thanks alot.

**Comment by hpinkos** [comment]
Hello @Brunel119,

You can add multiple files when you're creating an asset.  You can add files either by dragging/dropping them onto the window, or by using the 'Add files' button.  For drag/drop, you can drag the obj and texture files, or I often drag/drop a folder containing all of the files related to the model to easily add them all at once.
If you are unable to drag/drop, you can also click the `Add files` button as many times as you need to select all of the files necessary.

I hope this answers your question!  I'm going to close this issue, but if you have any follow up questions you can comment here and I'll be more than happy to help!

**Comment by mramato** [comment]
One thing I'll add here is that if you use the `Add files` button, then we lose directory structure which is important for many models.  This is unfortunately a browser limitation.  If your textures are in a different directory than your model, dragging and dropping the directory is the only way things are guaranteed to work.
