### ISSUE TITLE
Error Creating Cesium 3D Tile Asset

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium-ion-community#70]
From @bbehling-trimble in https://github.com/AnalyticalGraphicsInc/cesium/issues/7402

> Hello.
>
> I'm trying to create a Cesium ION asset using the FME Cesium ION Connector. When I go to my assets, this error is displayed:
>
> "We're having trouble with your data. To help fix it, please open an issue in our Github repository.
>
> If you don't have a GitHub account, email Sean at sean.lilley@cesium.com with the asset ID: 12136."
>
> Any idea what the issue is?

> I've also created a GML file and tried to create 3D tiles directly from the ION Asset page. Same error:
>
>"We're having trouble with your data. To help fix it, please open an issue in our Github repository.
>
>If you don't have a GitHub account, email Sean at sean.lilley@cesium.com with the asset ID: 12138."
>
>The GML can be viewed in QGIS. Its attached. (rename to .gml)
land_xml.txt

**Comment by lilleyse** [comment]
It looks like the failure is coming from lack of `LineStringSegment` support in the CityGML parser. @bbehling-trimble we'll let you know once we have a fix. Thanks!

**Comment by bbehling-trimble** [comment]
Hello @lilleyse 

Is there documentation available describing what geometry formats are supported by CityGML  parsers? 

Are LineStrings supported?

**Comment by lilleyse** [comment]
Hey @bbehling-trimble. Generally most object and node types are supported, including most triangular data, but line data like `LineStrings` and `LineStringSegment` are not and will be a bit of work to integrate into our triangle-centric pipeline. It might be easier to convert the vector data to another format like GeoJSON and load in Cesium directly. That is, until we have full vector tiling support in ion.

There is no documentation yet on the supported CityGML types, but that is a good suggestion and we'll get a list together.

**Comment by lilleyse** [comment]
See https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/78 for an asset using `LineString`.

**Comment by bbehling-trimble** [comment]
Thanks @lilleyse 

I started investigating vector data as 3D Tiles because we plan on loading datasets that could potentially be very large, to alleviate performance issues loading all the data at once. Can't wait till this fully supported.

Also, does Cesium JS viewer support CityGML lines? We did get a converter done in FME that outputs vector GML lines. However, we aren't seeing the geometries in the viewer and no errors are thrown. If you want, I can't move this question to CesiumJS.

**Comment by lilleyse** [comment]
Yeah vector tiling is a big thing on our list.

CesiumJS doesn't load CityGML or GML natively, but it can load GeoJSON or KML. See if one of those work.

**Comment by bbehling-trimble** [comment]
I know GeoJSON or KML will work, but loading huge data sets will cause some performance issues.

**Comment by bbehling-trimble** [comment]
What about the CityGML that is converted to BIM models? I followed the example on FME about creating building footprints. I know the Cesium tilers doesn't support this, but we did get 3D tiles converted with line strings in FME.

Should these BIM model lines be rendered in CesiumJS?

**Comment by lilleyse** [comment]
Yes, CesiumJS can render tiles that contain lines. The FME tileset ought to work.

Also a heads up - we're working on a new BIM/CAD tiler and are considering adding line support.

**Comment by bbehling-trimble** [comment]
So I converted the data b3dm tiles used from line strings to polygons. CesiumJS did not render the line strings, but did render the polygons.

**Comment by lilleyse** [comment]
Would you mind sending me those files? I can double check that the embedded glTFs are correct - any line primites would need to use mode 1 (`LINES`).

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!

**Comment by Wima7** [comment]
I have the same issue when i try to import citygml file on cesium using FME
![image](https://user-images.githubusercontent.com/88974102/191988932-94fd351c-f779-4d0f-9774-cdc916535924.png)
