### ISSUE TITLE
dae -> 3D tiles, missing textures

### ISSUE THREAD

**Issue by DFic** [AnalyticalGraphicsInc/cesium-ion-community#73]
Tried to convert dae model to 3D tiles, and it's working, except the textures are missing in resulting 3D tiles model.

Link to original thread at Cesium forum:
https://cesiumjs.org/forum/#!msg/cesium-dev/2IlV8hvDR3Q/oF6s0KvmCAAJ

**Comment by lilleyse** [comment]
Hi @DFic,

If you drag and drop both `medvedgrad1a.dae` and the `medvedgrad1a` texture folder onto the Upload Data page you should get a tileset with textures. Maybe only the .dae file was uploaded when you tried?

![picture](https://user-images.githubusercontent.com/915398/49910053-4a773d00-fe4f-11e8-92b7-66a565d722c5.PNG)

**Comment by DFic** [comment]
Thanks Sean, 
drag and drop is a solution for textures, I tried to use "open" for textures but then path was lost.

Just one more thing, noticed that 3D tiles models are bit darker then same glft models ( please see attached comparison image).
![glft_3dtiles_light](https://user-images.githubusercontent.com/24660983/49935497-72a78000-fed1-11e8-9d10-e7e71f555be6.jpg)

**Comment by lilleyse** [comment]
3D Tiles uses glTF 2.0 which has a different shading model than glTF 1.0 and may account for those differences.

To make the tileset brighter try setting [tileset.lightColor](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#lightColor). The default is `(1.5, 1.4, 1.2)`

**Comment by DFic** [comment]
Having a hard time finding a detailed reference about tileset.lightColor, especially about those three parameters.
General info only in https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileset.html?classFilter=cesium3dtileset#lightColor

pls, could u share a small code example?

**Comment by OmarShehata** [comment]
Try:

```
tileset.lightColor = new Cesium.Cartesian3(3, 2.8, 2.4)
```

Does that make it brighter for you?

**Comment by lilleyse** [comment]
I'm going to close this for now. @DFic let us know if you still have any questions.

**Comment by shueseman-skyline** [comment]
This doesn't seem to work, tried in Cesium versions 1.53 and 1.56.  I, too, am looking to "brighten" up a tileset.  You can test in your sandcastle (https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Photogrammetry.html) and add the line above (tileset.lightColor = new Cesium.Cartesian3(3, 2.8, 2.4);) into the sandcastle

**Comment by OmarShehata** [comment]
@lilleyse can correct me if I'm wrong here, but I _think_ this is because photogrammetry tilesets use an unlit material so that they are unaffected by light sources in the scene.

If you try this on the 3D Tiles interior model here it works:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Interior.html

Try:

```
var lightIntensity = 20;
var sunColor = new Cesium.Cartesian3(3, 2.8, 2.4);

Cesium.Cartesian3.multiplyByScalar(sunColor, lightIntensity, tileset.lightColor) 
```

I know you can apply styles https://github.com/AnalyticalGraphicsInc/cesium/pull/7255 to photogrammetry tilesets but that won't help make it brighter though.
