### ISSUE TITLE
.jgw not recognized as world file for .jpg

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium-ion-community#75]
Ion did not recognize the georeferencing file, .jgw, I uploaded with a .jpg file.

**Comment by lilleyse** [comment]
Thanks @GatorScott. This is something we'd like to support and we'll use this issue to track our progress.

**Comment by mramato** [comment]
We actually already support this and other world files.  This problem turned out to be a hiccup in our production servers that has been addressed and the failed asset is now working properly.  Thanks again for the issue @GatorScott.
