### ISSUE TITLE
Tiling issue with asset id: 12609

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#77]
Opening on behalf of Sankin on the forum:

https://groups.google.com/d/msg/cesium-dev/OhGtTs0_zvU/5sk3UfRuBwAJ

The TIF file is also attached in the forum thread.

**Comment by lilleyse** [comment]
Thanks @OmarShehata. We'll update this issue as we look into it.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
