### ISSUE TITLE
Error Creating Asset ID: 12658

### ISSUE THREAD

**Issue by bbehling-trimble** [AnalyticalGraphicsInc/cesium-ion-community#78]
When trying to tile a GML road feature, error is returned from ION tiler. Asset ID is 12658

**Comment by lilleyse** [comment]
It looks like the CityGML uses `LineString` which is also not supported yet. I'm going to close this issue and link from https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/70 just to keep them closer together.
