### ISSUE TITLE
Add support for measuredHeight node in CityGML

### ISSUE THREAD

**Issue by agilliland** [AnalyticalGraphicsInc/cesium-ion-community#79]
I just tried creating an asset (12675) from a citygml file that is using epsg:4979 as its CRS and i'm getting completely flat buildings.  I'm curious if the tiling process is accurately identifying that the data is coming in epsg:4979 and making the necessary accommodations.

Just as a point of reference, when I open up the file in a simple viewer such as Azul the file itself looks fine ... 
![screen shot 2018-12-17 at 3 13 00 pm](https://user-images.githubusercontent.com/1987787/50121656-43b14700-020e-11e9-9da0-c83b026d0ed3.png)

**Comment by lilleyse** [comment]
Hm that's strange. Thanks for letting us know, we're going to look into it.

**Comment by lilleyse** [comment]
So it's not an EPSG issue. The problem is we don't yet support the `measuredHeight` node which extrudes the building footprints. We'll let you know once we add support for it.

**Comment by agilliland** [comment]
my apologies @lilleyse , I found an issue with my citygml which was causing the problem so this can be closed.

For the sake of clarity I should mention that the `measuredHeight` attribute of the building actually has nothing to do with the geometry of the solid representing the building being tiled, it's purely there for metadata.  When I generate my tiles in Ion I see `measuredHeight` as one of the properties, which is correct.  I don't believe `measuredHeight` should be used in the tiling process for extrusion though because the citygml already details the 3D solids for each building.

**Comment by lilleyse** [comment]
Ah thanks for the explanation @agilliland!
