### ISSUE TITLE
about pick each feature in the model

### ISSUE THREAD

**Issue by verybigzhouhai** [AnalyticalGraphicsInc/cesium-ion-community#80]
Hi,
I uploaded my model to ion, got the conversion result and can show it, I want to ask, how should I pick each feature in the model separately?
like this：
![image](https://user-images.githubusercontent.com/37999729/50140360-72e3b900-02df-11e9-8348-253dac82dfb0.png)
I chose bim when uploading the model.
![image](https://user-images.githubusercontent.com/37999729/50140451-b76f5480-02df-11e9-8afa-e91163c25a2e.png)
Thanks！

**Comment by lilleyse** [comment]
Hi @verybigzhouhai,

The current BIM/CAD tiler doesn't preserve features in the model but we're working on a brand new BIM/CAD tiler that will. We'll let you know once it's ready.

**Comment by verybigzhouhai** [comment]
Ok, thank you for your reply. How long does it take? I am choosing a suitable platform for my future system.

**Comment by lilleyse** [comment]
We don't have an exact estimate yet, but sometime early next year. Glad to hear your interest!
