### ISSUE TITLE
Expose option to Draco compress points

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium-ion-community#81]
ion currently does not Draco compress point clouds. The tilers can do this, but it's just not exposed as an option through the platform. This would be useful for compressing data, getting faster streaming etc.

If this is something you need for your workflow please comment or 👍 this issue.

**Comment by mramato** [comment]
After some offline discussion, we are going to turn draco compression on for all point clouds.  I'll keep that issue open until that happens.

**Comment by lilleyse** [comment]
Draco compression is now enabled for all point clouds.
