### ISSUE TITLE
Tiling issue with asset id: 13101

### ISSUE THREAD

**Issue by Construkted-Reality** [AnalyticalGraphicsInc/cesium-ion-community#83]
The model decimated by Polygon Cruncher (a polygon reduction tool).
The model is 12Mil polys and used 9 x 16k textures.

I don't understand why it's not tiling.

**Comment by lilleyse** [comment]
Thanks @outsider787, we're looking into why it failed.

**Comment by lilleyse** [comment]
Hi @outsider787, the problem has been fixed. If you re-upload the model now it should work.

I'm going to close the issue but please reopen if you have any problems.
