### ISSUE TITLE
Tiling issue with asset id: 13298

### ISSUE THREAD

**Issue by Yoonmyeongwoo** [AnalyticalGraphicsInc/cesium-ion-community#84]
I want to use my Data. Korea Seoul area(EPSG : 4326). The data is converted shp to gml file. but, it has trouble upload on cesium ion. I want to fix the data. Help me please.

**Comment by lilleyse** [comment]
Hi @Yoonmyeongwoo,

Cesium ion does not support plain GML files at the moment, only CityGML files. See https://cesium.com/docs/tutorials/uploading/ for the full list of supported formats.

Additionally ion does not have vector data support yet.
