### ISSUE TITLE
Tiling issue with asset id: 13142

### ISSUE THREAD

**Issue by JCTamayo18** [AnalyticalGraphicsInc/cesium-ion-community#85]
My Washington DC asset file (asset ID: 13142) has cause an issue.  The Collada file is aprox. 370 mb. Any suggestions to resolve this problem is greatly appreciated

**Comment by lilleyse** [comment]
Hi @JCTamayo18, we fixed this problem and will let you know once it's pushed to ion.

**Comment by JCTamayo18** [comment]
Thanks @lilleyse, looking forward to it

**Comment by lilleyse** [comment]
@JCTamayo18, this asset ended up being more problematic than we thought. We're still looking at it but we'd suggest exporting it as KML instead if you are able. KML/COLLADA will ensure that buildings are treated as separate features and preserve any metadata.

**Comment by JCTamayo18** [comment]
Sean,

Thank you for your time and assistance in this matter. As I mentioned, my goal is to have a 3D model of Washington DC, running on AWS, with the capability of adding different layers of building information  to the model. Do you have any idea what the cost would be to build this type of model?

JT

**Comment by lilleyse** [comment]
What are the different layers composed of? If they are visual layers like buildings vs. roads vs. utilities I could see each layer being a separate ion asset. Then a CesiumJS app could show/hide the assets.

Also let me know if you are able you are able to convert to KML/COLLADA instead of just COLLADA from CityEngine, it should both tile better and present better in the app.

**Comment by JCTamayo18** [comment]
Sean,

 

Initially the idea is to layer information that will identify the buildings; restaurants, hotel, coffee shops, etc…

 

Unfortunately, I do not have access to CityEngine. Please don’t waste any more time on trying to resolve the issue, I’ll try to get access to a better model.

 

Thanks

JT

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
