### ISSUE TITLE
Tiling issue with asset id: 13586

### ISSUE THREAD

**Issue by hanjie941** [AnalyticalGraphicsInc/cesium-ion-community#89]
I've uploaded 148 OBJ files with 1KB each. 

![image](https://user-images.githubusercontent.com/42261340/50808536-f706ea80-1339-11e9-9fd2-294e7b78d77f.png)

**Comment by lilleyse** [comment]
Thanks @hanjie941, this data set appears to be working with our latest unreleased tilers. We'll make sure to verify this when we push out the next ion update.

**Comment by lilleyse** [comment]
Hi @hanjie941,

Your data looks good now. Asset 13586 has been corrected in your account.
