### ISSUE TITLE
Uploading a simple KML with points doesn't show anything

### ISSUE THREAD

**Issue by fnicollet** [AnalyticalGraphicsInc/cesium-ion-community#9]
Hello,

I tried to upload the following 111Kb KML file (zipped for github upload):
[Guide_Nautique_M_diterran_e_France_Sud_et_Corse_Ports_et_Mouillages.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2005015/Guide_Nautique_M_diterran_e_France_Sud_et_Corse_Ports_et_Mouillages.zip)

The extent is recognized, but it doesn't show anything in the viewer:
![image](https://user-images.githubusercontent.com/1240481/40057771-833f96f6-584f-11e8-94dc-e06d6b298605.png)

It should show billboard with the images, such as this:
![image](https://user-images.githubusercontent.com/1240481/40057823-a6f8b2b2-584f-11e8-8124-26ed39db52b4.png)

Fabien

**Comment by fnicollet** [comment]
Here is another file which doesn't work, with a simple linestring
[Avoid_Kharva.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2005085/Avoid_Kharva.zip)

Fabien

**Comment by fnicollet** [comment]
Well, actually, the linestring is somehow visible but not clamped to the ground, so sometimes it goes underground:
![image](https://user-images.githubusercontent.com/1240481/40059255-f08f004e-5853-11e8-9b7d-21f5cad6a049.png)

Maybe a missing option to force the file to be clamped to the ground while importing?

**Comment by mramato** [comment]
We've created issue #130 as a general Vector tiling feature issue.  I'm going to close this but we'll comment here once vector tiling is available on ion.  Feel free to chime in on #130 if you have any thoughts.
