### ISSUE TITLE
Merge multiple types of source data into single tileset

### ISSUE THREAD

**Issue by xuncanzhe** [AnalyticalGraphicsInc/cesium-ion-community#90]
Does cesium ion support the integration of different types of 3D source data into one 3Dtiles?

**Comment by lilleyse** [comment]
Right now no, only source data of the same type can be merged together (e.g. all obj files or all CityGML files).

But this a good idea we might want to explore in the future.

**Comment by lilleyse** [comment]
I should also note that a CesiumJS app can load multiple 3D Tilesets at once, so each source data can be its own ion asset and they can be loaded together in the app.

However if you still need all the source data to be a single tileset we'd be curious to hear your use case.

**Comment by xuncanzhe** [comment]
Yes, we can load different ion assets through the program. But the ion asset is conceptually more like a virtualized object. If I can fuse all types of data together like a container, for example I publish an ion asset that contains all the data. Then an ion asset is more like a product.
This is just a personal point of view.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
