### ISSUE TITLE
Tiling issue with asset id: 13696

### ISSUE THREAD

**Issue by TWith2Sugars** [AnalyticalGraphicsInc/cesium-ion-community#91]
A KMZ output of a naviswork file.

**Comment by lilleyse** [comment]
Hi @TWith2Sugars,

We only support KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip)
