### ISSUE TITLE
Tiling issue with asset id: 13841

### ISSUE THREAD

**Issue by swtgeo** [AnalyticalGraphicsInc/cesium-ion-community#92]
<Please provide a short summary of your data.> These are OSGB datas

**Comment by lilleyse** [comment]
Hi @mrsun12, we don't support OSGB data yet. See [Uploading Data to ion](https://cesium.com/docs/tutorials/uploading/) for a full list of the supported formats.

**Comment by swtgeo** [comment]
ok, can i upload phototopography to cesium ion?

**Comment by lilleyse** [comment]
It depends on the input format. Our terrain tiler currently only supports raster data and our photogrammetry tiler expects either OBJ or COLLADA.

**Comment by swtgeo** [comment]
I see. Thank U !
