### ISSUE TITLE
Tiling issue with asset id: 14030

### ISSUE THREAD

**Issue by WilCodeBoer** [AnalyticalGraphicsInc/cesium-ion-community#94]
I've been trying to add Lidar data from https://data.gov.uk/dataset/8b007edd-a886-44ca-9fa0-2ee2efc1248d/lidar-composite-dsm-25cm all day and no matter what I do it always fails. If I use the default asc I get from downloading it it fails. If I convert the .asc  into a tiff it fails. Using the WMS server fails because of CORS. 

What do I do?

**Comment by lilleyse** [comment]
`gdal_info` reports:

```
Driver: GTiff/GeoTIFF
Files: testersr.tif
Size is 4000, 4000
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (333000.000000000000000,449000.000000000000000)
Pixel Size = (0.250000000000000,-0.250000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  333000.000,  449000.000) (Invalid angle,Invalid angle)
Lower Left  (  333000.000,  448000.000) (Invalid angle,Invalid angle)
Upper Right (  334000.000,  449000.000) (Invalid angle,Invalid angle)
Lower Right (  334000.000,  448000.000) (Invalid angle,Invalid angle)
Center      (  333500.000,  448500.000) (Invalid angle,Invalid angle)
Band 1 Block=4000x1 Type=Float64, ColorInterp=Gray
  NoData Value=-9999
```

Note the `Invalid angle` lines, this is causing the asset to fail.

Does anyone have suggestions for fixing this? I ran across https://gis.stackexchange.com/questions/54518/how-can-i-fix-badly-specified-geographic-coordinate-system-with-units-in-arc-sec which looks like a similar problem.

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

@WilCodeBoer if you're still having issues getting your data into Cesium ion, please post on the community forum and we can take another look here (if the LiDAR is available as LAS/LAZ files that would be worth trying).
