### ISSUE TITLE
Tiling issue with asset id: 14347

### ISSUE THREAD

**Issue by HuyQuoc** [AnalyticalGraphicsInc/cesium-ion-community#97]
My data is converted from OBJ to CityGML using FME 2018. The data can be displayed with FME Data Translator but this cannot be displayed in CesiumIon in 3DTiles format. 

I dont know what is problem. Please help me to fix it. Here is my 3D Sample Model: https://free3d.com/3d-model/19-low-poly-buildings-974347.html

**Comment by lilleyse** [comment]
Hi @HuyQuoc, we're missing support for some of the node types the CityGML file uses. We'll let you know once the data can be processed.

Until then, have you tried using ion to process the OBJ model?

**Comment by OmarShehata** [comment]
We're migrating the issues in this repository to consolidate questions, Cesium ion feature requests, and bug reports on the [Cesium community forum](https://community.cesium.com/), that way there'll be one place to search for answers. 

We're tracking this issue internally now. For any follow-up questions, please use the community forum!
