### ISSUE TITLE
Tiling issue with asset id: 14549

### ISSUE THREAD

**Issue by icbaagriculture** [AnalyticalGraphicsInc/cesium-ion-community#99]
Hi, I can't upload kmz file on Cesium. It gives below error:

We're having trouble with your data. To help fix it, please open an issue in our Github repository.

**Comment by lilleyse** [comment]
Hi @icbaagriculture 

We only support KML with model placemarks at the moment (KML/COLLADA). For a simple example see [MackyBldg.zip](https://github.com/AnalyticalGraphicsInc/cesium-ion-community/files/2674428/MackyBldg.zip)
